### ISSUE TITLE
Editorial issues.

### ISSUE THREAD

**Issue by Govind-cg** [greenplum-db/sre-test#100]
Page no 620.

Issue: misspelled.

Given statement.
Each partition is a separate physical file or set of tiles (in the case of column-oriented tables) on every
segment.

Correct statement:
Each partition is a separate physical file or set of **files** (in the case of column-oriented tables) on every
segment.

Page no 604.

Issue: misspelled.

Given statement.
In a scenario where a large number of workfiles are generated calculate the gp_vmem factor with this
formulat to account for the workfiles.

Correct statement:
In a scenario where a large number of workfiles are generated calculate the gp_vmem factor with this
**formulate** to account for the workfiles:

**Comment by fifthposition** [comment]
Docs story created.
