### ISSUE TITLE
Incorrect input file format.

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#101]
Page No : 665

Issue: Incorrect input file format, due to which command in step 4 fails (gpmovemirrors -i mirror_config_file).

The input file correct format as per gpmovemirrors --help is 

The input file should be a plain text file with the format:
`<old_address>|<port>|<datadir> <new_address>|<port>|<datadir>`

Given:
The gpmovemirrors input file has the following format:
contentID|address|port|data_dir new_address|port|data_dir

**Comment by fifthposition** [comment]
Docs story created.

**Comment by mperezfuster** [comment]
This is an issue for engineering: The -h option gives a description for -x, but -x doesn't appear in its synopsis.
