### ISSUE TITLE
Missing option in gpstart

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#103]
Page No : 775, 776

Issue: Option given in PDF Doc, missing in "gpstate -?"
[--skip-heap-checksum-validation]

--skip-heap-checksum-validation
During startup, the utility does not validate the consistency of the heap checksum setting
among the Greenplum Database master and segment instances. The default is to ensure
that the heap checksum setting is the same on all instances, either enabled or disabled.
Warning: Starting Greenplum Database without this validation could lead
to data loss. Use this option to start Greenplum Database only when it is
necessary to ignore the heap checksum verification errors to recover data or
to troubleshoot the errors.

**Comment by edespino** [comment]
Please note, this is a product issue and not a documentation issue. The online help content (`-h`) included with the product needs to be updated to match the documentation.

**Comment by niralis13** [comment]
Acknowledged

**Comment by niralis13** [comment]
https://github.com/greenplum-db/gpdb/pull/12138 adds the option in gpstart --help.
