### ISSUE TITLE
Statement contradicts the option.

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#106]
Page : 775

Below highlighted statement contradicts below option given in gpstart.
[--skip-heap-checksum-validation]

Note: Before you can start a Greenplum Database system, you must have initialized the system
using gpinitsystem. **Enabling or disabing heap checksums is set when you initialize the system
and cannot be changed after initialization.**

**Comment by fifthposition** [comment]
Docs story created.
