### ISSUE TITLE
Missing option in analyzedb 

### ISSUE THREAD

**Issue by Govind-cg** [greenplum-db/sre-test#107]
Page no 669

Issue: Option given in PDF Doc, missing in "analyzedb -?"
[ --debug ]

--debug
If specified, sets the logging level to debug. During command execution, debug level
information is written to the log file and to the command line. The information includes the
commands executed by the utility and the duration of each ANALYZE operation.ven in 

Page no 669

Issue: option not given in PDF Doc in analyzedb Synopsis. it is there in "analyzedb-?"
[--skip_root_stats]

--skip_root_stats  
This option is no longer used. Please remove it from your scripts.

**Comment by fifthposition** [comment]
Docs story created.
