### ISSUE TITLE
Statement missing High Availability configuration

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#109]
Page No: 775

Issue: Statement missing High Availability configuration.

Given Statement:
If the standby master is not accessible, you can start the system and troubleshoot standby master issues
while the system is available.

Complete/Better Statement:
If the standby master is not accessible, you can start the system and troubleshoot standby master issues, and re-initialize stand by master using gpinitstandby, while the system is available.

**Comment by fifthposition** [comment]
Docs story created.

**Comment by mperezfuster** [comment]
Update from PM:
_The statement re-initialize stand by master using gpinitstandby is not going to be true for all type of issues that can happen with standby.
I think we should keep the statement as is. NO CHANGE is needed._
We will be leaving this section unchanged.
