### ISSUE TITLE
"gpstate -s" segment output fields not in sync

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#112]
Page No : 779

Issue: "gpstate -s" segment output fields not in sync.

For example 
-  "Configuration reports status" as is present in online but missing in document.
- Many fields given in documentation are not present in online output of (gpstate -s) like below.
Change tracking data size
Estimated total data to synchronize
Data synchronized
Estimated resync progress with mirror
......etc

- Online: 
20210527:04:06:45:021099 gpstate:mdw_ipv4:gpadmin-[INFO]:-----------------------------------------------------
20210527:04:06:45:021099 gpstate:mdw_ipv4:gpadmin-[INFO]:-Segment Instance Status Report
20210527:04:06:45:021099 gpstate:mdw_ipv4:gpadmin-[INFO]:-----------------------------------------------------
20210527:04:06:45:021099 gpstate:mdw_ipv4:gpadmin-[INFO]:-   Segment Info
20210527:04:06:45:021099 gpstate:mdw_ipv4:gpadmin-[INFO]:-      Hostname                          = sdw1_ipv4
20210527:04:06:45:021099 gpstate:mdw_ipv4:gpadmin-[INFO]:-      Address                           = sdw1_ipv4
20210527:04:06:45:021099 gpstate:mdw_ipv4:gpadmin-[INFO]:-      Datadir                           = /data1/gpdb/primary/gpseg0
20210527:04:06:45:021099 gpstate:mdw_ipv4:gpadmin-[INFO]:-      Port                              = 4000
20210527:04:06:45:021099 gpstate:mdw_ipv4:gpadmin-[INFO]:-   Mirroring Info
20210527:04:06:45:021099 gpstate:mdw_ipv4:gpadmin-[INFO]:-      Current role                      = Primary
20210527:04:06:45:021099 gpstate:mdw_ipv4:gpadmin-[INFO]:-      Preferred role                    = Primary
20210527:04:06:45:021099 gpstate:mdw_ipv4:gpadmin-[INFO]:-      Mirror status                     = Synchronized
20210527:04:06:45:021099 gpstate:mdw_ipv4:gpadmin-[INFO]:-   Status
20210527:04:06:45:021099 gpstate:mdw_ipv4:gpadmin-[INFO]:-      PID                               = 7989
20210527:04:06:45:021099 gpstate:mdw_ipv4:gpadmin-[INFO]:-      Configuration reports status as   = Up
20210527:04:06:45:021099 gpstate:mdw_ipv4:gpadmin-[INFO]:-      Database status                   = Up
20210527:04:06:45:021099 gpstate:mdw_ipv4:gpadmin-[INFO]:-----------------------------------------------------
20210527:04:06:45:021099 gpstate:mdw_ipv4:gpadmin-[INFO]:-   Segment Info
20210527:04:06:45:021099 gpstate:mdw_ipv4:gpadmin-[INFO]:-      Hostname                          = sdw2_ipv4
20210527:04:06:45:021099 gpstate:mdw_ipv4:gpadmin-[INFO]:-      Address                           = sdw2_ipv4
20210527:04:06:45:021099 gpstate:mdw_ipv4:gpadmin-[INFO]:-      Datadir                           = /data1/gpdb/mirror/gpseg0
20210527:04:06:45:021099 gpstate:mdw_ipv4:gpadmin-[INFO]:-      Port                              = 5000
20210527:04:06:45:021099 gpstate:mdw_ipv4:gpadmin-[INFO]:-   Mirroring Info
20210527:04:06:45:021099 gpstate:mdw_ipv4:gpadmin-[INFO]:-      Current role                      = Mirror
20210527:04:06:45:021099 gpstate:mdw_ipv4:gpadmin-[INFO]:-      Preferred role                    = Mirror
20210527:04:06:45:021099 gpstate:mdw_ipv4:gpadmin-[INFO]:-      Mirror status                     = Streaming
20210527:04:06:45:021099 gpstate:mdw_ipv4:gpadmin-[INFO]:-   Replication Info
20210527:04:06:45:021099 gpstate:mdw_ipv4:gpadmin-[INFO]:-      WAL Sent Location                 = 2/57FCCF78
20210527:04:06:45:021099 gpstate:mdw_ipv4:gpadmin-[INFO]:-      WAL Flush Location                = 2/57FCCF78
20210527:04:06:45:021099 gpstate:mdw_ipv4:gpadmin-[INFO]:-      WAL Replay Location               = 2/57FCCD10 (616 bytes left)
20210527:04:06:45:021099 gpstate:mdw_ipv4:gpadmin-[INFO]:-   Status
20210527:04:06:45:021099 gpstate:mdw_ipv4:gpadmin-[INFO]:-      PID                               = 5025
20210527:04:06:45:021099 gpstate:mdw_ipv4:gpadmin-[INFO]:-      Configuration reports status as   = Up
20210527:04:06:45:021099 gpstate:mdw_ipv4:gpadmin-[INFO]:-      Segment status                    = Up
20210527:04:06:45:021099 gpstate:mdw_ipv4:gpadmin-[INFO]:-----------------------------------------------------

Document:
The following output fields are reported by gpstate -s for each segment:
Table 67: gpstate output data for segments
Output Data                  Description
==========================
Hostname            system-configured host name
Address            network address host name (NIC name)
Datadir            file system location of segment data directory
Port             port number of segment postgres database listener process
Current Role             current role of a segment: Mirror or Primary 
Preferred Role             role at system initialization time: Mirror or Primary
Mirror Status             status of a primary/mirror segment pair:
                                    Synchronized = data is up to date on both
                                    Resynchronization = data is currently being copied
                                     from one to the other
                                     Change Tracking = segment down and active
                                        segment is logging changes
Change tracking data             size when in Change Tracking mode, the size of
                                                 the change log file (may grow and shrink as
                                                  compression is applied)
Estimated total data to synchronize             when in Resynchronization mode, the estimated
                                                                       size of data left to synchronize
Data synchronized                 when in Resynchronization mode, the estimated
                                                size of data that has already been synchronized
Estimated resync progress with mirror             When in Resynchronization mode, the estimated
                                                                            percentage of completion

Estimated resync end time              when in Resynchronization mode, the estimated
                                                          time to complete
File postmaster.pid                   status of postmaster.pid lock file: Found or Missing
PID from postmaster.pid file              PID found in the postmaster.pid file
Lock files in /tmp              a segment port lock file for its postgres process
                                              is created in /tmp (file is removed when a segment
                                                 shuts down)
Active PID                            active process ID of a segment
Master reports status              as segment status as reported in the system catalog: Up or Down
Database status              status of Greenplum Database to incoming
                                          requests: Up, Down, or Suspended. A Suspended
                                          state means database activity is temporarily paused
                                          while a segment transitions from one state to
                                           another.

**Comment by fifthposition** [comment]
Docs story created.
