### ISSUE TITLE
gpstate "See Also" section not in sync

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#113]
Page No: 781

Issue: comma missing and Doc and Online not in sync.

Doc:
See Also
gpstart, gpexpandgplogfilter

Online:
gpstart, gplogfilter, gprecoverseg

**Comment by fifthposition** [comment]
@bala-cg I don't see a difference in the "See Also" list for the 6.15 PDF and the online 6.15 documentation at https://greenplum.docs.pivotal.io/6-15/utility_guide/ref/gpstate.html

**Comment by bala-cg** [comment]
@fifthposition, Sorry, with online I mean GP help (gpstate -?), and the issue is in GP pdf documentation 6.15 version.
![gpstate](https://user-images.githubusercontent.com/78151006/121373257-8cb86100-c95c-11eb-8860-54c62d4d49c1.JPG)
