### ISSUE TITLE
gpstop utility Issues

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#114]
1)
Page No : 781

Issue: Doc content not in sync with 

**Doc:**
gpstop --host host_name

**Gp Help:**
gpstop --host <segment_host_name>

2)
Page No : 781
Issue:  Description not in sync Doc to Online

**Doc:**
Description
The gpstop utility is used to stop the database servers that comprise a Greenplum Database system.
When you stop a Greenplum Database system, you are actually stopping several postgres database
server processes at once (the master and all of the segment instances). The gpstop utility handles the
shutdown of the individual instances. Each instance is shutdown in parallel.

The default shutdown mode (-M smart) waits for current client connections to finish before completing
the shutdown. If any connections remain open after the timeout period, or if you interrupt with CTRL-C,
gpstop lists the open connections and prompts whether to continue waiting for connections to finish, or to
perform a fast or immediate shutdown. The default timeout period is 120 seconds and can be changed with
the -t timeout_seconds option.

Specify the -M fast shutdown mode to roll back all in-progress transactions and terminate any
connections before shutting down.

With the -u option, the utility uploads changes made to the master pg_hba.conf file or to runtime
configuration parameters in the master postgresql.conf file without interruption of service. Note that
any active sessions will not pickup the changes until they reconnect to the database.

**Gp Help:**

The gpstop utility is used to stop the database servers that
comprise a Greenplum Database system. When you stop a Greenplum
Database system, you are actually stopping several postgres
database server processes at once (the master and all of the
segment instances). The gpstop utility handles the shutdown
of the individual instances. Each instance is shutdown in parallel.

By default, you are not allowed to shut down Greenplum Database
if there are any client connections to the database. Use
the -M fast option to roll back and terminate any connections
before shutting down. If there are any transactions in progress,
the default behavior is to wait for them to commit before
shutting down. Use the -M fast option to roll back open
transactions.

With the -u option, the utility uploads changes made to the
master pg_hba.conf file or to runtime configuration parameters
in the master postgresql.conf file without interruption of
service. Note that any active sessions will not pickup the
changes until they reconnect to the database.

3)
Page No: 782

Issue: Option name and Description not in Sync

**Doc:**
--host host_name
The utility shuts down the Greenplum Database segment instances on the specified host
to allow maintenance on the host. Each primary segment instance on the host is shut down
and the associated mirror segment instance is promoted to a primary segment if the mirror
segment is on another host. Mirror segment instances on the host are shut down.
The segment instances are not shut down and the utility returns an error in these cases:
• Segment mirroring is not enabled for the system.
• The master or standby master is on the host.
• Both a primary segment instance and its mirror are on the host.
This option cannot be specified with the -m, -r, -u, or -y options.
Note: The gprecoverseg utility restores segment instances. Run
gprecoverseg commands to start the segments as mirrors and then to
return the segments to their preferred role (primary segments).

**GP Help:**
--host <segment_host_name>

 Stop all segments on this host. Specify segment_host_name as
 it is displayed in gp_segment_configuration.

 This cannot be used together with `-m`, `-r`, `-u`, or
 `-y` options.

 This will only complete if failover segments are available.
 This will fail if the system doesn't have mirrors. It will also
 fail if the specified host has a master or standby master on
 it. It will also fail if the specified host has both a primary
 and its corresponding mirror on it, the same host.

4)
Page No : 782

Issue: Options description not in sync.

**Doc:**
-M immediate
Immediate shut down. Any transactions in progress are aborted.
This mode kills all postgres processes without allowing the database server to complete
transaction processing or clean up any temporary or in-process work files.

-M smart
Smart shut down. This is the default shutdown mode. gpstop waits for active user
connections to disconnect and then proceeds with the shutdown. If any user connections
remain open after the timeout period (or if you interrupt by pressing CTRL-C) gpstop lists
the open user connections and prompts whether to continue waiting for connections to
finish, or to perform a fast or immediate shutdown.

**GP help:**
-M immediate

 Immediate shut down. Any transactions in progress are aborted. This
 shutdown mode is not recommended, and in some circumstances can cause
 database corruption requiring manual recovery.

 This mode kills all postgres processes without allowing the database
 server to complete transaction processing or clean up any temporary or
 in-process work files.

-M smart

 Smart shut down. If there are active connections, this command
 fails with a warning. This is the default shutdown mode.

5)
Page No : 783

Issue: For option "-t timeout_seconds" default time mentioned is not in sync 120/600 Doc/GP help.

6)
Page No: 783

Issue: Options sequence not in Sync.

**Doc:**
-v
Displays detailed status, progress and error messages output by the utility.
-y
Do not stop the standby master process. The default is to stop the standby master.
-? | -h | --help
Displays the online help.
--version
Displays the version of this utility.

**GP Help:**
-v
 Displays detailed status, progress and error messages output
 by the utility.
--version
 Displays the version of this utility.
-y
 Do not stop the standby master process. The default is to stop
 the standby master.
-? | -h | --help
 Displays the online help.

6)
Page No: 783
Issue: Missing example in Doc, mentioned in Online help.

Stop all segments on a particular host, while keeping
other hosts up:
  gpstop --host sdw1

**Comment by fifthposition** [comment]
Docs story created.
