### ISSUE TITLE
pg_dumpall option "-r" fails

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#119]
Page No : 795

Issue: -r option fails, works with --roles-only, GP help has correct option.

**Doc**
-r | --roles-only
Dump only roles, not databases or tablespaces.

**GP Help:**
  --roles-only             dump only roles, no databases or tablespaces

[gpadmin@mdw_ipv4 ~]$ pg_dumpall  -r -f dump01.sql
-r option is not supported. Did you mean --roles-only or --resource-queues?
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ pg_dumpall  --roles-only -f dump01.sql
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$

**Comment by fifthposition** [comment]
Docs story created.

**Comment by mperezfuster** [comment]
It looks like this is an issue with all short options for all pg_* utilities:

```
$ pg_dumpall -h
pg_dumpall: option requires an argument -- h
Try "pg_dump --help" for more information.
$ pg_dump -h
pg_dump: option requires an argument -- h
Try "pg_dump --help" for more information.
```
Looks more like a Dev issue not Docs issue.

**Comment by bala-cg** [comment]
Hi @fifthposition,  "-h = help" will not be work for some utilities which has different meaning for -h option like for pg_dumpall and pg_dump "-h" option is " -h, --host=HOSTNAME      database server host or socket directory".

**Comment by mperezfuster** [comment]
@bala-cg sorry about that you are correct. Anyway the `pg_dumpall` help also identifies `-r` option as an option which does not work:

```
  -r, --roles-only             dump only roles, no databases or tablespaces
```

So the issue is still coming from the utility help.
