### ISSUE TITLE
"pg_restore -l " output seems be to from old GP vserion.

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#122]
This seems to be from old GP version.
As with 6.15 the postgresql version is 9.4 not 8.3.

- And new file looks as below.

;
; Archive created at Mon May 31 17:37:23 2021
;     dbname: foo
;     TOC Entries: 9
;     Compression: -1
;     Dump Version: 1.13-0
;     Format: CUSTOM
;     Integer: 4 bytes
;     Offset: 8 bytes
**;     Dumped from database version: 9.4.24
;     Dumped by pg_dump version: 9.4.24**
;
;
; Selected TOC Entries:
;
2433; 1262 84968 DATABASE - foo gpadmin
6; 2615 2200 SCHEMA - public gpadmin
2434; 0 0 COMMENT - SCHEMA public gpadmin
2435; 0 0 ACL - SCHEMA public gpadmin
1; 3079 12331 EXTENSION - plpgsql
2436; 0 0 COMMENT - EXTENSION plpgsql

**Comment by fifthposition** [comment]
Docs story created.
