### ISSUE TITLE
gpexpand utility issues

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#123]
1)
Page No : 712

Doc:
Expands an existing Greenplum Database across new hosts in the **system**.
Gp help:
Expands an existing Greenplum Database across new hosts in the **array**.

2)
Page No :712

Issue: All options are same, layout or description not in sync/

Doc:
gpexpand [{-f|--hosts-file} hosts_file]
| {-i|--input} input_file [-B batch_size]
| [{-d | --duration} hh:mm:ss | {-e|--end} 'YYYY-MM-DD hh:mm:ss']
**[-a|-analyze]**
[-n parallel_processes]
| {-r|--rollback}
| {-c|--clean}
[-v|--verbose] [-s|--silent]
[{-t|--tardir} directory ]
[-S|--simple-progress ]
gpexpand -? | -h | --help
gpexpand --version

GP help:
gpexpand
      [-f <hosts_file>]
      | -i <input_file> [-B <batch_size>] [-V] [-t segment_tar_dir] [-S]
      | {-d <hh:mm:ss> | -e '<YYYY-MM-DD hh:mm:ss>'}
        **[-analyze]** [-n <parallel_processes>]
      | --hba-hostnames
      | --rollback
      | --clean
[--verbose] [--silent]

gpexpand -? | -h | --help

gpexpand --version

3)
Page No : 712

Issue: Below part is present in Doc, and missing in Gp help under Prerequisites section.

Missing in GP help:
Note: These utilities cannot be run while gpexpand is performing segment initialization.
• gpbackup
• gpcheckcat
• gpconfig
• gppkg
• gprestore
Important: When expanding a Greenplum Database system, you must disable Greenplum
interconnect proxies before adding new hosts and segment instances to the system, and you must
update the gp_interconnect_proxy_addresses parameter with the newly-added segment
instances before you re-enable interconnect proxies. For information about Greenplum interconnect
proxies, see Configuring Proxies for the Greenplum Interconnect.
For information about preparing a system for expansion, see Expanding a Greenplum System in the
Greenplum Database Administrator Guide.

4)
Page No :713

Issue: Doc Description section not sync with GP help.

5)
Page No : 713

Issue : Below option missing in Doc present in GP help.

-V | --novacuum
 Do not vacuum catalog tables before creating schema copy.

**Comment by fifthposition** [comment]
Docs story created.
