### ISSUE TITLE
gpexpand is complete successfully gpstate still show in progress

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#124]
issue: gpexpand is complete successfully gpstate still show in progress

Issued below 2 commands, both are completed successfully.
gpexpand -i input_file
gpexpand -d 60:00:00

- Still gpstate say "Cluster Expansion                                         = In Progress"

[gpadmin@mdw_ipv4 ~]$ gpstate
20210601:17:38:42:031694 gpstate:mdw_ipv4:gpadmin-[INFO]:-Starting gpstate with args:
20210601:17:38:43:031694 gpstate:mdw_ipv4:gpadmin-[INFO]:-local Greenplum Version: 'postgres (Greenplum Database) 6.15.0 build commit:4e6288c9e9fca634b007a978fba3ce25aae26aed'
20210601:17:38:43:031694 gpstate:mdw_ipv4:gpadmin-[INFO]:-master Greenplum Version: 'PostgreSQL 9.4.24 (Greenplum Database 6.15.0 build commit:4e6288c9e9fca634b007a978fba3ce25aae26aed) on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 6.4.0, 64-bit compiled on Mar 10 2021 22:30:36'
20210601:17:38:43:031694 gpstate:mdw_ipv4:gpadmin-[INFO]:-Obtaining Segment details from master...
20210601:17:38:43:031694 gpstate:mdw_ipv4:gpadmin-[INFO]:-Gathering data from segments...
20210601:17:38:43:031694 gpstate:mdw_ipv4:gpadmin-[INFO]:-Greenplum instance status summary
20210601:17:38:43:031694 gpstate:mdw_ipv4:gpadmin-[INFO]:-----------------------------------------------------
20210601:17:38:43:031694 gpstate:mdw_ipv4:gpadmin-[INFO]:-   Master instance                                           = Active
20210601:17:38:43:031694 gpstate:mdw_ipv4:gpadmin-[INFO]:-   Master standby                                            = smdw_ipv4
20210601:17:38:43:031694 gpstate:mdw_ipv4:gpadmin-[INFO]:-   Standby master state                                      = Standby host passive
20210601:17:38:43:031694 gpstate:mdw_ipv4:gpadmin-[INFO]:-   Total segment instance count from metadata                = 8
20210601:17:38:43:031694 gpstate:mdw_ipv4:gpadmin-[INFO]:-----------------------------------------------------
20210601:17:38:43:031694 gpstate:mdw_ipv4:gpadmin-[INFO]:-   Primary Segment Status
20210601:17:38:43:031694 gpstate:mdw_ipv4:gpadmin-[INFO]:-----------------------------------------------------
20210601:17:38:43:031694 gpstate:mdw_ipv4:gpadmin-[INFO]:-   Total primary segments                                    = 4
20210601:17:38:43:031694 gpstate:mdw_ipv4:gpadmin-[INFO]:-   Total primary segment valid (at master)                   = 4
20210601:17:38:43:031694 gpstate:mdw_ipv4:gpadmin-[INFO]:-   Total primary segment failures (at master)                = 0
20210601:17:38:43:031694 gpstate:mdw_ipv4:gpadmin-[INFO]:-   Total number of postmaster.pid files missing              = 0
20210601:17:38:43:031694 gpstate:mdw_ipv4:gpadmin-[INFO]:-   Total number of postmaster.pid files found                = 4
20210601:17:38:43:031694 gpstate:mdw_ipv4:gpadmin-[INFO]:-   Total number of postmaster.pid PIDs missing               = 0
20210601:17:38:43:031694 gpstate:mdw_ipv4:gpadmin-[INFO]:-   Total number of postmaster.pid PIDs found                 = 4
20210601:17:38:43:031694 gpstate:mdw_ipv4:gpadmin-[INFO]:-   Total number of /tmp lock files missing                   = 0
20210601:17:38:43:031694 gpstate:mdw_ipv4:gpadmin-[INFO]:-   Total number of /tmp lock files found                     = 4
20210601:17:38:43:031694 gpstate:mdw_ipv4:gpadmin-[INFO]:-   Total number postmaster processes missing                 = 0
20210601:17:38:43:031694 gpstate:mdw_ipv4:gpadmin-[INFO]:-   Total number postmaster processes found                   = 4
20210601:17:38:43:031694 gpstate:mdw_ipv4:gpadmin-[INFO]:-----------------------------------------------------
20210601:17:38:43:031694 gpstate:mdw_ipv4:gpadmin-[INFO]:-   Mirror Segment Status
20210601:17:38:43:031694 gpstate:mdw_ipv4:gpadmin-[INFO]:-----------------------------------------------------
20210601:17:38:43:031694 gpstate:mdw_ipv4:gpadmin-[INFO]:-   Total mirror segments                                     = 4
20210601:17:38:43:031694 gpstate:mdw_ipv4:gpadmin-[INFO]:-   Total mirror segment valid (at master)                    = 4
20210601:17:38:43:031694 gpstate:mdw_ipv4:gpadmin-[INFO]:-   Total mirror segment failures (at master)                 = 0
20210601:17:38:43:031694 gpstate:mdw_ipv4:gpadmin-[INFO]:-   Total number of postmaster.pid files missing              = 0
20210601:17:38:43:031694 gpstate:mdw_ipv4:gpadmin-[INFO]:-   Total number of postmaster.pid files found                = 4
20210601:17:38:43:031694 gpstate:mdw_ipv4:gpadmin-[INFO]:-   Total number of postmaster.pid PIDs missing               = 0
20210601:17:38:43:031694 gpstate:mdw_ipv4:gpadmin-[INFO]:-   Total number of postmaster.pid PIDs found                 = 4
20210601:17:38:43:031694 gpstate:mdw_ipv4:gpadmin-[INFO]:-   Total number of /tmp lock files missing                   = 0
20210601:17:38:43:031694 gpstate:mdw_ipv4:gpadmin-[INFO]:-   Total number of /tmp lock files found                     = 4
20210601:17:38:43:031694 gpstate:mdw_ipv4:gpadmin-[INFO]:-   Total number postmaster processes missing                 = 0
20210601:17:38:43:031694 gpstate:mdw_ipv4:gpadmin-[INFO]:-   Total number postmaster processes found                   = 4
20210601:17:38:43:031694 gpstate:mdw_ipv4:gpadmin-[INFO]:-   Total number mirror segments acting as primary segments   = 0
20210601:17:38:43:031694 gpstate:mdw_ipv4:gpadmin-[INFO]:-   Total number mirror segments acting as mirror segments    = 4
20210601:17:38:43:031694 gpstate:mdw_ipv4:gpadmin-[INFO]:-----------------------------------------------------
20210601:17:38:43:031694 gpstate:mdw_ipv4:gpadmin-[INFO]:-   Cluster Expansion                                         = In Progress
20210601:17:38:43:031694 gpstate:mdw_ipv4:gpadmin-[INFO]:-----------------------------------------------------
[gpadmin@mdw_ipv4 ~]$

**Comment by fifthposition** [comment]
Docs story created.
