### ISSUE TITLE
gpfdist consolidated issues

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#125]
1)
Page No : 716

Issue: Synopsis section Doc content not matching GP help.

[-P last_http_port]
[--sslclean wait_time] ]
[-c config.yml]
[-s]

2)
Page No : 716

Issue: Description section not in sync Doc to GP help.

3)
Page No : 717

Issue: Below Option missing in  GP help.

-P last_http_port
The last port number in a range of HTTP port numbers (http_port to last_http_port,
inclusive) on which gpfdist will attempt to serve files. gpfdist serves the files on the
first port number in the range to which it successfully binds.

-s
Enables simplified logging. When this option is specified, only messages with WARN level
and higher are written to the gpfdist log file. INFO level messages are not written to the
log file. If this option is not specified, all gpfdist messages are written to the log file.

--sslclean wait_time
When the utility is run with the --ssl option, sets the number of seconds that the
utility delays before closing an SSL session and cleaning up the SSL resources after it
completes writing data to or from a Greenplum Database segment. The default value is 0,
no delay. The maximum value is 500 seconds. If the delay is increased, the transfer speed
decreases.
In some cases, this error might occur when copying large amounts of data: gpfdist
server closed connection. To avoid the error, you can add a delay, for example --
sslclean 5.

-c config.yaml
Specifies rules that gpfdist uses to select a transform to apply when loading or
extracting data. The gpfdist configuration file is a YAML 1.1 document.
For information about the file format, see Configuration File Format in the Greenplum
Database Administrator Guide. For information about configuring data transformation
with gpfdist, see Transforming External Data with gpfdist and gpload in the Greenplum
Database Administrator Guide.
This option is not available on Windows platforms.

4)
Page No : 719

Issue: Windows section present in  GP help missing in Doc.

Before Examples, Windows section is totally missed.

*****************************************************
RUNNING GPFDIST AS A WINDOWS SERVICE
*****************************************************

Greenplum Loaders allow gpfdist to run as a Windows Service.

Follow the instructions below to download, register and activate gpfdist
as a service:

1. Update your Greenplum Loader package to the latest version. This
   package is available from the EMC Download Center.
   (https://emc.subscribenet.com)

2. Register gpfdist as a Windows service:

   a. Open a Windows command window

   b. Run the following command:

     sc create gpfdist binpath= "path_to_gpfdist.exe -p 8081
       -d External\load\files\path -l Log\file\path"

   You can create multiple instances of gpfdist by running the same command
   again, with a unique name and port number for each instance, for
   example:

   sc create gpfdistN binpath= "path_to_gpfdist.exe -p 8082
     -d External\load\files\path -l Log\file\path"

3. Activate the gpfdist service:

   a. Open the Windows Control Panel and select
      Administrative Tools>Services.

   b. Highlight then right-click on the gpfdist service in the list of
      services.

   c. Select Properties from the right-click menu, the Service Properties
      window opens.

      Note that you can also stop this service from the Service Properties
      window.

   d. Optional: Change the Startup Type to Automatic (after a system
      restart, this service will be running), then under Service status,
      click Start.

   e. Click OK.

Repeat the above steps for each instance of gpfdist that you created. 

5)
Page No :719

Issue: "See Also" section not in sync Doc to  GP help.

**Comment by fifthposition** [comment]
Docs story created.
