### ISSUE TITLE
gpinitstandby consolidated issues

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#126]
Page No : 719

Issue: Description section has below mismatches (Doc to GP help).

Doc:
new standby master instance.
GP help: 
new standby master host.

Issue: Below statement missing in Gp help, present in Doc.

Important: If the gpinitstandby utility previously failed to initialize the standby master, you must
delete the files in the standby master data directory before running gpinitstandby again. The
standby master data directory is not cleaned up after an initialization failure because it contains log
files that can help in determining the reason for the failure.
If an initialization failure occurs, a summary report file is generated in the standby host directory /
tmp. The report file lists the directories on the standby host that require clean up.

Page No : 720

Issue: Options section, format and sequence not in sync(Doc to GP Help)

For example.
Doc:
--hba-hostnames boolean
Optional. Controls whether this utility uses IP addresses or host names in the
pg_hba.conf file when updating this file with addresses that can connect to Greenplum
Database. When set to 0 -- the default value -- this utility uses IP addresses when
updating this file. When set to 1, this utility uses host names when updating this file.
For consistency, use the same value that was specified for HBA_HOSTNAMES when the
Greenplum Database system was initialized. For information about how Greenplum
Database resolves host names in the pg_hba.conf file, see Configuring Client
Authentication.

GP help:
--hba-hostnames

 Optional. use hostnames instead of CIDR in pg_hba.conf

**Comment by fifthposition** [comment]
Docs story created.

**Comment by dyozie** [comment]
@bala-cg We're not seeing inconsistencies between the PDF and HTMl doc in these cases.  Can you confirm that you're looking at the version 6.16 online docs (https://greenplum.docs.pivotal.io/6-16/utility_guide/ref/gpinitstandby.html in this case)?  I think if you look at the 6.16 html and 6.16 pdf the same fixes are in place.

**Comment by bala-cg** [comment]
Hi @dyozie,

I am using 6.15 PDF doc, and Sorry for the confusion, the difference is between PDF Doc and GP help content.
