### ISSUE TITLE
gpinitsystem consolidated issues

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#127]
Page No : 722

Issue: gpinitsystem content not in sync Doc to GP help.

- Synopsis section is totally missing.
- Description section totally missing.
- Examples and Also See sections missing.
- Options missing in GP help content.

--lc-collate=locale
Similar to --locale, but sets the locale used for collation (sorting data). The sort order
cannot be changed after Greenplum Database is initialized, so it is important to choose a
collation locale that is compatible with the character set encodings that you plan to use for
your data. There is a special collation name of C or POSIX (byte-order sorting as opposed
to dictionary-order sorting). The C collation can be used with any character encoding.
--lc-ctype=locale
Similar to --locale, but sets the locale used for character classification (what character
sequences are valid and how they are interpreted). This cannot be changed after
Greenplum Database is initialized, so it is important to choose a character classification
locale that is compatible with the data you plan to store in Greenplum Database.
--lc-messages=locale
Similar to --locale, but sets the locale used for messages output by Greenplum
Database. The current version of Greenplum Database does not support multiple locales
for output messages (all messages are in English), so changing this setting will not have
any effect.
--lc-monetary=locale
Similar to --locale, but sets the locale used for formatting currency amounts.
--lc-numeric=locale
Similar to --locale, but sets the locale used for formatting numbers.
--lc-time=locale
Similar to --locale, but sets the locale used for formatting dates and times.
--mirror_mode={group|spread}
Use this option to specify the placement of mirror segment instances on the segment
hosts. The default, group, groups the mirror segments for all of a host's primary segments
on a single alternate host. spread spreads mirror segments for the primary segments
on a host across different hosts in the Greenplum Database array. Spreading is only
allowed if the number of hosts is greater than the number of segment instances per host.
See Overview of Segment Mirroring for information about Greenplum Database mirroring
strategies.

- GP Help content for this option is more informative(-O output_configuration_file).

Doc:
-O output_configuration_file
Optional, used during new cluster initialization. This option writes the
cluster_configuration_file information (used with -c) to the specified
output_configuration_file. This file defines the Greenplum Database members using the
QD_PRIMARY_ARRAY, PRIMARY_ARRAY, and MIRROR_ARRAY parameters. Use this file as
a template for the -I input_configuration_file option. See Examples for more information.

GP Help:
      -O, <output_configuration_file>
          When used with the -O option, gpinitsystem does not create a new Greenplum
          Database cluster but instead writes the supplied cluster configuration
          information to the specified output_configuration_file. This file defines
          Greenplum Database members and segments using the QD_PRIMARY_ARRAY and
          PRIMARY_ARRAY parameters, and can be later used with -I
          <input_configuration_file> to initialize a new cluster.

**Comment by fifthposition** [comment]
Docs story created.
