### ISSUE TITLE
gpload consolidated issues

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#128]
1)

Page No: 730

Issue: Synopsis section below option is missing in GP Help.

[--max_retries retry_times]

2) 

Issue: Requirements in Doc Mentioned PREREQUISITES in GP Help and the content not in sync.

3)

Issue: Under Description section All 3 Notes are missing.

Note: gpfdist is compatible only with the Greenplum Database major version in which it is
shipped. For example, a gpfdist utility that is installed with Greenplum Database 4.x cannot be
used with Greenplum Database 5.x or 6.x.
Note: The Greenplum Database 5.22 and later gpload for Linux is compatible with Greenplum
Database 6.x. The Greenplum Database 6.x gpload for both Linux and Windows is compatible
with Greenplum 5.x.
Note: MERGE and UPDATE operations are not supported if the target table column name is a
reserved keyword, has capital letters, or includes any character that requires quotes (" ") to identify
the column.

4) 

Issue: Options missing in GP Help content.

--max_retries retry_times
Specifies the maximum number of times gpload attempts to connect to Greenplum
Database after a connection timeout. The default value is 0, do not attempt to connect
after a connection timeout. A negative integer, such as -1, specifies an unlimited number
of attempts.

5)

Issue: Missing in config file options.

FULLY_QUALIFIED_DOMAIN_NAME
Optional. Specifies whether gpload resolve hostnames to the fully qualified domain
name (FQDN) or the local hostname. If the value is set to true, names are resolved to
the FQDN. If the value is set to false, resolution is to the local hostname. The default is
false.
A fully qualified domain name might be required in some situations. For example, if the
Greenplum Database system is in a different domain than an ETL application that is being
accessed by gpload.

FILL_MISSING_FIELDS
Optional. The default value is false. When reading a row of data that has missing trailing
field values (the row of data has missing data fields at the end of a line or row), Greenplum
Database returns an error.
If the value is true, when reading a row of data that has missing trailing field values,
the values are set to NULL. Blank rows, fields with a NOT NULL constraint, and trailing
delimiters on a line will still report an error.
See the FILL MISSING FIELDS clause of the CREATE EXTERNAL TABLE command.

STAGING_TABLE
Optional. Specify the name of the temporary external table that is created during a gpload
operation. The external table is used by gpfdist. REUSE_TABLES: true must also
specified. If REUSE_TABLES is false or not specified, STAGING_TABLE is ignored. By
default, gpload creates a temporary external table with a randomly generated name.
If external_table_name contains a period (.), gpload returns an error. If the table exists,
the utility uses the table. The utility returns an error if the existing table schema does not
match the OUTPUT table schema.
The utility uses the value of SCHEMA in the EXTERNAL section as the schema for
external_table_name. If the SCHEMA value is %, the schema for external_table_name is the
same as the schema of the target table, the schema of TABLE in the OUTPUT section.
If SCHEMA is not set, the utility searches for the table (using the schemas in the database
search_path). If the table is not found, external_table_name is created in the default
PUBLIC schema.

FAST_MATCH
Optional. If set to true, gpload only searches the database for matching external table
objects when reusing external tables. The utility does not check the external table column
names and column types in the catalog table pg_attribute to ensure that the table can
be used for a gpload operation. Set the value to true to improve gpload performance
when reusing external table objects and the database catalog table pg_attribute
contains a large number of rows. The utility returns an error and quits if the column
definitions are not compatible.

**Comment by fifthposition** [comment]
Docs story created.
