### ISSUE TITLE
dead links

### ISSUE THREAD

**Issue by Govind-cg** [greenplum-db/sre-test#131]
Page no :706

Issue : dead link.

Given statement:
Specifies that the netperf binary should be used to perform the network test instead of
the Greenplum network test. To use this option, you must download netperf from http://
www.netperf.org and install it into $GPHOME/bin/lib on all Greenplum hosts (master and
segments).

**here  http://www.netperf.org** is not reaching .

page no: 707
Issue : dead link

Given statement:
If you would rather use netperf (http://www.netperf.org) instead of the Greenplum
network test, you can download it and install it into $GPHOME/bin/lib on all
Greenplum hosts (master and segments). You would then specify the optional --
netperf option to use the netperf binary instead of the default gpnetbench*
utilities.

**here http://www.netperf.org is not working.**

**Comment by fifthposition** [comment]
Docs story created.
