### ISSUE TITLE
gppkg update did not work for madlib

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#136]
Page No : 755

Issue: Upgrade is not working if we give the package name.

[gpadmin@mdw_ipv4 madlib-1.18.0+2-gp6-rhel7-x86_64]$ gppkg -q --all
20210608:15:52:59:010454 gppkg:mdw_ipv4:gpadmin-[INFO]:-Starting gppkg with args: -q --all
madlib-1.18.0+2
[gpadmin@mdw_ipv4 madlib-1.18.0+2-gp6-rhel7-x86_64]$
[gpadmin@mdw_ipv4 madlib-1.18.0+2-gp6-rhel7-x86_64]$
[gpadmin@mdw_ipv4 madlib-1.18.0+2-gp6-rhel7-x86_64]$ gppkg -u madlib-1.18.0+2
20210608:15:53:06:010468 gppkg:mdw_ipv4:gpadmin-[INFO]:-Starting gppkg with args: -u madlib-1.18.0+2
20210608:15:53:06:010468 gppkg:mdw_ipv4:gpadmin-[WARNING]:-WARNING: The process of updating a package includes removing all
20210608:15:53:06:010468 gppkg:mdw_ipv4:gpadmin-[WARNING]:-previous versions of the system objects related to the package. For
20210608:15:53:06:010468 gppkg:mdw_ipv4:gpadmin-[WARNING]:-example, previous versions of shared libraries are removed.
20210608:15:53:06:010468 gppkg:mdw_ipv4:gpadmin-[WARNING]:-After the update process, a database function will fail when it is
20210608:15:53:06:010468 gppkg:mdw_ipv4:gpadmin-[WARNING]:-called if the function references a package file that has been removed.
Do you still want to continue ? Yy|Nn (default=N):
> y
20210608:15:53:27:010468 gppkg:mdw_ipv4:gpadmin-[ERROR]:-Cannot find package madlib-1.18.0+2
20210608:15:53:27:010468 gppkg:mdw_ipv4:gpadmin-[CRITICAL]:-gppkg failed. (Reason='') exiting...
[gpadmin@mdw_ipv4 madlib-1.18.0+2-gp6-rhel7-x86_64]$

[gpadmin@mdw_ipv4 madlib-1.18.0+2-gp6-rhel7-x86_64]$ gppkg -u madlib-1.18*
20210608:15:53:41:010576 gppkg:mdw_ipv4:gpadmin-[INFO]:-Starting gppkg with args: -u madlib-1.18.0+2-gp6-rhel7-x86_64.gppkg
20210608:15:53:41:010576 gppkg:mdw_ipv4:gpadmin-[WARNING]:-WARNING: The process of updating a package includes removing all
20210608:15:53:41:010576 gppkg:mdw_ipv4:gpadmin-[WARNING]:-previous versions of the system objects related to the package. For
20210608:15:53:41:010576 gppkg:mdw_ipv4:gpadmin-[WARNING]:-example, previous versions of shared libraries are removed.
20210608:15:53:41:010576 gppkg:mdw_ipv4:gpadmin-[WARNING]:-After the update process, a database function will fail when it is
20210608:15:53:41:010576 gppkg:mdw_ipv4:gpadmin-[WARNING]:-called if the function references a package file that has been removed.
Do you still want to continue ? Yy|Nn (default=N):
> y
20210608:15:53:43:010576 gppkg:mdw_ipv4:gpadmin-[INFO]:-Updating package madlib-1.18.0+2-gp6-rhel7-x86_64.gppkg
20210608:15:53:43:010576 gppkg:mdw_ipv4:gpadmin-[INFO]:-Validating rpm installation cmdStr='rpm --test -U --force /usr/local/greenplum-db-6.15.0/.tmp/madlib-1.18.0-1.x86_64.rpm --dbpath /usr/local/greenplum-db-6.15.0/share/packages/database --prefix /usr/local/greenplum-db-6.15.0'
20210608:15:53:45:010576 gppkg:mdw_ipv4:gpadmin-[INFO]:-Installing madlib-1.18.0+2-gp6-rhel7-x86_64.gppkg locally
20210608:15:53:46:010576 gppkg:mdw_ipv4:gpadmin-[INFO]:-Validating rpm installation cmdStr='rpm --test -U --force /usr/local/greenplum-db-6.15.0/.tmp/madlib-1.18.0-1.x86_64.rpm --dbpath /usr/local/greenplum-db-6.15.0/share/packages/database --prefix /usr/local/greenplum-db-6.15.0'
20210608:15:53:46:010576 gppkg:mdw_ipv4:gpadmin-[INFO]:-Installing rpms cmdStr='rpm -U --force /usr/local/greenplum-db-6.15.0/.tmp/madlib-1.18.0-1.x86_64.rpm --dbpath /usr/local/greenplum-db-6.15.0/share/packages/database --prefix=/usr/local/greenplum-db-6.15.0'
20210608:15:53:46:010576 gppkg:mdw_ipv4:gpadmin-[INFO]:-Completed local installation of madlib-1.18.0+2-gp6-rhel7-x86_64.gppkg.
20210608:15:53:46:010576 gppkg:mdw_ipv4:gpadmin-[INFO]:-madlib-1.18.0+2-gp6-rhel7-x86_64.gppkg successfully updated.
[gpadmin@mdw_ipv4 madlib-1.18.0+2-gp6-rhel7-x86_64]$

**Comment by fifthposition** [comment]
Docs story created.
