### ISSUE TITLE
psql

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#141]
Page No 836

Issue: psql content not in sync Doc to GP help (psql -?)

Missing Synopsis, Description, and Examples sections.
Option Description not in Sync.

Page No : 860
Issue: Distribution key missing in the description output of a table.

Doc:
testdb=> \d my_table
Table "my_table"
Attribute | Type | Modifier
-----------+---------+--------------------
first | integer | not null default 0
second | text |

Actual:
\d my_table
        Table "public.my_table"
 Column |  Type   |     Modifiers
--------+---------+--------------------
 first  | integer | not null default 0
 second | text    |
Distributed by: (first)

**Comment by fifthposition** [comment]
Docs story created for second issue.
