### ISSUE TITLE
Panic occurred when executed this select statement to call the function.

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#144]
Page No: 1045

Issue: Panic occurred when executed this select statement to call the function.

gpadmin=# SELECT * FROM return_enum_as_array('red'::rainbow, 'green'::rainbow,'blue'::rainbow);
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.

- Given set of statements.
CREATE TYPE rainbow AS
ENUM('red','orange','yellow','green','blue','indigo','violet');
CREATE FUNCTION return_enum_as_array( anyenum, anyelement, anyelement )
RETURNS TABLE (ae anyenum, aa anyarray) AS $$
SELECT $1, array[$2, $3]
$$ LANGUAGE SQL STABLE;
SELECT * FROM return_enum_as_array('red'::rainbow, 'green'::rainbow,'blue'::rainbow);

- Master Logs

return_enum_as_array('red'::rainbow, 'green'::rainbow,
'blue'::rainbow);",,,,,,"SELECT * FROM return_enum_as_array('red'::rainbow, 'green'::rainbow,
'blue'::rainbow);",0,,"postgres.c",1639,
2021-06-14 17:40:38.651436 UTC,,,p3441,th0,,,2021-06-14 14:29:21 UTC,0,con19471,cmd21,seg-1,,,,,"PANIC","XX000","Unexpected internal error: Master process received signal SIGSEGV",,,,,,,0,,,,"1    0x7f1f2bfb75f0 libpthread.so.0 <symbol not found> + 0x2bfb75f0
2    0xfce266 postgres _ZN5gpdxl16CTranslatorUtils23ConvertToCDXLLogicalTVFEPN4gpos11CMemoryPoolEPN5gpopt11CMDAccessorEPNS_12CIdGeneratorEPK13RangeTblEntry (CRefCount.h:103)
3    0xfeea97 postgres _ZN5gpdxl21CTranslatorQueryToDXL17TranslateTVFToDXLEPK13RangeTblEntryjj (CTranslatorQueryToDXL.cpp:3577)
4    0xfe7ef6 postgres _ZN5gpdxl21CTranslatorQueryToDXL22TranslateFromExprToDXLEP8FromExpr (CTranslatorQueryToDXL.cpp:2922)
5    0xfe937a postgres _ZN5gpdxl21CTranslatorQueryToDXL21TranslateGroupingSetsEP8FromExprP4ListS4_bPN4gpos8CHashMapIijXadL_ZNS5_9HashValueIiEEjPKT_EEXadL_ZNS5_6EqualsIiEEbSA_SA_EEXadL_ZNS5_13CleanupDeleteIiEEvPS8_EEXadL_ZNSC_IjEEvSD_EEEESF_ (CTranslatorQueryToDXL.cpp:613)
6    0xfe97bd postgres _ZN5gpdxl21CTranslatorQueryToDXL25TranslateSelectQueryToDXLEv (CTranslatorQueryToDXL.cpp:557)
7    0xfeaf46 postgres _ZN5gpdxl21CTranslatorQueryToDXL19TranslateQueryToDXLEv (CTranslatorQueryToDXL.cpp:659)
8    0xfffaf4 postgres _ZN9COptTasks12OptimizeTaskEPv (discriminator 3)
9    0xcf06f6 postgres _ZN4gpos5CTask7ExecuteEv (CTask.cpp:130)
10   0xcf1688 postgres _ZN4gpos7CWorker7ExecuteEPNS_5CTaskE (CWorker.cpp:82)
11   0xcefbbd postgres _ZN4gpos14CAutoTaskProxy7ExecuteEPNS_5CTaskE (CAutoTaskProxy.cpp:301)
12   0xcf2281 postgres gpos_exec (_api.cpp:246)
13   0xffdca1 postgres _ZN9COptTasks7ExecuteEPFPvS0_ES0_ (COptTasks.cpp:261)
14   0xffeece postgres _ZN9COptTasks18GPOPTOptimizedPlanEP5QueryP11SOptContext (COptTasks.cpp:775)
15   0x1001191 postgres GPOPTOptimizedPlan (CGPOptimizer.cpp:60)
16   0x9d29e3 postgres optimize_query (orca.c:46)
17   0x9c406d postgres standard_planner (planner.c:240)
18   0x9c43c5 postgres planner (planner.c:200)
19   0xa8a2e1 postgres <symbol not found> (postgres.c:961)
20   0xa8cc7f postgres PostgresMain (postgres.c:5242)
"
2021-06-14 17:40:38.651559 UTC,,,p17617,th781932672,,,,0,,,seg-1,,,,,"LOG","00000","server process (PID 3441) was terminated by signal 11: Segmentation fault","Failed process was running: SELECT * FROM return_enum_as_array('red'::rainbow, 'green'::rainbow,
'blue'::rainbow);",,,,,,0,,"postmaster.c",3970,

**Comment by fifthposition** [comment]
Docs story created.

**Comment by bala-cg** [comment]
Hi Ben @fifthposition ,

This is a product issue, Ed will be looking into it once.

**Comment by edespino** [comment]
The following GPDB product issue has been filed: [#12171](https://github.com/greenplum-db/gpdb/issues/12171).

Ben (@fifthposition), please close the doc story you created. This is not a doc issue.

**Comment by fifthposition** [comment]
@edespino Done.

It did seem to me to not really be a doc issue, except that I figured we could investigate whether we should change the statement or something (i.e. the docs could have had an error, rather than functionality being actually broken)
