### ISSUE TITLE
missing option in COMMENT

### ISSUE THREAD

**Issue by Govind-cg** [greenplum-db/sre-test#146]
Page no : 990

Issue: missing option in COMMENT.
missing options are 
  **TEXT SEARCH CONFIGURATION object_name |
  TEXT SEARCH DICTIONARY object_name |
  TEXT SEARCH PARSER object_name |
  TEXT SEARCH TEMPLATE object_name |
  COLUMN relation_name.column_name**

**Comment by fifthposition** [comment]
Docs story created.
