### ISSUE TITLE
missing  Optimizer: Pivotal Optimizer (GPORCA) message in doc.

### ISSUE THREAD

**Issue by Govind-cg** [greenplum-db/sre-test#147]
Page no 1012.

Issue : missing **Optimizer: Pivotal Optimizer (GPORCA)** message in doc, when executed explain select agg_prefunc(a, b) from t1;

------------------------------------------------------------------------------------
 Aggregate  (cost=0.00..431.00 rows=1 width=8)
   ->  Gather Motion 6:1  (slice1; segments: 6)  (cost=0.00..431.00 rows=1 width=8)
         ->  Aggregate  (cost=0.00..431.00 rows=1 width=8)
               ->  Seq Scan on t1  (cost=0.00..431.00 rows=1 width=8)
 Optimizer: Pivotal Optimizer (GPORCA)
(5 rows)

**Comment by fifthposition** [comment]
Docs story created.
