### ISSUE TITLE
Drop protocol link missing in "See Also" section

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#149]
Page No : 943

Issue: Drop protocol link missing in "See Also" section

Given:
See Also
CREATE EXTERNAL TABLE, CREATE PROTOCOL

**Comment by fifthposition** [comment]
Docs story created.

**Comment by mperezfuster** [comment]
@bala-cg can you specify what link is missing? I am able to click on both links.

**Comment by bala-cg** [comment]
@fifthposition, attached screenshot from the pdf doc, in page 943 reference link to Drop protocol missing
![drop protocol missing](https://user-images.githubusercontent.com/78151006/124498899-bdb07800-ddda-11eb-8429-1ccc61c1b881.JPG)
.

**Comment by mperezfuster** [comment]
@bala-cg thank you, I wasn't sure what command you were referring to, I can confirm now the command to modify is ALTER PROTOCOL
