### ISSUE TITLE
memory_limit (default or set to 0) option definition confusing

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#150]
Page No 945

Issue: memory_limit (default or set to 0) option definition confusing

Given:
MEMORY_LIMIT integer
The percentage of Greenplum Database memory resources to reserve for this resource
group. The minimum memory percentage for a resource group is 0. The maximum is 100.
The default value is 0.
**When MEMORY_LIMIT is 0, Greenplum Database reserves no memory for the resource
group**, but uses global shared memory to fulfill all memory requests in the group. If
MEMORY_LIMIT is 0, MEMORY_SPILL_RATIO must also be 0.

Practical:
memory_limit set to 0 means unlimited as per bellow Error.

 CREATE RESOURCE GROUP rgroup2 WITH (CPU_RATE_LIMIT=5);

gpadmin=# SELECT * FROM gp_toolkit.gp_resgroup_config where groupname ='rgroup2' ;
 groupid |   groupname   | concurrency | cpu_rate_limit | memory_limit | memory_shared_quota | memory_spill_ratio | memory_auditor | cpuset
---------+---------------+-------------+----------------+--------------+---------------------+--------------------+----------------+--------
 115988 | rgroup2       | 20          | 5              | 0            | 80                  | 0                  | vmtracker      | -1

gpadmin=# ALTER RESOURCE GROUP rgroup2 SET memory_spill_ratio 95;
ERROR:  when memory_limit is unlimited memory_spill_ratio must be set to 0
gpadmin=#

**Comment by fifthposition** [comment]
Docs story created.
