### ISSUE TITLE
Not mentioned what will happen if Query cost beyond MAX_COST 

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#151]
Page No : 1070

Issue: Not Mention what will happen if the query cost goes beyond MAX_COST of RQ.

This will fail with Error.

gpadmin=> select count(*) from (select * from  tab1, tab2) a;
ERROR:  statement requires more resources than resource queue allows.

Given in Doc:
MAX_COST float
Resource queues with a MAX_COST threshold set a maximum limit on the total cost of
queries that can be executed by roles assigned to that queue. Cost is measured in the
estimated total cost for the query as determined by the Greenplum Database query
optimizer (as shown in the EXPLAIN output for a query). Therefore, an administrator must
be familiar with the queries typically executed on the system in order to set an appropriate
cost threshold for a queue. Cost is measured in units of disk page fetches; 1.0 equals one
sequential disk page read. The value for MAX_COST is specified as a floating point number
(for example 100.0) or can also be specified as an exponent (for example 1e+2).

**Comment by fifthposition** [comment]
Docs story created.
