### ISSUE TITLE
Incorrect/Incomplete statement

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#152]
Page No: 1071

Issue: Incorrect/Incomplete statement

**Correct statement:**
each query will be allocated 100MB*(no of segments) present in the segment host.

**Given in Doc:**
Create a resource queue with an active query limit of 20 and a total memory limit of 2000MB (**each query
will be allocated 100MB of segment host memory at execution time)**:
CREATE RESOURCE QUEUE myqueue WITH (ACTIVE_STATEMENTS=20,
MEMORY_LIMIT='2000MB');

**Comment by fifthposition** [comment]
Docs story created.
