### ISSUE TITLE
Example misplaced 

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#155]
Page No : 969

Issue: Example misplaced.

Given:
Add a not-null constraint to a column:
To rename an existing constraint:
ALTER TABLE distributors RENAME CONSTRAINT zipchk TO zip_check;
ALTER TABLE distributors ALTER COLUMN street SET NOT NULL;

To Be:
Add a not-null constraint to a column:
ALTER TABLE distributors ALTER COLUMN street SET NOT NULL;
To rename an existing constraint:
ALTER TABLE distributors RENAME CONSTRAINT zipchk TO zip_check;

**Comment by fifthposition** [comment]
Docs story created.
