### ISSUE TITLE
First 2 Examples not highlighted in PDF and Online Documentation

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#156]
Page No : 974

Issue: First 2 Examples not highlighted in PDF and Online Documentation

PDF page no: 974

Online Doc Link
https://gpdb.docs.pivotal.io/6-16/ref_guide/sql_commands/ALTER_TEXT_SEARCH_DICTIONARY.html

**Comment by fifthposition** [comment]
Docs story created.
