### ISSUE TITLE
"Deny Between" option for Role and User need more clarity.

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#158]
**Page No : 951**

Issue: "Deny Between" option for Role and User need more clarity.

Given:
The DENY BETWEEN clause uses two deny_point parameters.

Better to be:
The DENY BETWEEN clause uses two deny_point parameters and the deny_point need both Day and Time, just day will throw an error.

gpadmin=#
gpadmin=# ALTER USER user1 DENY between day 'sunday' and 'monday';
ERROR:  syntax error at or near "'monday'"
LINE 1: ALTER USER user1 DENY between day 'sunday' and 'monday';

gpadmin=# ALTER user user1 DENY between day 'sunday' time '00:00' and day 'monday' time '00:00';
ALTER ROLE
gpadmin=# 

**Page No: 952**

Better to have one example with "deny between" clause.

ALTER user user1 DENY between day 'sunday' time '00:00' and day 'monday' time '00:00';

**Comment by fifthposition** [comment]
Docs story created.
