### ISSUE TITLE
while enabling gp_resource_manager to group it failed

### ISSUE THREAD

**Issue by Govind-cg** [greenplum-db/sre-test#160]
Page no 1068 

Issue : while creating resource group with given  ,it's giving warning  and hint, while resolving warning with hint it failed.

gpadmin=# CREATE RESOURCE GROUP rgroup1 WITH (CPU_RATE_LIMIT=35, MEMORY_LIMIT=35);
WARNING:  resource group is disabled
HINT:  To enable set gp_resource_manager=group
CREATE RESOURCE GROUP

-trying to set gp_resource_manager to group it failed with below error.
gpadmin=# set gp_resource_manager='group';
ERROR:  parameter "gp_resource_manager" cannot be changed without restarting the server

- tried with gpconfig -c gp_resource_manager -v "group" it failed with below error.

gpconfig -c gp_resource_manager -v 'group';
20210701:06:36:50:001687 gpconfig:mdw_ipv4:gpadmin-[CRITICAL]:-new GUC value failed validation: [mdw_ipv4:cgroup is not properly configured: directory '/sys/fs/cgroup/cpu/gpdb/' does not exist],[sdw1_ipv4:cgroup is not properly configured: directory '/sys/fs/cgroup/cpu/gpdb/' does not exist],[sdw2_ipv4:cgroup is not properly configured: directory '/sys/fs/cgroup/cpu/gpdb/' does not exist],[smdw_ipv4:cgroup is not properly configured: directory '/sys/fs/cgroup/cpu/gpdb/' does not exist]
new GUC value failed validation: [mdw_ipv4:cgroup is not properly configured: directory '/sys/fs/cgroup/cpu/gpdb/' does not exist],[sdw1_ipv4:cgroup is not properly configured: directory '/sys/fs/cgroup/cpu/gpdb/' does not exist],[sdw2_ipv4:cgroup is not properly configured: directory '/sys/fs/cgroup/cpu/gpdb/' does not exist],[smdw_ipv4:cgroup is not properly configured: directory '/sys/fs/cgroup/cpu/gpdb/' does not exist]

- I see this KB, with similar error, not relevant to this issue(here we are trying to change gp_resource_manager to group).

https://community.pivotal.io/s/article/FATAL--cgroup-Is-Not-Properly-Configured-Gives-The-Error-can-not-find-cgroup-mount-point?language=en_US

**Comment by edespino** [comment]
@bala-cg Enabling `cgroups` across the cluster is a prerequisite to using Resource Groups. This is covered in Chapter 5 [Memory and Resource Management with Resource Groups](https://greenplum.docs.pivotal.io/6-17/best_practices/resgroups.html). I would recommend modifying the section to include a prerequisite section pointing to  Chapter 5 [Memory and Resource Management with Resource Groups](https://greenplum.docs.pivotal.io/6-17/best_practices/resgroups.html). Once `cgroups` is configured, things work properly.

**Comment by edespino** [comment]
I do think the HINT is misleading/wrong. How about the following recommendation?

**From:**
`errhint("To enable set gp_resource_manager=group")));
`
**To:** 
`errhint("Follow Greenplum documented procedures to enable Resource Group support.")));
`

**Comment by bala-cg** [comment]
Yes @edespino, it works fine after running the prerequisites, yes if the HITN message is changed the confusion can be avoided.

gpadmin=# CREATE RESOURCE GROUP rgroup1 WITH (CPU_RATE_LIMIT=20, MEMORY_LIMIT=25,
gpadmin(# MEMORY_SPILL_RATIO=20);
CREATE RESOURCE GROUP
gpadmin=#
gpadmin=#
gpadmin=# CREATE RESOURCE GROUP rgroup_extcomp WITH (MEMORY_AUDITOR=cgroup,
gpadmin(# CONCURRENCY=0,
gpadmin(# CPUSET='1', MEMORY_LIMIT=15);
CREATE RESOURCE GROUP
gpadmin=#
gpadmin=#
gpadmin=# ALTER RESOURCE GROUP rg_role_light SET CONCURRENCY 7;
ERROR:  resource group "rg_role_light" does not exist
gpadmin=#
gpadmin=#
gpadmin=#
gpadmin=# ALTER RESOURCE GROUP rgroup1 SET CONCURRENCY 7;
ALTER RESOURCE GROUP
gpadmin=#
