### ISSUE TITLE
analyze command issues

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#161]
1)
Page: 982

Issue: Incomplete statement.

Given:
You can specify a set of column names, in which case the statistics only for those columns are collected.

Better to be:
You can specify a set of column names in a specific table, in which case the statistics only for those columns of that table are collected.

2)
page 983

Issue: duplicate phrase.

Given:
VERBOSE
**Enables display of progress messages. Enables display of progress messages.** When
specified, ANALYZE emits this information

3)
Page : 985

Issue: "See Also" section analyzedb utility reference link missing.

Given:
See Also
ALTER TABLE, EXPLAIN, VACUUM, **analyzedb** utility in the Greenplum Database Utility Guide.

**Comment by fifthposition** [comment]
Docs story created.
