### ISSUE TITLE
Reference link not working in PDF doc.

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#162]
Page No : 1294

Issue: Reference link not working.

Given:
The orafce module is installed when you install Greenplum Database. Before you can use any of the
functions defined in the module, you must register the orafce extension in each database in which you
want to use the functions. Refer to **Installing Additional Supplied Modules** for more information.

Page No: 1280

Issue: Reference link not working for below 2 modules on same page.

Given:
The citext module is installed when you install Greenplum Database. Before you can use any of the
data types, operators, or functions defined in the module, you must register the citext extension in each
database in which you want to use the objects. **Refer to Installing Additional Supplied Modules** for more
information.

Given:
The dblink module is installed when you install Greenplum Database. Before you can use any of the
functions defined in the module, you must register the dblink extension in each database in which you
want to use the functions. **Refer to Installing Additional Supplied Modules** for more information.

**Comment by fifthposition** [comment]
Docs story created.
