### ISSUE TITLE
Given command fails when ran.

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#163]
Page No : 1285

Issue: Given command fails when ran, single quotes missing for the role name, as both function arguments are text data type.

Given: 
This example sets a 500MB quota for the nickd role:
SELECT diskquota.set_role_quota(nickd, '500MB');
ERROR:  column "nickd" does not exist
LINE 1: SELECT diskquota.set_role_quota(nickd, '500MB');

Correct statement:
SELECT diskquota.set_role_quota('nickd', '500MB');
 set_role_quota
----------------

(1 row)

**Comment by fifthposition** [comment]
Docs story created.
