### ISSUE TITLE
missing information

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#164]
Page No: 1286

Issue: missing information, given command need a gp reload for the change to take affect, this is not mentioned.

Given:
Setting the Delay Between Disk Usage Updates
The diskquota.naptime server configuration parameter specifies how frequently (in seconds) the table
sizes are recalculated. The smaller the naptime value, the less delay in detecting changes in disk usage.
This example sets the naptime to ten seconds.
$ gpconfig -c diskquota.naptime -v 10

Testing:
[gpadmin@mdw_ipv4 ~]$ gpconfig -s diskquota.naptime
Values on all segments are consistent
GUC          : diskquota.naptime
Master  value: 2
Segment value: 2
[gpadmin@mdw_ipv4 ~]$ gpconfig -c diskquota.naptime -v 10
20210705:17:19:55:024697 gpconfig:mdw_ipv4:gpadmin-[INFO]:-completed successfully with parameters '-c diskquota.naptime -v 10'
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s diskquota.naptime
Values on all segments are consistent
GUC          : diskquota.naptime
Master  value: 2
Segment value: 2
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s diskquota.naptime
Values on all segments are consistent
GUC          : diskquota.naptime
Master  value: 2
Segment value: 2
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpstop -u
20210705:17:20:28:024856 gpstop:mdw_ipv4:gpadmin-[INFO]:-Starting gpstop with args: -u
20210705:17:20:28:024856 gpstop:mdw_ipv4:gpadmin-[INFO]:-Gathering information and validating the environment...
20210705:17:20:28:024856 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20210705:17:20:28:024856 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Segment details from master...
20210705:17:20:28:024856 gpstop:mdw_ipv4:gpadmin-[INFO]:-Greenplum Version: 'postgres (Greenplum Database) 6.16.0 build commit:5650be2b79197fed564dca8d734d10f2a76b876c'
20210705:17:20:28:024856 gpstop:mdw_ipv4:gpadmin-[INFO]:-Signalling all postmaster processes to reload
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s diskquota.naptime
Values on all segments are consistent
GUC          : diskquota.naptime
Master  value: 10
Segment value: 10
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$

**Comment by fifthposition** [comment]
Docs story created.
