### ISSUE TITLE
References are missing  

### ISSUE THREAD

**Issue by Govind-cg** [greenplum-db/sre-test#165]
Page 1128 

Issue: Missing ALTER LANGUAGE reference for language in see also section.

page 1135.

Issue : missing ALTER EXTERNAL TABLE  reference for EXTERNAL TABLE  in see also section.

Page 1156 

Issue : missing CREATE  USER  reference for USER  in see also section.

page  1158

Issue : missing ALTER  VIEW  reference for VIEW  in see also section.

**Comment by fifthposition** [comment]
Docs story created.

**Comment by mperezfuster** [comment]
Hi @Govind-cg could you please specify what sections of the docs you are looking at that are missing references? As the page numbers do not match anymore.
For example for the first one, are you looking at CREATE LANGUAGE, DROP LANGUAGE, etc?
Thank you!

**Comment by Govind-cg** [comment]
Hi @mperezfuster .. sorry my mistake. given wrong page number for DROP LANGUAGE.  please find blow  updated with section.

page 1135.
Query: DROP EXTERNAL TABLE
Issue : missing ALTER EXTERNAL TABLE reference  in see also section.
given: 
**See Also**
CREATE EXTERNAL TABLE
it should be like : 
**See Also**
CREATE EXTERNAL TABLE, ALTER EXTERNAL TABLE

Page 1156
Query: DROP USER
Issue : missing CREATE USER reference in see also section.
given: 
**See Also**
DROP ROLE
it should be like: 
**See Also**
DROP ROLE, CREATE  USER.

page 1158
Query: DROP VIEW
Issue : missing ALTER VIEW reference in see also section.
given: 
**See Also**
CREATE VIEW
it should be like: 
**See Also**
CREATE VIEW,ALTER VIEW

**Comment by mperezfuster** [comment]
Thank you @Govind-cg !
