### ISSUE TITLE
Reference link not working in PDF doc

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#167]
Fix for below issues: the reference link should refer back to page 80 in the PDF file topic "Installing Additional Supplied Modules".

Page No: 1288

Issue: Reference link not working.

Given:
The fuzzystrmatch module is installed when you install Greenplum Database. Before you can use
any of the functions defined in the module, you must register the fuzzystrmatch extension in each
database in which you want to use the functions. Refer to **Installing Additional Supplied Modules** for more
information.

Page No : 1289

Issue: Reference link not working.

Given:
The gp_sparse_vector module is installed when you install Greenplum Database. Before you can use
any of the functions defined in the module, you must register the gp_sparse_vector extension in each
database where you want to use the functions. Refer to **Installing Additional Supplied Modules** for more
information.

Page No : 1293

Issue: Reference link not working.

Given:
The hstore module is installed when you install Greenplum Database. Before you can use any of the
data types or functions defined in the module, you must register the hstore extension in each database in
which you want to use the objects. Refer to **Installing Additional Supplied Modules** for more information.

Page No: 1296

Issue: Reference link not working.

Given:
The pageinspect module is installed when you install Greenplum Database. Before you can use any of
the functions defined in the module, you must register the pageinspect extension in each database in
which you want to use the functions. Refer to **Installing Additional Supplied Modules** for more information.

Page No: 1296

Issue: Reference link not working.

Given:
The pgcrypto module is installed when you install Greenplum Database. Before you can use any of the
functions defined in the module, you must register the pgcrypto extension in each database in which you
want to use the functions. Refer to **Installing Additional Supplied Modules** for more information.

Page No: 1297

Issue: Reference link not working.

Given:
The postgres_fdw module is installed when you install Greenplum Database. Before you can use the
foreign data wrapper, you must register the postgres_fdw extension in each database in which you want
to use the foreign data wrapper. Refer to **Installing Additional Supplied Modules** for more information.

Page No: 1297

Issue: Reference link not working.

Given:
The sslinfo module is installed when you install Greenplum Database. Before you can use any of the
functions defined in the module, you must register the sslinfo extension in each database in which you
want to use the functions. Refer to **Installing Additional Supplied Modules** for more information.

**Comment by fifthposition** [comment]
Docs story created.
