### ISSUE TITLE
client_encoding parameter issues

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#169]
Page No: 1318

- 2 Issues
1)After changing this parameter value it gets changed only on Master, not on segments.
2) After change it does reflect when we query using "show client_encoding;"

testing:
1)
[gpadmin@mdw_ipv4 ~]$ gpconfig -s client_encoding
Values on all segments are consistent
GUC          : client_encoding
Master  value: UTF8
Segment value: UTF8
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -c client_encoding -v SQL_ASCII
20210708:17:59:14:003554 gpconfig:mdw_ipv4:gpadmin-[INFO]:-completed successfully with parameters '-c client_encoding -v SQL_ASCII'
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s client_encoding
Values on all segments are consistent
GUC          : client_encoding
Master  value: UTF8
Segment value: UTF8
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpstop -u
20210708:17:59:24:003642 gpstop:mdw_ipv4:gpadmin-[INFO]:-Starting gpstop with args: -u
20210708:17:59:24:003642 gpstop:mdw_ipv4:gpadmin-[INFO]:-Gathering information and validating the environment...
20210708:17:59:24:003642 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20210708:17:59:24:003642 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Segment details from master...
20210708:17:59:24:003642 gpstop:mdw_ipv4:gpadmin-[INFO]:-Greenplum Version: 'postgres (Greenplum Database) 6.16.0 build commit:5650be2b79197fed564dca8d734d10f2a76b876c'
20210708:17:59:24:003642 gpstop:mdw_ipv4:gpadmin-[INFO]:-Signalling all postmaster processes to reload
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s client_encoding
Values on all segments are consistent
GUC          : client_encoding
Master  value: SQL_ASCII
Segment value: UTF8
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ 

2)
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ psql
psql (9.4.24)
Type "help" for help.

gpadmin=# show client_encoding;
 client_encoding
-----------------
 UTF8
(1 row)

gpadmin=# \q
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s client_encoding
Values on all segments are consistent
GUC          : client_encoding
Master  value: SQL_ASCII
Segment value: UTF8
[gpadmin@mdw_ipv4 ~]$

**Comment by edespino** [comment]
I'm guessing this GUC needs to be moved from `src/include/utils/nosync_guc_name.h` to `src/include/utils/sync_guc_name.h`.

**Comment by edespino** [comment]
@ashwinstar Do you have any thoughts on this behavior?

**Comment by ashwinstar** [comment]
It has nothing to do with `nosync_guc_name` file. Will have to play little to find/trace/understand what's going on.
