### ISSUE TITLE
DateStyle parameter issue

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#170]
Page No : 1320

Issue: - This parameter fails set when given lower case of the parameter, usually All parameter names are case-insensitive (as per Doc page no 1303).

testing:

[gpadmin@mdw_ipv4 ~]$ gpconfig -s datestyle
Values on all segments are consistent
GUC          : datestyle
Master  value: ISO, MDY
Segment value: ISO, MDY
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$

[gpadmin@mdw_ipv4 ~]$ gpconfig -c datestyle -v 'ISO, DMY'
20210709:11:27:16:008541 gpconfig:mdw_ipv4:gpadmin-[CRITICAL]:-GUC Validation Failed: datestyle cannot be changed under normal conditions. Please refer to gpconfig documentation.
GUC Validation Failed: datestyle cannot be changed under normal conditions. Please refer to gpconfig documentation.

[gpadmin@mdw_ipv4 ~]$ gpconfig -c DateStyle -v 'ISO, DMY'
20210709:11:29:49:008824 gpconfig:mdw_ipv4:gpadmin-[INFO]:-completed successfully with parameters '-c DateStyle -v 'ISO, DMY''
[gpadmin@mdw_ipv4 ~]$

**Comment by edespino** [comment]
This should probably be changed to a generic gpconfig issue. It cannot handle pg_settings name case mismatches.
