### ISSUE TITLE
wrong schema name and missing backend_xmin column in gp_stat_replication table

### ISSUE THREAD

**Issue by Govind-cg** [greenplum-db/sre-test#173]
page no 1419.

Issue1 : wrong schema name.

given : Table 138: **gp_catalog**.gp_stat_replication.
correction: it should be **pg_catalog**.gp_stat_replication.

Issue2: missing backend_xmin column in gp_stat_replication table in document.

**Comment by fifthposition** [comment]
Docs story created.
