### ISSUE TITLE
Missing few columns in pg_catalog.pg_trigger table.

### ISSUE THREAD

**Issue by Govind-cg** [greenplum-db/sre-test#177]
Page no :1497

Issue: missing tgconstrindid, tgconstraint, tgqual columns and it's description in document. those columns are present in sysstem.

**Comment by fifthposition** [comment]
@Govind-cg Does this refer to Table 208 (pg_catalog.pg_statistic)?

**Comment by fifthposition** [comment]
Docs story created.
