### ISSUE TITLE
dynamic_library_path parameter takes affect with reload

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#179]
Page No 1324

Issue: This parameter change takes effect on reload, restart is given.

[gpadmin@mdw_ipv4 pg_log]$ gpconfig -s dynamic_library_path
Values on all segments are consistent
GUC          : dynamic_library_path
Master  value: $libdir
Segment value: $libdir
[gpadmin@mdw_ipv4 pg_log]$
[gpadmin@mdw_ipv4 pg_log]$
[gpadmin@mdw_ipv4 pg_log]$ gpconfig -c dynamic_library_path -v MASTER
20210713:18:31:30:002258 gpconfig:mdw_ipv4:gpadmin-[INFO]:-completed successfully with parameters '-c dynamic_library_path -v MASTER'
[gpadmin@mdw_ipv4 pg_log]$
[gpadmin@mdw_ipv4 pg_log]$
[gpadmin@mdw_ipv4 pg_log]$
[gpadmin@mdw_ipv4 pg_log]$ gpconfig -s dynamic_library_path
Values on all segments are consistent
GUC          : dynamic_library_path
Master  value: $libdir
Segment value: $libdir
[gpadmin@mdw_ipv4 pg_log]$
[gpadmin@mdw_ipv4 pg_log]$
[gpadmin@mdw_ipv4 pg_log]$ gpstop -u
20210713:18:32:03:002379 gpstop:mdw_ipv4:gpadmin-[INFO]:-Starting gpstop with args: -u
20210713:18:32:03:002379 gpstop:mdw_ipv4:gpadmin-[INFO]:-Gathering information and validating the environment...
20210713:18:32:03:002379 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20210713:18:32:03:002379 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Segment details from master...
20210713:18:32:03:002379 gpstop:mdw_ipv4:gpadmin-[INFO]:-Greenplum Version: 'postgres (Greenplum Database) 6.16.0 build commit:5650be2b79197fed564dca8d734d10f2a76b876c'
20210713:18:32:03:002379 gpstop:mdw_ipv4:gpadmin-[INFO]:-Signalling all postmaster processes to reload
[gpadmin@mdw_ipv4 pg_log]$
[gpadmin@mdw_ipv4 pg_log]$
[gpadmin@mdw_ipv4 pg_log]$ gpconfig -s dynamic_library_path
Values on all segments are consistent
GUC          : dynamic_library_path
Master  value: MASTER
Segment value: MASTER
[gpadmin@mdw_ipv4 pg_log]$
[gpadmin@mdw_ipv4 pg_log]$

**Comment by fifthposition** [comment]
Docs story created.
