### ISSUE TITLE
Inconsistent Greenplum document titles

### ISSUE THREAD

**Issue by indranil-cg** [greenplum-db/sre-test#18]
On the VMware Tanzu Docs site at [https://greenplum.docs.pivotal.io/6-14/main/index.html](https://greenplum.docs.pivotal.io/6-14/main/index.html) the document is titled "VMWare Tanzu™ Greenplum® 6.14 Documentation". however if one downloads the [PDF ](https://greenplum.docs.pivotal.io/6-14/pdf/GPDB614Docs.pdf)link on the right of the page, the PDF document (GPDB614Docs.pdf) is titled

Pivotal™ Greenplum Database®
Version 6.14
Pivotal Greenplum Database Documentation"

The title of the page also has VMware spelled as VMWare on the documentation site.
The naming conventions should be consistent across all the documents both at the site and the PDF, and should follow VMware branding guidelines

**Comment by VMWareJennyBeth** [comment]
Added to an existing doc story about branding of PDF being incorrect.
