### ISSUE TITLE
effective_cache_size Default value need to be corrected

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#180]
Page No : 1324

Issue: The Default value is 16GB, "512" is not required here.

Given: 
Value Range
floating point
Default 
**512 (16GB)**
Set Classifications
master
session
reload

[gpadmin@mdw_ipv4 pg_log]$ gpconfig -s effective_cache_size
Values on all segments are consistent
GUC          : effective_cache_size
Master  value: 16GB
Segment value: 16GB
[gpadmin@mdw_ipv4 pg_log]$

**Comment by fifthposition** [comment]
Docs story created.
