### ISSUE TITLE
gp_add_column_inherits_table_setting parameter issue

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#183]
Page No : 1328

Issue: This parameter cannot be set via gpconfig without using "--skipvalidation", though it works from DB (psql), as per the KB this parameter is protected one.

https://community.pivotal.io/s/article/gpconfig-failed-GUC-Validation-Failed-xxxxxx-cannot-be-changed-under-normal-condition?language=en_US

[gpadmin@mdw_ipv4 ~]$ gpconfig -s gp_add_column_inherits_table_setting
Values on all segments are consistent
GUC          : gp_add_column_inherits_table_setting
Master  value: off
Segment value: off
[gpadmin@mdw_ipv4 ~]$

[gpadmin@mdw_ipv4 ~]$ gpconfig -c gp_add_column_inherits_table_setting -v on
20210714:10:31:48:004323 gpconfig:mdw_ipv4:gpadmin-[CRITICAL]:-GUC Validation Failed: gp_add_column_inherits_table_setting cannot be changed under normal conditions. Please refer to gpconfig documentation.
GUC Validation Failed: gp_add_column_inherits_table_setting cannot be changed under normal conditions. Please refer to gpconfig documentation.
[gpadmin@mdw_ipv4 ~]$

[gpadmin@mdw_ipv4 ~]$ gpconfig -c gp_add_column_inherits_table_setting -v on --skipvalidation
20210716:11:29:26:014103 gpconfig:mdw_ipv4:gpadmin-[INFO]:-completed successfully with parameters '-c gp_add_column_inherits_table_setting -v on --skipvalidation'
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpstop -u
20210716:11:29:29:014177 gpstop:mdw_ipv4:gpadmin-[INFO]:-Starting gpstop with args: -u
20210716:11:29:29:014177 gpstop:mdw_ipv4:gpadmin-[INFO]:-Gathering information and validating the environment...
20210716:11:29:29:014177 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20210716:11:29:29:014177 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Segment details from master...
20210716:11:29:29:014177 gpstop:mdw_ipv4:gpadmin-[INFO]:-Greenplum Version: 'postgres (Greenplum Database) 6.16.0 build commit:5650be2b79197fed564dca8d734d10f2a76b876c'
20210716:11:29:29:014177 gpstop:mdw_ipv4:gpadmin-[INFO]:-Signalling all postmaster processes to reload
20210716:11:29:29:014177 gpstop:mdw_ipv4:gpadmin-[INFO]:---------------------------------------------
20210716:11:29:29:014177 gpstop:mdw_ipv4:gpadmin-[INFO]:-Some segment postmasters were not reloaded
20210716:11:29:29:014177 gpstop:mdw_ipv4:gpadmin-[INFO]:---------------------------------------------
20210716:11:29:29:014177 gpstop:mdw_ipv4:gpadmin-[INFO]:-   Host        Datadir                      Port   Status
20210716:11:29:29:014177 gpstop:mdw_ipv4:gpadmin-[INFO]:-   smdw_ipv4   /data1/gpdb/master/gpseg-1   5432   u
20210716:11:29:29:014177 gpstop:mdw_ipv4:gpadmin-[INFO]:---------------------------------------------
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ grep gp_add_column_inherits_table_setting $MASTER_DATA_DIRECTORY/postgresql.conf
gp_add_column_inherits_table_setting=on
[gpadmin@mdw_ipv4 ~]$

**Comment by fifthposition** [comment]
Docs story created.
