### ISSUE TITLE
Parameter can be set at session level

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#186]
1)
Page no : 1331,1332

Issue: Parameter(gp_create_table_random_default_distribution) can be set at session level, given as system.

gpadmin=# show gp_create_table_random_default_distribution;
 gp_create_table_random_default_distribution
---------------------------------------------
 off
(1 row)

gpadmin=# set gp_create_table_random_default_distribution = 'on';
SET
gpadmin=# \q
[gpadmin@mdw_ipv4 ~]$

**Comment by fifthposition** [comment]
Docs story created.
