### ISSUE TITLE
Parameter need reload for the change to take effect

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#187]
Page No : 1339

Issue: gp_fts_probe_interval need reload for the change to take effect, restart is given which is not needed.

Page No : 1340

Issue: gp_fts_probe_retries need reload for the change to take effect, restart is given which is not needed.

Page No : 1340

Issue: gp_fts_probe_timeout need reload for the change to take effect, restart is given which is not needed.

Page No : 1346

Issue: gp_interconnect_type need reload for the change to take effect, restart is given which is not needed.

Page No : 1347

Issue: gp_max_packet_size need reload for the change to take effect, restart is given which is not needed.

Page No : 1353

Issue: gp_safefswritesize need reload for the change to take effect, restart is given which is not needed.

**Comment by fifthposition** [comment]
Docs story created.
