### ISSUE TITLE
Parameter need Reload and set at session level

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#189]
Page No : 1341

Issue: gp_gpperfmon_send_interval parameter can be set at session and need reload for the change to take effect.

gpadmin=# show gp_gpperfmon_send_interval;
 gp_gpperfmon_send_interval
----------------------------
 1
(1 row)

gpadmin=#
gpadmin=#
gpadmin=# set gp_gpperfmon_send_interval =5;
SET
gpadmin=#
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -c gp_gpperfmon_send_interval -v 2
20210719:09:58:48:004010 gpconfig:mdw_ipv4:gpadmin-[INFO]:-completed successfully with parameters '-c gp_gpperfmon_send_interval -v 2'
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpstop -u
20210719:09:58:58:004090 gpstop:mdw_ipv4:gpadmin-[INFO]:-Starting gpstop with args: -u
20210719:09:58:58:004090 gpstop:mdw_ipv4:gpadmin-[INFO]:-Gathering information and validating the environment...
20210719:09:58:58:004090 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20210719:09:58:58:004090 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Segment details from master...
20210719:09:58:58:004090 gpstop:mdw_ipv4:gpadmin-[INFO]:-Greenplum Version: 'postgres (Greenplum Database) 6.16.0 build commit:5650be2b79197fed564dca8d734d10f2a76b876c'
20210719:09:58:58:004090 gpstop:mdw_ipv4:gpadmin-[INFO]:-Signalling all postmaster processes to reload
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s gp_gpperfmon_send_interval
Values on all segments are consistent
GUC          : gp_gpperfmon_send_interval
Master  value: 2
Segment value: 2
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$

2)

Page No : 1342

Issue: gpperfmon_log_alert_level parameter can be set at session and need reload for the change to take effect.

[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s gpperfmon_log_alert_level
Values on all segments are consistent
GUC          : gpperfmon_log_alert_level
Master  value: none
Segment value: none
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ psql
psql (9.4.24)
Type "help" for help.

gpadmin=#
gpadmin=# show gpperfmon_log_alert_level;
 gpperfmon_log_alert_level
---------------------------
 none
(1 row)

gpadmin=#
gpadmin=# set gpperfmon_log_alert_level = 'error';
SET
gpadmin=# \q
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -c gpperfmon_log_alert_level -v error
20210719:10:05:14:005075 gpconfig:mdw_ipv4:gpadmin-[INFO]:-completed successfully with parameters '-c gpperfmon_log_alert_level -v error'
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpstop -u
20210719:10:05:22:005154 gpstop:mdw_ipv4:gpadmin-[INFO]:-Starting gpstop with args: -u
20210719:10:05:22:005154 gpstop:mdw_ipv4:gpadmin-[INFO]:-Gathering information and validating the environment...
20210719:10:05:22:005154 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20210719:10:05:22:005154 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Segment details from master...
20210719:10:05:22:005154 gpstop:mdw_ipv4:gpadmin-[INFO]:-Greenplum Version: 'postgres (Greenplum Database) 6.16.0 build commit:5650be2b79197fed564dca8d734d10f2a76b876c'
20210719:10:05:22:005154 gpstop:mdw_ipv4:gpadmin-[INFO]:-Signalling all postmaster processes to reload
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s gpperfmon_log_alert_level
Values on all segments are consistent
GUC          : gpperfmon_log_alert_level
Master  value: error
Segment value: error
[gpadmin@mdw_ipv4 ~]$

Page No: 1351

Issue: gp_resqueue_memory_policy parameter can be set at session and need reload for the change to take effect.

**Comment by fifthposition** [comment]
Docs story created.
