### ISSUE TITLE
Release notes missing opensource unsupported disclaimer

### ISSUE THREAD

**Issue by indranil-cg** [greenplum-db/sre-test#19]
The Greenplum 6.14 release notes PDF at [https://greenplum.docs.pivotal.io/6-14/pdf/GPDB614Docs.pdf](https://greenplum.docs.pivotal.io/6-14/pdf/GPDB614Docs.pdf) has a note in Pg14, Chapter 1 that says

VMware Tanzu Greenplum 6 is based on the open source Greenplum Database project code.
**Important**: VMware does not provide support for open source versions of Greenplum Database.
Only VMware Tanzu Greenplum Database is supported by VMware

However the Documentation site at [https://greenplum.docs.pivotal.io/6-14/relnotes/gpdb-614-release-notes.html](https://greenplum.docs.pivotal.io/6-14/relnotes/gpdb-614-release-notes.html) has only

VMware Tanzu Greenplum 6 is based on the open source Greenplum Database project code.

The note about the opensource Greenplum not being supported by VMware is missing.

**Comment by VMWareJennyBeth** [comment]
Reopening until I've created a doc story for this.

**Comment by VMWareJennyBeth** [comment]
Sorry, mistake.

**Comment by VMWareJennyBeth** [comment]
These notes are being removed in an upcoming release.
