### ISSUE TITLE
wrong format

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#192]
Page No : 1334

Issue: for parameter gp_dynamic_partition_pruning in table content value for "Value Range" given as "on/off", which usually given as Boolean.

This should be in sync with rest.

Page No : 1347

Issue: gp_max_plan_size table content for "Set Classifications" not correct.

Given:
Set Classifications
master
superuser
session

To Be:
master
superuser
session
reload

Page No: 1349

Issue: gp_resgroup_memory_policy parameter change takes effect at reload, given as "restart/reload". 

Page No: 1349

Issue: gp_resource_group_bypass  table content for "Set Classifications" not correct.

Given:
Set Classifications
session

To Be:
local
session
reload

Page No: 1351

Issue: gp_resource_group_queuing_timeout table content for "Set Classifications" not correct.

Given:
Set Classifications
master
system
session
reload

To Be:
master
session
reload

Page No: 

Issue: gp_segment_connect_timeout parameter can be set at session level, given as system.

Given:
Set Classifications
local
system
reload

To Be:
Set Classifications
local
session
reload

**Comment by fifthposition** [comment]
Docs story created.
