### ISSUE TITLE
Parameter can be set at session and reload needed to take effect

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#193]
Page No : 1334

Issue : gp_enable_direct_dispatch Parameter can be set at session and reload needed to take effect.

Given:
Set Classifications
master
system
restart

To Be:
Set Classifications
master
session
reload

Testing:
gpadmin=#
gpadmin=# set gp_enable_direct_dispatch = off;
SET
gpadmin=#

[gpadmin@mdw_ipv4 pg_log]$
[gpadmin@mdw_ipv4 pg_log]$ gpconfig -c gp_enable_direct_dispatch -v off
20210718:19:09:30:024984 gpconfig:mdw_ipv4:gpadmin-[INFO]:-completed successfully with parameters '-c gp_enable_direct_dispatch -v off'
[gpadmin@mdw_ipv4 pg_log]$
[gpadmin@mdw_ipv4 pg_log]$
[gpadmin@mdw_ipv4 pg_log]$ gpstop -u
20210718:19:09:33:025058 gpstop:mdw_ipv4:gpadmin-[INFO]:-Starting gpstop with args: -u
20210718:19:09:33:025058 gpstop:mdw_ipv4:gpadmin-[INFO]:-Gathering information and validating the environment...
20210718:19:09:33:025058 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20210718:19:09:33:025058 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Segment details from master...
20210718:19:09:33:025058 gpstop:mdw_ipv4:gpadmin-[INFO]:-Greenplum Version: 'postgres (Greenplum Database) 6.16.0 build commit:5650be2b79197fed564dca8d734d10f2a76b876c'
20210718:19:09:33:025058 gpstop:mdw_ipv4:gpadmin-[INFO]:-Signalling all postmaster processes to reload

[gpadmin@mdw_ipv4 pg_log]$
[gpadmin@mdw_ipv4 pg_log]$
[gpadmin@mdw_ipv4 pg_log]$ gpconfig -s gp_enable_direct_dispatch
Values on all segments are consistent
GUC          : gp_enable_direct_dispatch
Master  value: off
Segment value: off
[gpadmin@mdw_ipv4 pg_log]$
[gpadmin@mdw_ipv4 pg_log]$

Page No : 1351

Issue: gp_resqueue_memory_policy Parameter can be set at session and reload needed to take effect.

gpadmin=# show gp_resqueue_memory_policy;
 gp_resqueue_memory_policy
---------------------------
 eager_free
(1 row)

gpadmin=#
gpadmin=#
gpadmin=# set gp_resqueue_memory_policy='auto';
SET
gpadmin=#
gpadmin=#
gpadmin=# show gp_resqueue_memory_policy;
 gp_resqueue_memory_policy
---------------------------
 auto
(1 row)

gpadmin=#
gpadmin=#
gpadmin=# \q
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s gp_resqueue_memory_policy
Values on all segments are consistent
GUC          : gp_resqueue_memory_policy
Master  value: eager_free
Segment value: eager_free
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -c gp_resqueue_memory_policy -v auto
20210720:15:07:41:030964 gpconfig:mdw_ipv4:gpadmin-[INFO]:-completed successfully with parameters '-c gp_resqueue_memory_policy -v auto'
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpstop -u
20210720:15:07:46:031041 gpstop:mdw_ipv4:gpadmin-[INFO]:-Starting gpstop with args: -u
20210720:15:07:46:031041 gpstop:mdw_ipv4:gpadmin-[INFO]:-Gathering information and validating the environment...
20210720:15:07:46:031041 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20210720:15:07:46:031041 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Segment details from master...
20210720:15:07:46:031041 gpstop:mdw_ipv4:gpadmin-[INFO]:-Greenplum Version: 'postgres (Greenplum Database) 6.16.0 build commit:5650be2b79197fed564dca8d734d10f2a76b876c'
20210720:15:07:46:031041 gpstop:mdw_ipv4:gpadmin-[INFO]:-Signalling all postmaster processes to reload
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s gp_resqueue_memory_policy
Values on all segments are consistent
GUC          : gp_resqueue_memory_policy
Master  value: auto
Segment value: auto
[gpadmin@mdw_ipv4 ~]$

**Comment by fifthposition** [comment]
The second parameter was already mentioned in #189.

**Comment by fifthposition** [comment]
Docs story created for first issue.
