### ISSUE TITLE
In GPDB 6.14 Release Notes, there is an incorrect GPDB 5 upgrade not support reference

### ISSUE THREAD

**Issue by edespino** [greenplum-db/sre-test#20]
The [GPDB 6.14 Release Notes](https://gpdb.docs.pivotal.io/6-14/relnotes/gpdb-614-release-notes.html) incorrectly indicate there is no direct upgrades from Greenplum 5 releases. With the release of gpupgrade, this should be removed. I believe there are multiple locations across the docs that should be updated.

Here is the current incorrect text:

**Note: Greenplum 6 does not support direct upgrades from Greenplum 4 or Greenplum 5 releases, or from earlier Greenplum 6 Beta releases.**

**Comment by VMWareJennyBeth** [comment]
Doc story created.
