### ISSUE TITLE
Parameter can be set at session level

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#207]
Page No: 1355

Issue: gp_vmem_idle_resource_timeout parameter can be set at session level, given as system "Set Classifications".

gpadmin=# show gp_vmem_idle_resource_timeout;
 gp_vmem_idle_resource_timeout
-------------------------------
 18s
(1 row)

gpadmin=#
gpadmin=# set gp_vmem_idle_resource_timeout='20s';
SET
gpadmin=#

**Comment by fifthposition** [comment]
Docs story created.
