### ISSUE TITLE
ignore_checksum_failure parameter issues

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#208]
Page No : 1358

Issue: ignore_checksum_failure parameter can be set at session and reload enough for change to take effect.

gpadmin=# show ignore_checksum_failure;
 ignore_checksum_failure
-------------------------
 off
(1 row)

gpadmin=#
gpadmin=#
gpadmin=# set ignore_checksum_failure = on;
SET
gpadmin=#
[gpadmin@mdw_ipv4 ~]$ gpconfig -s ignore_checksum_failure
Values on all segments are consistent
GUC          : ignore_checksum_failure
Master  value: off
Segment value: off
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -c ignore_checksum_failure -v on
20210722:13:06:54:023714 gpconfig:mdw_ipv4:gpadmin-[INFO]:-completed successfully with parameters '-c ignore_checksum_failure -v on'
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpstop -u
20210722:13:07:05:023798 gpstop:mdw_ipv4:gpadmin-[INFO]:-Starting gpstop with args: -u
20210722:13:07:05:023798 gpstop:mdw_ipv4:gpadmin-[INFO]:-Gathering information and validating the environment...
20210722:13:07:05:023798 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20210722:13:07:05:023798 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Segment details from master...
20210722:13:07:05:023798 gpstop:mdw_ipv4:gpadmin-[INFO]:-Greenplum Version: 'postgres (Greenplum Database) 6.16.0 build commit:5650be2b79197fed564dca8d734d10f2a76b876c'
20210722:13:07:05:023798 gpstop:mdw_ipv4:gpadmin-[INFO]:-Signalling all postmaster processes to reload
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s ignore_checksum_failure
Values on all segments are consistent
GUC          : ignore_checksum_failure
Master  value: on
Segment value: on
[gpadmin@mdw_ipv4 ~]$

**Comment by fifthposition** [comment]
Docs story created.
