### ISSUE TITLE
krb_server_keyfile parameter issues

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#210]
Page No : 1359

Issues: 
1)
This Parameter krb_server_keyfile Default value is set to below, but given as unset.

Given:
Default
Unset

- In system it's set to

[gpadmin@mdw_ipv4 ~]$ gpconfig -s krb_server_keyfile
Values on all segments are consistent
GUC          : krb_server_keyfile
Master  value: FILE:/usr/local/greenplum-db-devel/etc/postgresql/krb5.keytab
Segment value: FILE:/usr/local/greenplum-db-devel/etc/postgresql/krb5.keytab
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$

2) 
The change takes effect on reload, but given as restart

Given
Set Classifications
master
system
**restart**

To Be:
Set Classifications
master
system
reload

[gpadmin@mdw_ipv4 ~]$ gpconfig -s krb_server_keyfile
Values on all segments are consistent
GUC          : krb_server_keyfile
Master  value: FILE:/usr/local/greenplum-db-devel/etc/postgresql/krb5.keytab
Segment value: FILE:/usr/local/greenplum-db-devel/etc/postgresql/krb5.keytab
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -c krb_server_keyfile -v 'FILE:/usr/local/greenplum-db-devel/etc/postgresql/krb5.keytab1'
20210722:16:24:38:010671 gpconfig:mdw_ipv4:gpadmin-[INFO]:-completed successfully with parameters '-c krb_server_keyfile -v FILE:/usr/local/greenplum-db-devel/etc/postgresql/krb5.keytab1'
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpstop -u
20210722:16:24:43:010748 gpstop:mdw_ipv4:gpadmin-[INFO]:-Starting gpstop with args: -u
20210722:16:24:43:010748 gpstop:mdw_ipv4:gpadmin-[INFO]:-Gathering information and validating the environment...
20210722:16:24:43:010748 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20210722:16:24:43:010748 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Segment details from master...
20210722:16:24:43:010748 gpstop:mdw_ipv4:gpadmin-[INFO]:-Greenplum Version: 'postgres (Greenplum Database) 6.16.0 build commit:5650be2b79197fed564dca8d734d10f2a76b876c'
20210722:16:24:43:010748 gpstop:mdw_ipv4:gpadmin-[INFO]:-Signalling all postmaster processes to reload
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s krb_server_keyfile
Values on all segments are consistent
GUC          : krb_server_keyfile
Master  value: FILE:/usr/local/greenplum-db-devel/etc/postgresql/krb5.keytab1
Segment value: FILE:/usr/local/greenplum-db-devel/etc/postgresql/krb5.keytab1
[gpadmin@mdw_ipv4 ~]$

**Comment by fifthposition** [comment]
Docs story created.

**Comment by fifthposition** [comment]
@edespino How can I find out the default value of `krb_server_keyfile`?
