### ISSUE TITLE
lc_messages parameter issues

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#211]
1)
Page No : 1360

Issues:  lc_messages Parameter can be set at session level and need reload for change to take effect

Testing:
gpadmin=# show lc_messages;
 lc_messages
-------------
 en_US.utf8
(1 row)

gpadmin=#
gpadmin=#
gpadmin=#
gpadmin=# set lc_messages = 'en_GB.utf8';
SET
gpadmin=# \q
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s lc_messages
Values on all segments are consistent
GUC          : lc_messages
Master  value: en_US.utf8
Segment value: en_US.utf8
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -c lc_messages -v en_GB.utf8
20210722:16:52:31:015257 gpconfig:mdw_ipv4:gpadmin-[INFO]:-completed successfully with parameters '-c lc_messages -v en_GB.utf8'
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpstop -u
20210722:16:54:10:015488 gpstop:mdw_ipv4:gpadmin-[INFO]:-Starting gpstop with args: -u
20210722:16:54:10:015488 gpstop:mdw_ipv4:gpadmin-[INFO]:-Gathering information and validating the environment...
20210722:16:54:10:015488 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20210722:16:54:10:015488 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Segment details from master...
20210722:16:54:10:015488 gpstop:mdw_ipv4:gpadmin-[INFO]:-Greenplum Version: 'postgres (Greenplum Database) 6.16.0 build commit:5650be2b79197fed564dca8d734d10f2a76b876c'
20210722:16:54:10:015488 gpstop:mdw_ipv4:gpadmin-[INFO]:-Signalling all postmaster processes to reload
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s lc_messages
Values on all segments are consistent
GUC          : lc_messages
Master  value: en_GB.utf8
Segment value: en_GB.utf8
[gpadmin@mdw_ipv4 ~]$

2)

Page No : 1360

Issue: lc_monetary Parameter can be set at session level and need reload for change to take effect.

**Comment by fifthposition** [comment]
Docs story created.
