### ISSUE TITLE
Parameter need reload for change to take effect

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#213]
Page No : Multiple pages.

Issue: Below parameters need reload for change to take effect, given as restart.

log_connections
log_disconnections
log_dispatch_stats
log_hostname
log_truncate_on_rotation
maintenance_work_mem
max_slot_wal_keep_size
pljava_classpath_insecure
pljava_statement_cache_size
pljava_release_lingering_savepoints
wait_for_replication_threshold

**Sample testing**

[gpadmin@mdw_ipv4 ~]$ gpconfig -s log_dispatch_stats
Values on all segments are consistent
GUC          : log_dispatch_stats
Master  value: off
Segment value: off
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -c log_dispatch_stats -v on
20210723:06:43:27:018076 gpconfig:mdw_ipv4:gpadmin-[INFO]:-completed successfully with parameters '-c log_dispatch_stats -v on'
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpstop -u
20210723:06:43:48:018175 gpstop:mdw_ipv4:gpadmin-[INFO]:-Starting gpstop with args: -u
20210723:06:43:48:018175 gpstop:mdw_ipv4:gpadmin-[INFO]:-Gathering information and validating the environment...
20210723:06:43:48:018175 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20210723:06:43:48:018175 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Segment details from master...
20210723:06:43:48:018175 gpstop:mdw_ipv4:gpadmin-[INFO]:-Greenplum Version: 'postgres (Greenplum Database) 6.16.0 build commit:5650be2b79197fed564dca8d734d10f2a76b876c'
20210723:06:43:48:018175 gpstop:mdw_ipv4:gpadmin-[INFO]:-Signalling all postmaster processes to reload
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s log_dispatch_stats
Values on all segments are consistent
GUC          : log_dispatch_stats
Master  value: on
Segment value: on
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$

**log_hostname testing:**

[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s log_hostname
Values on all segments are consistent
GUC          : log_hostname
Master  value: off
Segment value: off
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ psql
psql (9.4.24)
Type "help" for help.

gpadmin=# show log_hostname;
 log_hostname
--------------
 off
(1 row)

gpadmin=# set log_hostname = on;
ERROR:  parameter "log_hostname" cannot be changed now
gpadmin=# \q
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -c log_hostname -v on
20210725:14:02:02:003101 gpconfig:mdw_ipv4:gpadmin-[INFO]:-completed successfully with parameters '-c log_hostname -v on'
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpstop -u
20210725:14:02:11:003181 gpstop:mdw_ipv4:gpadmin-[INFO]:-Starting gpstop with args: -u
20210725:14:02:11:003181 gpstop:mdw_ipv4:gpadmin-[INFO]:-Gathering information and validating the environment...
20210725:14:02:11:003181 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20210725:14:02:11:003181 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Segment details from master...
20210725:14:02:11:003181 gpstop:mdw_ipv4:gpadmin-[INFO]:-Greenplum Version: 'postgres (Greenplum Database) 6.16.0 build commit:5650be2b79197fed564dca8d734d10f2a76b876c'
20210725:14:02:11:003181 gpstop:mdw_ipv4:gpadmin-[INFO]:-Signalling all postmaster processes to reload
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s log_hostname
20210725:14:02:16:003219 gpconfig:mdw_ipv4:gpadmin-[ERROR]:-Failed to retrieve GUC information: error 'ERROR:  interconnect error: Could not parse remote listener address: 'mdw_ipv4' port '31247': Name or service not known  (seg0 slice1 10.0.25.114:4000 pid=24872)
DETAIL:  getaddrinfo() unable to parse address: 'mdw_ipv4'
CONTEXT:  SQL function "gp_param_setting" statement 1
' in 'select * from gp_toolkit.gp_param_setting('log_hostname')'
'NoneType' object is not iterable
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s log_hostname
20210725:14:03:41:003571 gpconfig:mdw_ipv4:gpadmin-[ERROR]:-Failed to retrieve GUC information: error 'ERROR:  interconnect error: Could not parse remote listener address: 'mdw_ipv4' port '35196': Name or service not known  (seg0 slice1 10.0.25.114:4000 pid=25392)
DETAIL:  getaddrinfo() unable to parse address: 'mdw_ipv4'
CONTEXT:  SQL function "gp_param_setting" statement 1
' in 'select * from gp_toolkit.gp_param_setting('log_hostname')'
'NoneType' object is not iterable
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -r log_hostname
20210725:14:04:09:003649 gpconfig:mdw_ipv4:gpadmin-[INFO]:-completed successfully with parameters '-r log_hostname'
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpstop -u
20210725:14:04:18:003728 gpstop:mdw_ipv4:gpadmin-[INFO]:-Starting gpstop with args: -u
20210725:14:04:18:003728 gpstop:mdw_ipv4:gpadmin-[INFO]:-Gathering information and validating the environment...
20210725:14:04:18:003728 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20210725:14:04:18:003728 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Segment details from master...
20210725:14:04:18:003728 gpstop:mdw_ipv4:gpadmin-[INFO]:-Greenplum Version: 'postgres (Greenplum Database) 6.16.0 build commit:5650be2b79197fed564dca8d734d10f2a76b876c'
20210725:14:04:18:003728 gpstop:mdw_ipv4:gpadmin-[INFO]:-Signalling all postmaster processes to reload
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s log_hostname
Values on all segments are consistent
GUC          : log_hostname
Master  value: off
Segment value: off
[gpadmin@mdw_ipv4 ~]$

**Comment by fifthposition** [comment]
Docs story created.
