### ISSUE TITLE
Parameter can be set at session and need reload

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#218]
Page No: 1366

Issue: Parameter log_temp_files can be set at session and need reload, given as System and restart.

Testing:
[gpadmin@mdw_ipv4 ~]$ gpconfig -s log_temp_files
Values on all segments are consistent
GUC          : log_temp_files
Master  value: -1
Segment value: -1
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ psql
psql (9.4.24)
Type "help" for help.

gpadmin=#
gpadmin=# show log_temp_files;
 log_temp_files
----------------
 -1
(1 row)

gpadmin=#
gpadmin=# set log_temp_files = 0;
SET
gpadmin=#
gpadmin=# \q
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -c log_temp_files -v 0
20210726:02:48:12:003207 gpconfig:mdw_ipv4:gpadmin-[INFO]:-completed successfully with parameters '-c log_temp_files -v 0'
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpstop -u
20210726:02:48:21:003288 gpstop:mdw_ipv4:gpadmin-[INFO]:-Starting gpstop with args: -u
20210726:02:48:21:003288 gpstop:mdw_ipv4:gpadmin-[INFO]:-Gathering information and validating the environment...
20210726:02:48:21:003288 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20210726:02:48:21:003288 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Segment details from master...
20210726:02:48:21:003288 gpstop:mdw_ipv4:gpadmin-[INFO]:-Greenplum Version: 'postgres (Greenplum Database) 6.16.0 build commit:5650be2b79197fed564dca8d734d10f2a76b876c'
20210726:02:48:21:003288 gpstop:mdw_ipv4:gpadmin-[INFO]:-Signalling all postmaster processes to reload
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s log_temp_files
Values on all segments are consistent
GUC          : log_temp_files
Master  value: 0
Segment value: 0
[gpadmin@mdw_ipv4 ~]$

Page No : 1370

Issue: Parameter max_stack_depth can be set at session and need reload, given as System and restart.

Testing:

[gpadmin@mdw_ipv4 ~]$ psql
psql (9.4.24)
Type "help" for help.

gpadmin=#
gpadmin=# show max_stack_depth;
 max_stack_depth
-----------------
 2MB
(1 row)

gpadmin=# set max_stack_depth = '4MB';
SET
gpadmin=# \q
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s max_stack_depth
Values on all segments are consistent
GUC          : max_stack_depth
Master  value: 2MB
Segment value: 2MB
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -c max_stack_depth -v 4MB
20210726:08:22:30:003313 gpconfig:mdw_ipv4:gpadmin-[INFO]:-completed successfully with parameters '-c max_stack_depth -v 4MB'
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpstop -u
20210726:08:22:42:003396 gpstop:mdw_ipv4:gpadmin-[INFO]:-Starting gpstop with args: -u
20210726:08:22:42:003396 gpstop:mdw_ipv4:gpadmin-[INFO]:-Gathering information and validating the environment...
20210726:08:22:42:003396 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20210726:08:22:42:003396 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Segment details from master...
20210726:08:22:42:003396 gpstop:mdw_ipv4:gpadmin-[INFO]:-Greenplum Version: 'postgres (Greenplum Database) 6.16.0 build commit:5650be2b79197fed564dca8d734d10f2a76b876c'
20210726:08:22:42:003396 gpstop:mdw_ipv4:gpadmin-[INFO]:-Signalling all postmaster processes to reload
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s max_stack_depth
Values on all segments are consistent
GUC          : max_stack_depth
Master  value: 4MB
Segment value: 4MB
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$

Page No: 1373

Issue: optimizer_control can be set at session and need reload, given as System and restart.

[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s optimizer_control
Values on all segments are consistent
GUC          : optimizer_control
Master  value: on
Segment value: on
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ psql
psql (9.4.24)
Type "help" for help.

gpadmin=#
gpadmin=# set optimizer_control =off;
SET
gpadmin=# \q
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -c optimizer_control -v off
20210726:11:27:21:017724 gpconfig:mdw_ipv4:gpadmin-[INFO]:-completed successfully with parameters '-c optimizer_control -v off'
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpstop -u
20210726:11:27:29:017803 gpstop:mdw_ipv4:gpadmin-[INFO]:-Starting gpstop with args: -u
20210726:11:27:29:017803 gpstop:mdw_ipv4:gpadmin-[INFO]:-Gathering information and validating the environment...
20210726:11:27:29:017803 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20210726:11:27:29:017803 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Segment details from master...
20210726:11:27:29:017803 gpstop:mdw_ipv4:gpadmin-[INFO]:-Greenplum Version: 'postgres (Greenplum Database) 6.16.0 build commit:5650be2b79197fed564dca8d734d10f2a76b876c'
20210726:11:27:29:017803 gpstop:mdw_ipv4:gpadmin-[INFO]:-Signalling all postmaster processes to reload
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s optimizer_control
Values on all segments are consistent
GUC          : optimizer_control
Master  value: off
Segment value: off
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -r optimizer_control
20210726:11:33:25:018292 gpconfig:mdw_ipv4:gpadmin-[INFO]:-completed successfully with parameters '-r optimizer_control'
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpstop -u
20210726:11:33:30:018370 gpstop:mdw_ipv4:gpadmin-[INFO]:-Starting gpstop with args: -u
20210726:11:33:30:018370 gpstop:mdw_ipv4:gpadmin-[INFO]:-Gathering information and validating the environment...
20210726:11:33:30:018370 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20210726:11:33:30:018370 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Segment details from master...
20210726:11:33:30:018370 gpstop:mdw_ipv4:gpadmin-[INFO]:-Greenplum Version: 'postgres (Greenplum Database) 6.16.0 build commit:5650be2b79197fed564dca8d734d10f2a76b876c'
20210726:11:33:30:018370 gpstop:mdw_ipv4:gpadmin-[INFO]:-Signalling all postmaster processes to reload
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s optimizer_control
Values on all segments are consistent
GUC          : optimizer_control
Master  value: on
Segment value: on
[gpadmin@mdw_ipv4 ~]$

Issue: resource_cleanup_gangs_on_wait can be set at session and need reload, given as System and restart.

[gpadmin@mdw_ipv4 ~]$ psql
psql (9.4.24)
Type "help" for help.

gpadmin=#
gpadmin=# show resource_cleanup_gangs_on_wait;
 resource_cleanup_gangs_on_wait
--------------------------------
 on
(1 row)

gpadmin=#
gpadmin=# set resource_cleanup_gangs_on_wait = off;
SET
gpadmin=# \q
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -c resource_cleanup_gangs_on_wait -v off
20210726:19:18:52:028245 gpconfig:mdw_ipv4:gpadmin-[INFO]:-completed successfully with parameters '-c resource_cleanup_gangs_on_wait -v off'
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s resource_cleanup_gangs_on_wait
Values on all segments are consistent
GUC          : resource_cleanup_gangs_on_wait
Master  value: on
Segment value: on
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpstop -u
20210726:19:19:03:028333 gpstop:mdw_ipv4:gpadmin-[INFO]:-Starting gpstop with args: -u
20210726:19:19:03:028333 gpstop:mdw_ipv4:gpadmin-[INFO]:-Gathering information and validating the environment...
20210726:19:19:03:028333 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20210726:19:19:03:028333 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Segment details from master...
20210726:19:19:03:028333 gpstop:mdw_ipv4:gpadmin-[INFO]:-Greenplum Version: 'postgres (Greenplum Database) 6.16.0 build commit:5650be2b79197fed564dca8d734d10f2a76b876c'
20210726:19:19:03:028333 gpstop:mdw_ipv4:gpadmin-[INFO]:-Signalling all postmaster processes to reload
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s resource_cleanup_gangs_on_wait
Values on all segments are consistent
GUC          : resource_cleanup_gangs_on_wait
Master  value: off
Segment value: off
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$

Issue: track_activities can be set at session and need reload, given as System and restart.

[gpadmin@mdw_ipv4 timezonesets]$ gpconfig -s track_activities
Values on all segments are consistent
GUC          : track_activities
Master  value: on
Segment value: on
[gpadmin@mdw_ipv4 timezonesets]$
[gpadmin@mdw_ipv4 timezonesets]$
[gpadmin@mdw_ipv4 timezonesets]$
[gpadmin@mdw_ipv4 timezonesets]$
[gpadmin@mdw_ipv4 timezonesets]$ pslq
-bash: pslq: command not found
[gpadmin@mdw_ipv4 timezonesets]$
[gpadmin@mdw_ipv4 timezonesets]$ cd
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ psql
psql (9.4.24)
Type "help" for help.

gpadmin=#
gpadmin=# show track_activities;
 track_activities
------------------
 on
(1 row)

gpadmin=#
gpadmin=#
gpadmin=# set track_activities = off;
SET
gpadmin=# \q
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s track_activities
Values on all segments are consistent
GUC          : track_activities
Master  value: on
Segment value: on
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -c track_activities -v off
20210727:17:53:22:015003 gpconfig:mdw_ipv4:gpadmin-[INFO]:-completed successfully with parameters '-c track_activities -v off'
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpstop -u
20210727:17:54:33:015160 gpstop:mdw_ipv4:gpadmin-[INFO]:-Starting gpstop with args: -u
20210727:17:54:33:015160 gpstop:mdw_ipv4:gpadmin-[INFO]:-Gathering information and validating the environment...
20210727:17:54:33:015160 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20210727:17:54:33:015160 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Segment details from master...
20210727:17:54:33:015160 gpstop:mdw_ipv4:gpadmin-[INFO]:-Greenplum Version: 'postgres (Greenplum Database) 6.16.0 build commit:5650be2b79197fed564dca8d734d10f2a76b876c'
20210727:17:54:33:015160 gpstop:mdw_ipv4:gpadmin-[INFO]:-Signalling all postmaster processes to reload
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s track_activities
Values on all segments are consistent
GUC          : track_activities
Master  value: off
Segment value: off
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$

**Comment by fifthposition** [comment]
Docs story created.
