### ISSUE TITLE
Incorrect Default value given in Doc

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#219]
Page No : 1367

Issue: maintenance_work_mem parameter default value given as 16MB, but system shows 64MB.

[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s maintenance_work_mem
Values on all segments are consistent
GUC          : maintenance_work_mem
Master  value: 64MB
Segment value: 64MB
[gpadmin@mdw_ipv4 ~]$
 

Page No: 1372

Issue: optimizer_array_expansion_threshold parameter default value given as 25, but system shows 100.

[gpadmin@mdw_ipv4 ~]$ gpconfig -s optimizer_array_expansion_threshold
Values on all segments are consistent
GUC          : optimizer_array_expansion_threshold
Master  value: 100
Segment value: 100
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$

**Comment by fifthposition** [comment]
Docs story created.
