### ISSUE TITLE
Parameter not exists in system given in Doc

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#222]
Page No: 1385

Issue: replication_timeout Parameter not exists in system given in Doc
Issue: regex_flavor Parameter not exists in system given in Doc

[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s replication_timeout
20210726:19:06:22:027318 gpconfig:mdw_ipv4:gpadmin-[ERROR]:-Failed to retrieve GUC information, guc does not exist: replication_timeout
'NoneType' object is not iterable
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ psql
psql (9.4.24)
Type "help" for help.

gpadmin=#
gpadmin=# show replication_timeout;
ERROR:  unrecognized configuration parameter "replication_timeout"
gpadmin=#
gpadmin=#

**Comment by fifthposition** [comment]
Docs story created.

**Comment by soumyadeep2007** [comment]
`replication_timeout` was renamed to `wal_sender_timeout`  in [commit](https://github.com/greenplum-db/gpdb/commit/6f60fdd7015b032bf49273c99f80913d57eac284)

The `regex_flavor` GUC was removed in [commit](https://github.com/greenplum-db/gpdb/commit/6f60fdd7015b032bf49273c99f80913d57eac284)
