### ISSUE TITLE
statement_mem parameter issue

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#223]
Page No : 1389

Issue: As per the given statement we cannot set statement_mem exceed to max_statement_mem.

Given:
Allocates segment host memory per query. The amount of memory allocated with this parameter cannot
exceed max_statement_mem or the memory limit on the resource queue or resource group through

Testing:

[gpadmin@mdw_ipv4 ~]$ gpconfig -s statement_mem
Values on all segments are consistent
GUC          : statement_mem
Master  value: 125MB
Segment value: 125MB
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s max_statement_mem
Values on all segments are consistent
GUC          : max_statement_mem
Master  value: 2000MB
Segment value: 2000MB
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -c statement_mem -v 4000MB
20210727:18:17:44:018301 gpconfig:mdw_ipv4:gpadmin-[INFO]:-completed successfully with parameters '-c statement_mem -v 4000MB'
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpstop -u
20210727:18:17:49:018378 gpstop:mdw_ipv4:gpadmin-[INFO]:-Starting gpstop with args: -u
20210727:18:17:49:018378 gpstop:mdw_ipv4:gpadmin-[INFO]:-Gathering information and validating the environment...
20210727:18:17:49:018378 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20210727:18:17:49:018378 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Segment details from master...
20210727:18:17:49:018378 gpstop:mdw_ipv4:gpadmin-[INFO]:-Greenplum Version: 'postgres (Greenplum Database) 6.16.0 build commit:5650be2b79197fed564dca8d734d10f2a76b876c'
20210727:18:17:49:018378 gpstop:mdw_ipv4:gpadmin-[INFO]:-Signalling all postmaster processes to reload
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s statement_mem
Values on all segments are consistent
GUC          : statement_mem
Master  value: 4000MB
Segment value: 4000MB
[gpadmin@mdw_ipv4 ~]$

**Comment by fifthposition** [comment]
@bala-cg Is this a product issue?
