### ISSUE TITLE
transaction_read_only parameter issue

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#227]
Page No : 1394

Issues: 
1) transaction_read_only works only with --skipvalidation
2) the changed parameter do not reflect even after restrat/reload.

Testing:
[gpadmin@mdw_ipv4 ~]$ gpconfig -s transaction_read_only
Values on all segments are consistent
GUC          : transaction_read_only
Master  value: off
Segment value: off
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ psql
psql (9.4.24)
Type "help" for help.

gpadmin=#
gpadmin=# show transaction_read_only;
 transaction_read_only
-----------------------
 off
(1 row)

gpadmin=#
gpadmin=# set transaction_read_only = pn;
ERROR:  parameter "transaction_read_only" requires a Boolean value
gpadmin=#
gpadmin=#
gpadmin=#
gpadmin=# set transaction_read_only = on;
SET
gpadmin=#
gpadmin=# \q
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -c transaction_read_only -v on
20210728:02:26:57:021620 gpconfig:mdw_ipv4:gpadmin-[CRITICAL]:-not a modifiable GUC: 'transaction_read_only'
not a modifiable GUC: 'transaction_read_only'
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -c transaction_read_only -v on --skipvalidation
20210728:02:27:07:021637 gpconfig:mdw_ipv4:gpadmin-[INFO]:-completed successfully with parameters '-c transaction_read_only -v on --skipvalidation'
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpstop -u
20210728:02:27:17:021717 gpstop:mdw_ipv4:gpadmin-[INFO]:-Starting gpstop with args: -u
20210728:02:27:17:021717 gpstop:mdw_ipv4:gpadmin-[INFO]:-Gathering information and validating the environment...
20210728:02:27:17:021717 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20210728:02:27:17:021717 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Segment details from master...
20210728:02:27:17:021717 gpstop:mdw_ipv4:gpadmin-[INFO]:-Greenplum Version: 'postgres (Greenplum Database) 6.16.0 build commit:5650be2b79197fed564dca8d734d10f2a76b876c'
20210728:02:27:17:021717 gpstop:mdw_ipv4:gpadmin-[INFO]:-Signalling all postmaster processes to reload
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s transaction_read_only
Values on all segments are consistent
GUC          : transaction_read_only
Master  value: off
Segment value: off
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpstart -arf
Usage: gpstart [--help] [options]

gpstart: error: no such option: -r
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpstop -arf
20210728:02:27:34:021778 gpstop:mdw_ipv4:gpadmin-[INFO]:-Starting gpstop with args: -arf
20210728:02:27:34:021778 gpstop:mdw_ipv4:gpadmin-[INFO]:-Gathering information and validating the environment...
20210728:02:27:34:021778 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20210728:02:27:34:021778 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Segment details from master...
20210728:02:27:34:021778 gpstop:mdw_ipv4:gpadmin-[INFO]:-Greenplum Version: 'postgres (Greenplum Database) 6.16.0 build commit:5650be2b79197fed564dca8d734d10f2a76b876c'
20210728:02:27:34:021778 gpstop:mdw_ipv4:gpadmin-[INFO]:-Commencing Master instance shutdown with mode='fast'
20210728:02:27:34:021778 gpstop:mdw_ipv4:gpadmin-[INFO]:-Master segment instance directory=/data1/gpdb/master/gpseg-1
20210728:02:27:34:021778 gpstop:mdw_ipv4:gpadmin-[INFO]:-Attempting forceful termination of any leftover master process
20210728:02:27:34:021778 gpstop:mdw_ipv4:gpadmin-[INFO]:-Terminating processes for segment /data1/gpdb/master/gpseg-1
20210728:02:27:34:021778 gpstop:mdw_ipv4:gpadmin-[INFO]:-Stopping master standby host smdw_ipv4 mode=fast
20210728:02:27:34:021778 gpstop:mdw_ipv4:gpadmin-[INFO]:-Successfully shutdown standby process on smdw_ipv4
20210728:02:27:34:021778 gpstop:mdw_ipv4:gpadmin-[INFO]:-Targeting dbid [2, 8, 3, 9, 4, 10, 5, 11, 6, 12, 7, 13] for shutdown
20210728:02:27:34:021778 gpstop:mdw_ipv4:gpadmin-[INFO]:-Commencing parallel primary segment instance shutdown, please wait...
20210728:02:27:34:021778 gpstop:mdw_ipv4:gpadmin-[INFO]:-0.00% of jobs completed
20210728:02:27:34:021778 gpstop:mdw_ipv4:gpadmin-[INFO]:-100.00% of jobs completed
20210728:02:27:34:021778 gpstop:mdw_ipv4:gpadmin-[INFO]:-Commencing parallel mirror segment instance shutdown, please wait...
20210728:02:27:34:021778 gpstop:mdw_ipv4:gpadmin-[INFO]:-0.00% of jobs completed
20210728:02:27:35:021778 gpstop:mdw_ipv4:gpadmin-[INFO]:-100.00% of jobs completed
20210728:02:27:35:021778 gpstop:mdw_ipv4:gpadmin-[INFO]:-----------------------------------------------------
20210728:02:27:35:021778 gpstop:mdw_ipv4:gpadmin-[INFO]:-   Segments stopped successfully      = 12
20210728:02:27:35:021778 gpstop:mdw_ipv4:gpadmin-[INFO]:-   Segments with errors during stop   = 0
20210728:02:27:35:021778 gpstop:mdw_ipv4:gpadmin-[INFO]:-----------------------------------------------------
20210728:02:27:35:021778 gpstop:mdw_ipv4:gpadmin-[INFO]:-Successfully shutdown 12 of 12 segment instances
20210728:02:27:35:021778 gpstop:mdw_ipv4:gpadmin-[INFO]:-Database successfully shutdown with no errors reported
20210728:02:27:35:021778 gpstop:mdw_ipv4:gpadmin-[INFO]:-Cleaning up leftover gpmmon process
20210728:02:27:35:021778 gpstop:mdw_ipv4:gpadmin-[INFO]:-No leftover gpmmon process found
20210728:02:27:35:021778 gpstop:mdw_ipv4:gpadmin-[INFO]:-Cleaning up leftover gpsmon processes
20210728:02:27:35:021778 gpstop:mdw_ipv4:gpadmin-[INFO]:-No leftover gpsmon processes on some hosts. not attempting forceful termination on these hosts
20210728:02:27:35:021778 gpstop:mdw_ipv4:gpadmin-[INFO]:-Cleaning up leftover shared memory
20210728:02:27:35:021778 gpstop:mdw_ipv4:gpadmin-[INFO]:-Restarting System...
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ psql
psql (9.4.24)
Type "help" for help.

gpadmin=#
gpadmin=# \q
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s transaction_read_only
Values on all segments are consistent
GUC          : transaction_read_only
Master  value: off
Segment value: off
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ grep transaction_read_only $MASTER_DATA_DIRECTORY/postgresql.conf
#default_transaction_read_only = off
#transaction_read_only=on
transaction_read_only=on
[gpadmin@mdw_ipv4 ~]$

**Comment by fifthposition** [comment]
@bala-cg Is this a product issue?

**Comment by bala-cg** [comment]
@fifthposition , this is bug, updated the label.
