### ISSUE TITLE
unix_socket_permissions parameter issues.

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#228]
Page No : 1395

Issues:
1)Default value not in sync Doc to system, given 511 in Doc, system show 0777.
2) When we try to set this value to 0511 and restart don't work, we have to revert the change to start the DB.

[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s unix_socket_permissions
Values on all segments are consistent
GUC          : unix_socket_permissions
Master  value: 0777
Segment value: 0777
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s unix_socket_permissions -v ^C
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ psql
psql (9.4.24)
Type "help" for help.

gpadmin=#
gpadmin=# show unix_socket_permissions;
 unix_socket_permissions
-------------------------
 0777
(1 row)

gpadmin=#
gpadmin=# set unix_socket_permissions = 0511;
ERROR:  parameter "unix_socket_permissions" cannot be changed without restarting the server
gpadmin=#
gpadmin=#
gpadmin=# \q
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -c unix_socket_permissions -v 0511
20210728:03:14:56:028508 gpconfig:mdw_ipv4:gpadmin-[INFO]:-completed successfully with parameters '-c unix_socket_permissions -v 0511'
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpstop -u
20210728:03:15:08:028592 gpstop:mdw_ipv4:gpadmin-[INFO]:-Starting gpstop with args: -u
20210728:03:15:08:028592 gpstop:mdw_ipv4:gpadmin-[INFO]:-Gathering information and validating the environment...
20210728:03:15:08:028592 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20210728:03:15:08:028592 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Segment details from master...
20210728:03:15:09:028592 gpstop:mdw_ipv4:gpadmin-[INFO]:-Greenplum Version: 'postgres (Greenplum Database) 6.16.0 build commit:5650be2b79197fed564dca8d734d10f2a76b876c'
20210728:03:15:09:028592 gpstop:mdw_ipv4:gpadmin-[INFO]:-Signalling all postmaster processes to reload
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s unix_socket_permissions
Values on all segments are consistent
GUC          : unix_socket_permissions
Master  value: 0777
Segment value: 0777
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpstop -arf
20210728:03:15:19:028669 gpstop:mdw_ipv4:gpadmin-[INFO]:-Starting gpstop with args: -arf
20210728:03:15:19:028669 gpstop:mdw_ipv4:gpadmin-[INFO]:-Gathering information and validating the environment...
20210728:03:15:19:028669 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20210728:03:15:19:028669 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Segment details from master...
20210728:03:15:19:028669 gpstop:mdw_ipv4:gpadmin-[INFO]:-Greenplum Version: 'postgres (Greenplum Database) 6.16.0 build commit:5650be2b79197fed564dca8d734d10f2a76b876c'
20210728:03:15:19:028669 gpstop:mdw_ipv4:gpadmin-[INFO]:-Commencing Master instance shutdown with mode='fast'
20210728:03:15:19:028669 gpstop:mdw_ipv4:gpadmin-[INFO]:-Master segment instance directory=/data1/gpdb/master/gpseg-1
20210728:03:15:19:028669 gpstop:mdw_ipv4:gpadmin-[INFO]:-Attempting forceful termination of any leftover master process
20210728:03:15:19:028669 gpstop:mdw_ipv4:gpadmin-[INFO]:-Terminating processes for segment /data1/gpdb/master/gpseg-1
20210728:03:15:19:028669 gpstop:mdw_ipv4:gpadmin-[INFO]:-Stopping master standby host smdw_ipv4 mode=fast
20210728:03:15:19:028669 gpstop:mdw_ipv4:gpadmin-[INFO]:-Successfully shutdown standby process on smdw_ipv4
20210728:03:15:19:028669 gpstop:mdw_ipv4:gpadmin-[INFO]:-Targeting dbid [2, 8, 3, 9, 4, 10, 5, 11, 6, 12, 7, 13] for shutdown
20210728:03:15:19:028669 gpstop:mdw_ipv4:gpadmin-[INFO]:-Commencing parallel primary segment instance shutdown, please wait...
20210728:03:15:19:028669 gpstop:mdw_ipv4:gpadmin-[INFO]:-0.00% of jobs completed
20210728:03:15:20:028669 gpstop:mdw_ipv4:gpadmin-[INFO]:-100.00% of jobs completed
20210728:03:15:20:028669 gpstop:mdw_ipv4:gpadmin-[INFO]:-Commencing parallel mirror segment instance shutdown, please wait...
20210728:03:15:20:028669 gpstop:mdw_ipv4:gpadmin-[INFO]:-0.00% of jobs completed
20210728:03:15:20:028669 gpstop:mdw_ipv4:gpadmin-[INFO]:-100.00% of jobs completed
20210728:03:15:20:028669 gpstop:mdw_ipv4:gpadmin-[INFO]:-----------------------------------------------------
20210728:03:15:20:028669 gpstop:mdw_ipv4:gpadmin-[INFO]:-   Segments stopped successfully      = 12
20210728:03:15:20:028669 gpstop:mdw_ipv4:gpadmin-[INFO]:-   Segments with errors during stop   = 0
20210728:03:15:20:028669 gpstop:mdw_ipv4:gpadmin-[INFO]:-----------------------------------------------------
20210728:03:15:20:028669 gpstop:mdw_ipv4:gpadmin-[INFO]:-Successfully shutdown 12 of 12 segment instances
20210728:03:15:20:028669 gpstop:mdw_ipv4:gpadmin-[INFO]:-Database successfully shutdown with no errors reported
20210728:03:15:20:028669 gpstop:mdw_ipv4:gpadmin-[INFO]:-Cleaning up leftover gpmmon process
20210728:03:15:20:028669 gpstop:mdw_ipv4:gpadmin-[INFO]:-No leftover gpmmon process found
20210728:03:15:20:028669 gpstop:mdw_ipv4:gpadmin-[INFO]:-Cleaning up leftover gpsmon processes
20210728:03:15:20:028669 gpstop:mdw_ipv4:gpadmin-[INFO]:-No leftover gpsmon processes on some hosts. not attempting forceful termination on these hosts
20210728:03:15:20:028669 gpstop:mdw_ipv4:gpadmin-[INFO]:-Cleaning up leftover shared memory
20210728:03:15:20:028669 gpstop:mdw_ipv4:gpadmin-[INFO]:-Restarting System...

^C[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ grep unix_socket_permissions $MASTER_DATA_DIRECTORY/postgresql.conf
#unix_socket_permissions = 0777         # begin with 0 to use octal notation
unix_socket_permissions=0511
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ vi $MASTER_DATA_DIRECTORY/postgresql.conf
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -r^Cnix_socket_permissions
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpstrat -am
-bash: gpstrat: command not found
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpstart -am
20210728:03:17:33:028962 gpstart:mdw_ipv4:gpadmin-[INFO]:-Starting gpstart with args: -am
20210728:03:17:33:028962 gpstart:mdw_ipv4:gpadmin-[INFO]:-Gathering information and validating the environment...
20210728:03:17:33:028962 gpstart:mdw_ipv4:gpadmin-[INFO]:-Greenplum Binary Version: 'postgres (Greenplum Database) 6.16.0 build commit:5650be2b79197fed564dca8d734d10f2a76b876c'
20210728:03:17:33:028962 gpstart:mdw_ipv4:gpadmin-[INFO]:-Greenplum Catalog Version: '301908232'
20210728:03:17:33:028962 gpstart:mdw_ipv4:gpadmin-[WARNING]:-****************************************************************************
20210728:03:17:33:028962 gpstart:mdw_ipv4:gpadmin-[WARNING]:-Master-only start requested. Disruptive action if standby master configured.
20210728:03:17:33:028962 gpstart:mdw_ipv4:gpadmin-[WARNING]:-This is advisable only under the direct supervision of Greenplum support.
20210728:03:17:33:028962 gpstart:mdw_ipv4:gpadmin-[WARNING]:-This mode of operation is not supported in a production environment and
20210728:03:17:33:028962 gpstart:mdw_ipv4:gpadmin-[WARNING]:-may lead to a split-brain condition and possible unrecoverable data loss.
20210728:03:17:33:028962 gpstart:mdw_ipv4:gpadmin-[WARNING]:-****************************************************************************
20210728:03:17:33:028962 gpstart:mdw_ipv4:gpadmin-[INFO]:-Starting Master instance in admin mode
20210728:03:17:33:028962 gpstart:mdw_ipv4:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20210728:03:17:33:028962 gpstart:mdw_ipv4:gpadmin-[INFO]:-Obtaining Segment details from master...
20210728:03:17:33:028962 gpstart:mdw_ipv4:gpadmin-[INFO]:-Setting new master era
20210728:03:17:33:028962 gpstart:mdw_ipv4:gpadmin-[INFO]:-Master Started...
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -r unix_socket_permissions
20210728:03:17:41:028991 gpconfig:mdw_ipv4:gpadmin-[INFO]:-completed successfully with parameters '-r unix_socket_permissions'
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpstop -u
20210728:03:17:44:029064 gpstop:mdw_ipv4:gpadmin-[INFO]:-Starting gpstop with args: -u
20210728:03:17:44:029064 gpstop:mdw_ipv4:gpadmin-[INFO]:-Gathering information and validating the environment...
20210728:03:17:44:029064 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20210728:03:17:44:029064 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Segment details from master...
20210728:03:17:44:029064 gpstop:mdw_ipv4:gpadmin-[INFO]:-Greenplum Version: 'postgres (Greenplum Database) 6.16.0 build commit:5650be2b79197fed564dca8d734d10f2a76b876c'
20210728:03:17:44:029064 gpstop:mdw_ipv4:gpadmin-[INFO]:-Signalling all postmaster processes to reload
20210728:03:17:45:029064 gpstop:mdw_ipv4:gpadmin-[INFO]:---------------------------------------------
20210728:03:17:45:029064 gpstop:mdw_ipv4:gpadmin-[INFO]:-Some segment postmasters were not reloaded
20210728:03:17:45:029064 gpstop:mdw_ipv4:gpadmin-[INFO]:---------------------------------------------
20210728:03:17:45:029064 gpstop:mdw_ipv4:gpadmin-[INFO]:-   Host        Datadir                      Port   Status
20210728:03:17:45:029064 gpstop:mdw_ipv4:gpadmin-[INFO]:-   sdw2_ipv4   /data2/gpdb/mirror/gpseg1    5001   u
20210728:03:17:45:029064 gpstop:mdw_ipv4:gpadmin-[INFO]:-   smdw_ipv4   /data1/gpdb/master/gpseg-1   5432   u
20210728:03:17:45:029064 gpstop:mdw_ipv4:gpadmin-[INFO]:-   sdw2_ipv4   /data1/gpdb/primary/gpseg3   4000   u
20210728:03:17:45:029064 gpstop:mdw_ipv4:gpadmin-[INFO]:-   sdw2_ipv4   /data2/gpdb/primary/gpseg4   4001   u
20210728:03:17:45:029064 gpstop:mdw_ipv4:gpadmin-[INFO]:-   sdw2_ipv4   /data3/gpdb/mirror/gpseg2    5002   u
20210728:03:17:45:029064 gpstop:mdw_ipv4:gpadmin-[INFO]:-   sdw1_ipv4   /data2/gpdb/primary/gpseg1   4001   u
20210728:03:17:45:029064 gpstop:mdw_ipv4:gpadmin-[INFO]:-   sdw1_ipv4   /data3/gpdb/primary/gpseg2   4002   u
20210728:03:17:45:029064 gpstop:mdw_ipv4:gpadmin-[INFO]:-   sdw2_ipv4   /data1/gpdb/mirror/gpseg0    5000   u
20210728:03:17:45:029064 gpstop:mdw_ipv4:gpadmin-[INFO]:-   sdw2_ipv4   /data3/gpdb/primary/gpseg5   4002   u
20210728:03:17:45:029064 gpstop:mdw_ipv4:gpadmin-[INFO]:-   sdw1_ipv4   /data1/gpdb/mirror/gpseg3    5000   u
20210728:03:17:45:029064 gpstop:mdw_ipv4:gpadmin-[INFO]:-   sdw1_ipv4   /data2/gpdb/mirror/gpseg4    5001   u
20210728:03:17:45:029064 gpstop:mdw_ipv4:gpadmin-[INFO]:-   sdw1_ipv4   /data1/gpdb/primary/gpseg0   4000   u
20210728:03:17:45:029064 gpstop:mdw_ipv4:gpadmin-[INFO]:-   sdw1_ipv4   /data3/gpdb/mirror/gpseg5    5002   u
20210728:03:17:45:029064 gpstop:mdw_ipv4:gpadmin-[INFO]:---------------------------------------------
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpstop -arf
20210728:03:17:56:029141 gpstop:mdw_ipv4:gpadmin-[INFO]:-Starting gpstop with args: -arf
20210728:03:17:56:029141 gpstop:mdw_ipv4:gpadmin-[INFO]:-Gathering information and validating the environment...
20210728:03:17:56:029141 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20210728:03:17:56:029141 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Segment details from master...
20210728:03:17:56:029141 gpstop:mdw_ipv4:gpadmin-[INFO]:-Greenplum Version: 'postgres (Greenplum Database) 6.16.0 build commit:5650be2b79197fed564dca8d734d10f2a76b876c'
20210728:03:17:56:029141 gpstop:mdw_ipv4:gpadmin-[INFO]:-Commencing Master instance shutdown with mode='fast'
20210728:03:17:56:029141 gpstop:mdw_ipv4:gpadmin-[INFO]:-Master segment instance directory=/data1/gpdb/master/gpseg-1
20210728:03:17:56:029141 gpstop:mdw_ipv4:gpadmin-[INFO]:-Attempting forceful termination of any leftover master process
20210728:03:17:56:029141 gpstop:mdw_ipv4:gpadmin-[INFO]:-Terminating processes for segment /data1/gpdb/master/gpseg-1
20210728:03:17:56:029141 gpstop:mdw_ipv4:gpadmin-[INFO]:-Stopping master standby host smdw_ipv4 mode=fast
20210728:03:17:56:029141 gpstop:mdw_ipv4:gpadmin-[WARNING]:-Error occured while stopping the standby master: ExecutionError: 'non-zero rc: 1' occurred.  Details: 'ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 smdw_ipv4 ". /usr/local/greenplum-db-6.16.0/greenplum_path.sh; $GPHOME/bin/pg_ctl -D /data1/gpdb/master/gpseg-1 -m fast -w -t 120 stop"'  cmd had rc=1 completed=True halted=False
  stdout=''
  stderr='pg_ctl: PID file "/data1/gpdb/master/gpseg-1/postmaster.pid" does not exist
Is server running?
'
20210728:03:17:56:029141 gpstop:mdw_ipv4:gpadmin-[INFO]:-Successfully shutdown standby process on smdw_ipv4
20210728:03:17:56:029141 gpstop:mdw_ipv4:gpadmin-[INFO]:-Targeting dbid [2, 8, 3, 9, 4, 10, 5, 11, 6, 12, 7, 13] for shutdown
20210728:03:17:56:029141 gpstop:mdw_ipv4:gpadmin-[INFO]:-Commencing parallel primary segment instance shutdown, please wait...
20210728:03:17:56:029141 gpstop:mdw_ipv4:gpadmin-[INFO]:-0.00% of jobs completed
20210728:03:17:56:029141 gpstop:mdw_ipv4:gpadmin-[INFO]:-100.00% of jobs completed
20210728:03:17:56:029141 gpstop:mdw_ipv4:gpadmin-[INFO]:-Commencing parallel mirror segment instance shutdown, please wait...
20210728:03:17:56:029141 gpstop:mdw_ipv4:gpadmin-[INFO]:-0.00% of jobs completed
20210728:03:17:57:029141 gpstop:mdw_ipv4:gpadmin-[INFO]:-100.00% of jobs completed
20210728:03:17:57:029141 gpstop:mdw_ipv4:gpadmin-[INFO]:-----------------------------------------------------
20210728:03:17:57:029141 gpstop:mdw_ipv4:gpadmin-[INFO]:-   Segments stopped successfully      = 12
20210728:03:17:57:029141 gpstop:mdw_ipv4:gpadmin-[INFO]:-   Segments with errors during stop   = 0
20210728:03:17:57:029141 gpstop:mdw_ipv4:gpadmin-[INFO]:-----------------------------------------------------
20210728:03:17:57:029141 gpstop:mdw_ipv4:gpadmin-[INFO]:-Successfully shutdown 12 of 12 segment instances
20210728:03:17:57:029141 gpstop:mdw_ipv4:gpadmin-[INFO]:-Database successfully shutdown with no errors reported
20210728:03:17:57:029141 gpstop:mdw_ipv4:gpadmin-[INFO]:-Cleaning up leftover gpmmon process
20210728:03:17:57:029141 gpstop:mdw_ipv4:gpadmin-[INFO]:-No leftover gpmmon process found
20210728:03:17:57:029141 gpstop:mdw_ipv4:gpadmin-[INFO]:-Cleaning up leftover gpsmon processes
20210728:03:17:57:029141 gpstop:mdw_ipv4:gpadmin-[INFO]:-No leftover gpsmon processes on some hosts. not attempting forceful termination on these hosts
20210728:03:17:57:029141 gpstop:mdw_ipv4:gpadmin-[INFO]:-Cleaning up leftover shared memory
20210728:03:17:57:029141 gpstop:mdw_ipv4:gpadmin-[INFO]:-Restarting System...
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ psql
psql (9.4.24)
Type "help" for help.
gpadmin=# \q
[gpadmin@mdw_ipv4 ~]$

**Comment by fifthposition** [comment]
@bala-cg I think that the title should refer to "unix_socket_permissions" not "unix_socket_directories".

2) sounds like a product issue to me.

**Comment by fifthposition** [comment]
Docs story created for first issue.

**Comment by bala-cg** [comment]
@fifthposition, Yes Issue 2 is Bug, as Doc story is created for 1st issue, adding bug label to this one.

**Comment by bala-cg** [comment]
@fifthposition, Yes issue title is corrected.
