### ISSUE TITLE
Parameter can be set at session and need reload (set2)

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#229]
Page No : 1395, 1396

1)
Issue: Below Parameters can  set at session and need reload, given system and restart.

 update_process_title
vacuum_cost_delay
vacuum_cost_limit
vacuum_cost_page_dirty
vacuum_cost_page_hit
vacuum_cost_page_miss

2)
Issue: parameter vacuum_freeze_min_age issues( Default value not sync doc to system), and this parameter can be set at session and need reload, given system and restart.

Testing:

[gpadmin@mdw_ipv4 ~]$ gpconfig -s update_process_title
Values on all segments are consistent
GUC          : update_process_title
Master  value: on
Segment value: on
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ psql
psql (9.4.24)
Type "help" for help.

gpadmin=# \q
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ psql
psql (9.4.24)
Type "help" for help.

gpadmin=#
gpadmin=#
gpadmin=# show update_process_title;
 update_process_title
----------------------
 on
(1 row)

gpadmin=#
gpadmin=# set update_process_title = off;
SET
gpadmin=#
gpadmin=#
gpadmin=# \q
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ psql
psql (9.4.24)
Type "help" for help.

gpadmin=#
gpadmin=# show unix_socket_permissions;
 unix_socket_permissions
-------------------------
 0777
(1 row)

gpadmin=# set unix_socket_permissions = 0511;
ERROR:  parameter "unix_socket_permissions" cannot be changed without restarting the server
gpadmin=# \q
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s update_process_title
Values on all segments are consistent
GUC          : update_process_title
Master  value: on
Segment value: on
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -c update_process_title -v off
20210728:14:08:50:011846 gpconfig:mdw_ipv4:gpadmin-[INFO]:-completed successfully with parameters '-c update_process_title -v off'
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpstop -u
20210728:14:08:55:011922 gpstop:mdw_ipv4:gpadmin-[INFO]:-Starting gpstop with args: -u
20210728:14:08:55:011922 gpstop:mdw_ipv4:gpadmin-[INFO]:-Gathering information and validating the environment...
20210728:14:08:55:011922 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20210728:14:08:55:011922 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Segment details from master...
20210728:14:08:55:011922 gpstop:mdw_ipv4:gpadmin-[INFO]:-Greenplum Version: 'postgres (Greenplum Database) 6.16.0 build commit:5650be2b79197fed564dca8d734d10f2a76b876c'
20210728:14:08:55:011922 gpstop:mdw_ipv4:gpadmin-[INFO]:-Signalling all postmaster processes to reload
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s update_process_title
Values on all segments are consistent
GUC          : update_process_title
Master  value: off
Segment value: off
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -r update_process_title
20210728:14:44:45:014536 gpconfig:mdw_ipv4:gpadmin-[INFO]:-completed successfully with parameters '-r update_process_title'
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpstop -u
20210728:14:44:48:014613 gpstop:mdw_ipv4:gpadmin-[INFO]:-Starting gpstop with args: -u
20210728:14:44:48:014613 gpstop:mdw_ipv4:gpadmin-[INFO]:-Gathering information and validating the environment...
20210728:14:44:48:014613 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20210728:14:44:48:014613 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Segment details from master...
20210728:14:44:48:014613 gpstop:mdw_ipv4:gpadmin-[INFO]:-Greenplum Version: 'postgres (Greenplum Database) 6.16.0 build commit:5650be2b79197fed564dca8d734d10f2a76b876c'
20210728:14:44:48:014613 gpstop:mdw_ipv4:gpadmin-[INFO]:-Signalling all postmaster processes to reload
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s update_process_title
Values on all segments are consistent
GUC          : update_process_title
Master  value: on
Segment value: on
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s vacuum_cost_delay
Values on all segments are consistent
GUC          : vacuum_cost_delay
Master  value: 0
Segment value: 0
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ pslq
-bash: pslq: command not found
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ psql
psql (9.4.24)
Type "help" for help.

gpadmin=#
gpadmin=# show vacuum_cost_delay;
 vacuum_cost_delay
-------------------
 0
(1 row)

gpadmin=#
gpadmin=# set vacuum_cost_delay = 10;
SET
gpadmin=# \q
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -c vacuum_cost_delay -v 10
20210728:14:46:26:014773 gpconfig:mdw_ipv4:gpadmin-[INFO]:-completed successfully with parameters '-c vacuum_cost_delay -v 10'
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpstop -u
20210728:14:46:31:014849 gpstop:mdw_ipv4:gpadmin-[INFO]:-Starting gpstop with args: -u
20210728:14:46:31:014849 gpstop:mdw_ipv4:gpadmin-[INFO]:-Gathering information and validating the environment...
20210728:14:46:31:014849 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20210728:14:46:31:014849 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Segment details from master...
20210728:14:46:31:014849 gpstop:mdw_ipv4:gpadmin-[INFO]:-Greenplum Version: 'postgres (Greenplum Database) 6.16.0 build commit:5650be2b79197fed564dca8d734d10f2a76b876c'
20210728:14:46:31:014849 gpstop:mdw_ipv4:gpadmin-[INFO]:-Signalling all postmaster processes to reload
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s vacuum_cost_delay
Values on all segments are consistent
GUC          : vacuum_cost_delay
Master  value: 10ms
Segment value: 10ms
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s vacuum_cost_limit
Values on all segments are consistent
GUC          : vacuum_cost_limit
Master  value: 200
Segment value: 200
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ psql
psql (9.4.24)
Type "help" for help.

gpadmin=#
gpadmin=# show vacuum_cost_limit;
 vacuum_cost_limit
-------------------
 200
(1 row)

gpadmin=#
gpadmin=# set vacuum_cost_limit = 400;
SET
gpadmin=# \q
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -c vacuum_cost_limit -v 500
20210728:14:48:08:015008 gpconfig:mdw_ipv4:gpadmin-[INFO]:-completed successfully with parameters '-c vacuum_cost_limit -v 500'
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpstop -u
20210728:14:48:11:015083 gpstop:mdw_ipv4:gpadmin-[INFO]:-Starting gpstop with args: -u
20210728:14:48:11:015083 gpstop:mdw_ipv4:gpadmin-[INFO]:-Gathering information and validating the environment...
20210728:14:48:11:015083 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20210728:14:48:11:015083 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Segment details from master...
20210728:14:48:11:015083 gpstop:mdw_ipv4:gpadmin-[INFO]:-Greenplum Version: 'postgres (Greenplum Database) 6.16.0 build commit:5650be2b79197fed564dca8d734d10f2a76b876c'
20210728:14:48:11:015083 gpstop:mdw_ipv4:gpadmin-[INFO]:-Signalling all postmaster processes to reload
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s vacuum_cost_limit
Values on all segments are consistent
GUC          : vacuum_cost_limit
Master  value: 500
Segment value: 500
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -r vacuum_cost_limit
20210728:14:50:15:015280 gpconfig:mdw_ipv4:gpadmin-[INFO]:-completed successfully with parameters '-r vacuum_cost_limit'
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpstop -u
20210728:14:50:17:015354 gpstop:mdw_ipv4:gpadmin-[INFO]:-Starting gpstop with args: -u
20210728:14:50:17:015354 gpstop:mdw_ipv4:gpadmin-[INFO]:-Gathering information and validating the environment...
20210728:14:50:17:015354 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20210728:14:50:17:015354 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Segment details from master...
20210728:14:50:17:015354 gpstop:mdw_ipv4:gpadmin-[INFO]:-Greenplum Version: 'postgres (Greenplum Database) 6.16.0 build commit:5650be2b79197fed564dca8d734d10f2a76b876c'
20210728:14:50:17:015354 gpstop:mdw_ipv4:gpadmin-[INFO]:-Signalling all postmaster processes to reload
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s vacuum_cost_limit
Values on all segments are consistent
GUC          : vacuum_cost_limit
Master  value: 200
Segment value: 200
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s vacuum_cost_page_dirty
Values on all segments are consistent
GUC          : vacuum_cost_page_dirty
Master  value: 20
Segment value: 20
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ psql
psql (9.4.24)
Type "help" for help.

gpadmin=#
gpadmin=# show vacuum_cost_page_dirty;
 vacuum_cost_page_dirty
------------------------
 20
(1 row)

gpadmin=#
gpadmin=# set vacuum_cost_page_dirty = 40;
SET
gpadmin=# \q
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -c vacuum_cost_page_dirty -v 50
20210728:14:51:22:015487 gpconfig:mdw_ipv4:gpadmin-[INFO]:-completed successfully with parameters '-c vacuum_cost_page_dirty -v 50'
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpstop -u
20210728:14:51:25:015562 gpstop:mdw_ipv4:gpadmin-[INFO]:-Starting gpstop with args: -u
20210728:14:51:25:015562 gpstop:mdw_ipv4:gpadmin-[INFO]:-Gathering information and validating the environment...
20210728:14:51:25:015562 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20210728:14:51:25:015562 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Segment details from master...
20210728:14:51:25:015562 gpstop:mdw_ipv4:gpadmin-[INFO]:-Greenplum Version: 'postgres (Greenplum Database) 6.16.0 build commit:5650be2b79197fed564dca8d734d10f2a76b876c'
20210728:14:51:25:015562 gpstop:mdw_ipv4:gpadmin-[INFO]:-Signalling all postmaster processes to reload
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s vacuum_cost_page_dirty
Values on all segments are consistent
GUC          : vacuum_cost_page_dirty
Master  value: 50
Segment value: 50
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -r vacuum_cost_page_dirty
20210728:14:52:07:015639 gpconfig:mdw_ipv4:gpadmin-[INFO]:-completed successfully with parameters '-r vacuum_cost_page_dirty'
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpstop -u
20210728:14:52:10:015741 gpstop:mdw_ipv4:gpadmin-[INFO]:-Starting gpstop with args: -u
20210728:14:52:10:015741 gpstop:mdw_ipv4:gpadmin-[INFO]:-Gathering information and validating the environment...
20210728:14:52:10:015741 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20210728:14:52:10:015741 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Segment details from master...
20210728:14:52:10:015741 gpstop:mdw_ipv4:gpadmin-[INFO]:-Greenplum Version: 'postgres (Greenplum Database) 6.16.0 build commit:5650be2b79197fed564dca8d734d10f2a76b876c'
20210728:14:52:10:015741 gpstop:mdw_ipv4:gpadmin-[INFO]:-Signalling all postmaster processes to reload
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s vacuum_cost_page_dirty
Values on all segments are consistent
GUC          : vacuum_cost_page_dirty
Master  value: 20
Segment value: 20
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s vacuum_cost_page_hit
Values on all segments are consistent
GUC          : vacuum_cost_page_hit
Master  value: 1
Segment value: 1
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ pslq
-bash: pslq: command not found
[gpadmin@mdw_ipv4 ~]$ psql
psql (9.4.24)
Type "help" for help.

gpadmin=# show vacuum_cost_page_hit;
 vacuum_cost_page_hit
----------------------
 1
(1 row)

gpadmin=#
gpadmin=#
gpadmin=# set vacuum_cost_page_hit = 2;
SET
gpadmin=# \q
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -c vacuum_cost_page_hit -v 3
20210728:14:54:54:015981 gpconfig:mdw_ipv4:gpadmin-[INFO]:-completed successfully with parameters '-c vacuum_cost_page_hit -v 3'
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpstop -u
20210728:14:55:04:016061 gpstop:mdw_ipv4:gpadmin-[INFO]:-Starting gpstop with args: -u
20210728:14:55:04:016061 gpstop:mdw_ipv4:gpadmin-[INFO]:-Gathering information and validating the environment...
20210728:14:55:04:016061 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20210728:14:55:04:016061 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Segment details from master...
20210728:14:55:04:016061 gpstop:mdw_ipv4:gpadmin-[INFO]:-Greenplum Version: 'postgres (Greenplum Database) 6.16.0 build commit:5650be2b79197fed564dca8d734d10f2a76b876c'
20210728:14:55:04:016061 gpstop:mdw_ipv4:gpadmin-[INFO]:-Signalling all postmaster processes to reload
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s vacuum_cost_page_hit
Values on all segments are consistent
GUC          : vacuum_cost_page_hit
Master  value: 3
Segment value: 3
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -r vacuum_cost_page_hit
20210728:14:55:16:016113 gpconfig:mdw_ipv4:gpadmin-[INFO]:-completed successfully with parameters '-r vacuum_cost_page_hit'
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpstop -u
20210728:14:55:19:016187 gpstop:mdw_ipv4:gpadmin-[INFO]:-Starting gpstop with args: -u
20210728:14:55:19:016187 gpstop:mdw_ipv4:gpadmin-[INFO]:-Gathering information and validating the environment...
20210728:14:55:19:016187 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20210728:14:55:19:016187 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Segment details from master...
20210728:14:55:19:016187 gpstop:mdw_ipv4:gpadmin-[INFO]:-Greenplum Version: 'postgres (Greenplum Database) 6.16.0 build commit:5650be2b79197fed564dca8d734d10f2a76b876c'
20210728:14:55:19:016187 gpstop:mdw_ipv4:gpadmin-[INFO]:-Signalling all postmaster processes to reload
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s vacuum_cost_page_hit
Values on all segments are consistent
GUC          : vacuum_cost_page_hit
Master  value: 1
Segment value: 1
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s vacuum_cost_page_miss
Values on all segments are consistent
GUC          : vacuum_cost_page_miss
Master  value: 10
Segment value: 10
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ psql
psql (9.4.24)
Type "help" for help.

gpadmin=#
gpadmin=# show vacuum_cost_page_miss;
 vacuum_cost_page_miss
-----------------------
 10
(1 row)

gpadmin=#
gpadmin=# set vacuum_cost_page_miss = 20;
SET
gpadmin=# \q
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -c vacuum_cost_page_miss -v 15
20210728:15:00:05:016580 gpconfig:mdw_ipv4:gpadmin-[INFO]:-completed successfully with parameters '-c vacuum_cost_page_miss -v 15'
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpstop -u
20210728:15:00:14:016660 gpstop:mdw_ipv4:gpadmin-[INFO]:-Starting gpstop with args: -u
20210728:15:00:14:016660 gpstop:mdw_ipv4:gpadmin-[INFO]:-Gathering information and validating the environment...
20210728:15:00:14:016660 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20210728:15:00:14:016660 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Segment details from master...
20210728:15:00:14:016660 gpstop:mdw_ipv4:gpadmin-[INFO]:-Greenplum Version: 'postgres (Greenplum Database) 6.16.0 build commit:5650be2b79197fed564dca8d734d10f2a76b876c'
20210728:15:00:14:016660 gpstop:mdw_ipv4:gpadmin-[INFO]:-Signalling all postmaster processes to reload
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s vacuum_cost_page_miss
Values on all segments are consistent
GUC          : vacuum_cost_page_miss
Master  value: 15
Segment value: 15
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -r vacuum_cost_page_miss
20210728:15:00:26:016712 gpconfig:mdw_ipv4:gpadmin-[INFO]:-completed successfully with parameters '-r vacuum_cost_page_miss'
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpstop -u
20210728:15:00:29:016787 gpstop:mdw_ipv4:gpadmin-[INFO]:-Starting gpstop with args: -u
20210728:15:00:29:016787 gpstop:mdw_ipv4:gpadmin-[INFO]:-Gathering information and validating the environment...
20210728:15:00:29:016787 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20210728:15:00:29:016787 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Segment details from master...
20210728:15:00:29:016787 gpstop:mdw_ipv4:gpadmin-[INFO]:-Greenplum Version: 'postgres (Greenplum Database) 6.16.0 build commit:5650be2b79197fed564dca8d734d10f2a76b876c'
20210728:15:00:29:016787 gpstop:mdw_ipv4:gpadmin-[INFO]:-Signalling all postmaster processes to reload
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s vacuum_cost_page_miss
Values on all segments are consistent
GUC          : vacuum_cost_page_miss
Master  value: 10
Segment value: 10
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$

**Comment by fifthposition** [comment]
Docs story created.

**Comment by fifthposition** [comment]
@bala-cg I don't see `vacuum_freeze_min_age`, or a default value for it, in the example output here.

**Comment by bala-cg** [comment]
@fifthposition, Below is the example output.

Type "help" for help.

gpadmin=#
gpadmin=#
gpadmin=# show vacuum_freeze_min_age;
 vacuum_freeze_min_age
-----------------------
 50000000
(1 row)

gpadmin=# \q
[gpadmin@mdw ~]$ gpconfig -s vacuum_freeze_min_age
Values on all segments are consistent
GUC          : vacuum_freeze_min_age
Master  value: 50000000
Segment value: 50000000
[gpadmin@mdw ~]$
[gpadmin@mdw ~]$
[gpadmin@mdw ~]$
[gpadmin@mdw ~]$
[gpadmin@mdw ~]$ psql
psql (9.4.24)
Type "help" for help.

gpadmin=#
gpadmin=# set vacuum_freeze_min_age = 100000000;
SET
gpadmin=#
gpadmin=# \q
[gpadmin@mdw ~]$ gpconfig -c vacuum_freeze_min_age -v 100000000
20210818:12:46:38:015510 gpconfig:mdw:gpadmin-[INFO]:-completed successfully with parameters '-c vacuum_freeze_min_age -v 100000000'
[gpadmin@mdw ~]$
[gpadmin@mdw ~]$
[gpadmin@mdw ~]$ gpstop -arf
20210818:12:46:45:015616 gpstop:mdw:gpadmin-[INFO]:-Starting gpstop with args: -arf
20210818:12:46:45:015616 gpstop:mdw:gpadmin-[INFO]:-Gathering information and validating the environment...
20210818:12:46:45:015616 gpstop:mdw:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20210818:12:46:45:015616 gpstop:mdw:gpadmin-[INFO]:-Obtaining Segment details from master...
20210818:12:46:45:015616 gpstop:mdw:gpadmin-[INFO]:-Greenplum Version: 'postgres (Greenplum Database) 6.16.3 build commit:f245f5686a407beb99f46a9ac7e3b9152223724b'
20210818:12:46:45:015616 gpstop:mdw:gpadmin-[INFO]:-Commencing Master instance shutdown with mode='fast'
20210818:12:46:45:015616 gpstop:mdw:gpadmin-[INFO]:-Master segment instance directory=/gpdata/master/gpseg-1
20210818:12:46:45:015616 gpstop:mdw:gpadmin-[INFO]:-Attempting forceful termination of any leftover master process
20210818:12:46:45:015616 gpstop:mdw:gpadmin-[INFO]:-Terminating processes for segment /gpdata/master/gpseg-1
20210818:12:46:45:015616 gpstop:mdw:gpadmin-[INFO]:-Stopping master standby host smdw mode=fast
20210818:12:46:45:015616 gpstop:mdw:gpadmin-[INFO]:-Successfully shutdown standby process on smdw
20210818:12:46:45:015616 gpstop:mdw:gpadmin-[INFO]:-Targeting dbid [2, 3, 4, 5, 6, 7, 8, 9] for shutdown
20210818:12:46:45:015616 gpstop:mdw:gpadmin-[INFO]:-Commencing parallel primary segment instance shutdown, please wait...
20210818:12:46:45:015616 gpstop:mdw:gpadmin-[INFO]:-0.00% of jobs completed
20210818:12:46:46:015616 gpstop:mdw:gpadmin-[INFO]:-100.00% of jobs completed
20210818:12:46:46:015616 gpstop:mdw:gpadmin-[INFO]:-Commencing parallel mirror segment instance shutdown, please wait...
20210818:12:46:46:015616 gpstop:mdw:gpadmin-[INFO]:-0.00% of jobs completed
20210818:12:46:46:015616 gpstop:mdw:gpadmin-[INFO]:-100.00% of jobs completed
20210818:12:46:46:015616 gpstop:mdw:gpadmin-[INFO]:-----------------------------------------------------
20210818:12:46:46:015616 gpstop:mdw:gpadmin-[INFO]:-   Segments stopped successfully      = 8
20210818:12:46:46:015616 gpstop:mdw:gpadmin-[INFO]:-   Segments with errors during stop   = 0
20210818:12:46:46:015616 gpstop:mdw:gpadmin-[INFO]:-----------------------------------------------------
20210818:12:46:46:015616 gpstop:mdw:gpadmin-[INFO]:-Successfully shutdown 8 of 8 segment instances
20210818:12:46:46:015616 gpstop:mdw:gpadmin-[INFO]:-Database successfully shutdown with no errors reported
20210818:12:46:46:015616 gpstop:mdw:gpadmin-[INFO]:-Cleaning up leftover gpmmon process
20210818:12:46:46:015616 gpstop:mdw:gpadmin-[INFO]:-No leftover gpmmon process found
20210818:12:46:46:015616 gpstop:mdw:gpadmin-[INFO]:-Cleaning up leftover gpsmon processes
20210818:12:46:46:015616 gpstop:mdw:gpadmin-[INFO]:-No leftover gpsmon processes on some hosts. not attempting forceful termination on these hosts
20210818:12:46:46:015616 gpstop:mdw:gpadmin-[INFO]:-Cleaning up leftover shared memory
20210818:12:46:47:015616 gpstop:mdw:gpadmin-[INFO]:-Restarting System...
[gpadmin@mdw ~]$ gpconfig -s vacuum_freeze_min_age
Values on all segments are consistent
GUC          : vacuum_freeze_min_age
Master  value: 100000000
Segment value: 100000000
[gpadmin@mdw ~]$

**Comment by fifthposition** [comment]
Thank you, @bala-cg!
