### ISSUE TITLE
Command Need to run as sudo or root user

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#23]
Doc Version : 6.15
Chapter 2

1)
PDF Page No: 49
Sections:
XFS Mount Options
Disk I/O Settings

2)
PDF Page No: 51
Section:
SSH Connection Threshold
Topic:
To increase this connection threshold for your Greenplum Database system, update the SSH
MaxStartups and MaxSessions configuration parameters in one of the /etc/ssh/sshd_config or /
etc/sshd_config SSH daemon configuration files.

3)
PDF Page No: 52
Section:
SSH Connection Threshold
Topic:
1. Add the parameter to the GRUB_CMDLINE_LINUX line in the file parameter in /etc/default/grub.

4)
PDF Page No: 54
Section:
SSH Connection Threshold
Topic:
1. Create the gpadmin group and user.
This example creates the gpadmin group, creates the gpadmin user as a system account with a home
directory and as a member of the gpadmin group, and creates a password for the user.
3. (Optional) Grant sudo access to the gpadmin user.

5)
PDF Page No: 72
Section:
Installing the Python Data Science Module Package
Topic/Command:
yum install tk

6)
PDF Page No: 88
Topic/Command:
$ rm /usr/local/greenplum-db
$ ln -s /usr/local/greenplum-db-<new_version> /usr/local/greenplum-db

**Comment by VMWareJennyBeth** [comment]
@bala-cg 

I think I understand most of this issue. For the commands in sections numbered 2 through 6, the user must be root to run those commands. 

Not sure what's going on in section 1, as I don't see a command there. 

Thank you.

**Comment by bala-cg** [comment]
Hi Jenny,

/etc/fstab file is owned by root, so to edit this need to run as sudo or run by root user.

Thanks

**Comment by VMWareJennyBeth** [comment]
Thanks so much! Also saw your other clarification. Thanks for that as well.

**Comment by VMWareJennyBeth** [comment]
Docs story created.
