### ISSUE TITLE
writable_external_table_bufsize format not mentioned

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#230]
Page No : 1399

Issue: writable_external_table_bufsize format not mentioned in Doc description, hint given on setting via psql (HINT:  Valid units for this parameter are "kB", "MB", "GB", and "TB".).

Testing: 

[gpadmin@mdw_ipv4 ~]$ gpconfig -s writable_external_table_bufsize
Values on all segments are consistent
GUC          : writable_external_table_bufsize
Master  value: 64kB
Segment value: 64kB
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ psql
psql (9.4.24)
Type "help" for help.

gpadmin=#
gpadmin=#
gpadmin=# show writable_external_table_bufsize;
 writable_external_table_bufsize
---------------------------------
 64kB
(1 row)

gpadmin=#
gpadmin=#
gpadmin=# set writable_external_table_bufsize = 128kb;
ERROR:  syntax error at or near "kb"
LINE 1: set writable_external_table_bufsize = 128kb;
                                                 ^
gpadmin=#
gpadmin=#
gpadmin=# set writable_external_table_bufsize = '128kb';
ERROR:  invalid value for parameter "writable_external_table_bufsize": "128kb"
HINT:  Valid units for this parameter are "kB", "MB", "GB", and "TB".
gpadmin=#
gpadmin=#
gpadmin=# set writable_external_table_bufsize = '128kB';
SET
gpadmin=#
gpadmin=#
gpadmin=# \q
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s writable_external_table_bufsize^C
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ psql
psql (9.4.24)
Type "help" for help.

gpadmin=#
gpadmin=#
gpadmin=# \q
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -c writable_external_table_bufsize -v 128kB
20210728:16:07:11:023099 gpconfig:mdw_ipv4:gpadmin-[INFO]:-completed successfully with parameters '-c writable_external_table_bufsize -v 128kB'
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpstop -u
20210728:16:07:31:023215 gpstop:mdw_ipv4:gpadmin-[INFO]:-Starting gpstop with args: -u
20210728:16:07:31:023215 gpstop:mdw_ipv4:gpadmin-[INFO]:-Gathering information and validating the environment...
20210728:16:07:31:023215 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20210728:16:07:31:023215 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Segment details from master...
20210728:16:07:31:023215 gpstop:mdw_ipv4:gpadmin-[INFO]:-Greenplum Version: 'postgres (Greenplum Database) 6.16.0 build commit:5650be2b79197fed564dca8d734d10f2a76b876c'
20210728:16:07:31:023215 gpstop:mdw_ipv4:gpadmin-[INFO]:-Signalling all postmaster processes to reload
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s writable_external_table_bufsize
Values on all segments are consistent
GUC          : writable_external_table_bufsize
Master  value: 128kB
Segment value: 128kB
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -r writable_external_table_bufsize
20210728:16:07:44:023268 gpconfig:mdw_ipv4:gpadmin-[INFO]:-completed successfully with parameters '-r writable_external_table_bufsize'
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpstop -u
20210728:16:07:50:023346 gpstop:mdw_ipv4:gpadmin-[INFO]:-Starting gpstop with args: -u
20210728:16:07:50:023346 gpstop:mdw_ipv4:gpadmin-[INFO]:-Gathering information and validating the environment...
20210728:16:07:50:023346 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20210728:16:07:50:023346 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Segment details from master...
20210728:16:07:50:023346 gpstop:mdw_ipv4:gpadmin-[INFO]:-Greenplum Version: 'postgres (Greenplum Database) 6.16.0 build commit:5650be2b79197fed564dca8d734d10f2a76b876c'
20210728:16:07:50:023346 gpstop:mdw_ipv4:gpadmin-[INFO]:-Signalling all postmaster processes to reload
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s writable_external_table_bufsize
Values on all segments are consistent
GUC          : writable_external_table_bufsize
Master  value: 64kB
Segment value: 64kB
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -c writable_external_table_bufsize -v 128kb
20210728:16:07:59:023395 gpconfig:mdw_ipv4:gpadmin-[INFO]:-completed successfully with parameters '-c writable_external_table_bufsize -v 128kb'
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpstop -u
20210728:16:08:03:023471 gpstop:mdw_ipv4:gpadmin-[INFO]:-Starting gpstop with args: -u
20210728:16:08:03:023471 gpstop:mdw_ipv4:gpadmin-[INFO]:-Gathering information and validating the environment...
20210728:16:08:03:023471 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20210728:16:08:03:023471 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Segment details from master...
20210728:16:08:03:023471 gpstop:mdw_ipv4:gpadmin-[INFO]:-Greenplum Version: 'postgres (Greenplum Database) 6.16.0 build commit:5650be2b79197fed564dca8d734d10f2a76b876c'
20210728:16:08:03:023471 gpstop:mdw_ipv4:gpadmin-[INFO]:-Signalling all postmaster processes to reload
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s writable_external_table_bufsize
Values on all segments are consistent
GUC          : writable_external_table_bufsize
Master  value: 64kB
Segment value: 64kB
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -c writable_external_table_bufsize -v 128KB
20210728:16:11:05:023748 gpconfig:mdw_ipv4:gpadmin-[INFO]:-completed successfully with parameters '-c writable_external_table_bufsize -v 128KB'
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpstop -u
20210728:16:11:08:023824 gpstop:mdw_ipv4:gpadmin-[INFO]:-Starting gpstop with args: -u
20210728:16:11:08:023824 gpstop:mdw_ipv4:gpadmin-[INFO]:-Gathering information and validating the environment...
20210728:16:11:08:023824 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20210728:16:11:08:023824 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Segment details from master...
20210728:16:11:08:023824 gpstop:mdw_ipv4:gpadmin-[INFO]:-Greenplum Version: 'postgres (Greenplum Database) 6.16.0 build commit:5650be2b79197fed564dca8d734d10f2a76b876c'
20210728:16:11:08:023824 gpstop:mdw_ipv4:gpadmin-[INFO]:-Signalling all postmaster processes to reload
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s writable_external_table_bufsize
Values on all segments are consistent
GUC          : writable_external_table_bufsize
Master  value: 64kB
Segment value: 64kB
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -c writable_external_table_bufsize -v 128kB
20210728:16:11:20:023876 gpconfig:mdw_ipv4:gpadmin-[INFO]:-completed successfully with parameters '-c writable_external_table_bufsize -v 128kB'
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpstop -u
20210728:16:11:22:023951 gpstop:mdw_ipv4:gpadmin-[INFO]:-Starting gpstop with args: -u
20210728:16:11:22:023951 gpstop:mdw_ipv4:gpadmin-[INFO]:-Gathering information and validating the environment...
20210728:16:11:22:023951 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20210728:16:11:22:023951 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Segment details from master...
20210728:16:11:22:023951 gpstop:mdw_ipv4:gpadmin-[INFO]:-Greenplum Version: 'postgres (Greenplum Database) 6.16.0 build commit:5650be2b79197fed564dca8d734d10f2a76b876c'
20210728:16:11:22:023951 gpstop:mdw_ipv4:gpadmin-[INFO]:-Signalling all postmaster processes to reload
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s writable_external_table_bufsize
Values on all segments are consistent
GUC          : writable_external_table_bufsize
Master  value: 128kB
Segment value: 128kB
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$

**Comment by fifthposition** [comment]
Docs story created.
