### ISSUE TITLE
Internal references are not working

### ISSUE THREAD

**Issue by Govind-cg** [greenplum-db/sre-test#231]
Page no 1635

Issue : internal references are not working in pdf , but working in web pages/version.

Refer to **Allowing Connections to
Greenplum Database** for detailed information about configuring remote client access

**Managing Roles and Privileges** describes configuring Greenplum Database users and
granting privileges.

Page no 1636.

Issue : internal references are not working in pdf , but  in web pages/version.
• UNIX client hosts - **Configuring Kerberos for Linux Clients**
• Windows client hosts - **Configuring Kerberos for Windows Clients**

page no 1640

Issue : internal references are not working in pdf , but  in web pages/version.

Note: Refer to **the Client and Loader Utility Reference** for the client or load command to determine
tool support for specifying these connection parameters via options, configuration property names,
and/or environment variables.

**Comment by fifthposition** [comment]
Docs story created.
