### ISSUE TITLE
Issue numbers are missing in the resolved issues tables in Release Note.

### ISSUE THREAD

**Issue by ankit-cg** [greenplum-db/sre-test#235]
Location : https://gpdb.docs.pivotal.io/pxf/6-2/release/release-notes.html

Tables under the topic "Resolved Issues" issue numbers are not specified for some of the resolved issues.
This gives the impression that issue number is missing.
A better option would be to mention "NA" in the cell if there is no issue number.

**Comment by lisakowen** [comment]
i've updated the 6.3 release notes (private repository) to replace empty issue #s with N/A.  this will be visible in next releases.
