### ISSUE TITLE
(Optional) Grant sudo access to the gpadmin user. -- This should not be Optional step

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#24]
PDF Doc: 6.15
page no: 54
Topic/Step:
3. (Optional) Grant sudo access to the gpadmin user

- Issues with this step.
i) This step should not be optional, as we install GP and other packages using gpadmin user which need sudo access.
ii) This step need to be run as root user or sudo.
iii) by uncomment the %wheel group entry it will affect all wheel group users along with gpadmin, it can have adverse effect, see if it's possible to make this change only to gpadmin user.
=======================
3. (Optional) Grant sudo access to the gpadmin user.
On Red Hat or CentOS, run visudo and uncomment the %wheel group entry.
%wheel ALL=(ALL) NOPASSWD: ALL
Make sure you uncomment the line that has the NOPASSWD keyword.
Add the gpadmin user to the wheel group with this command.
# usermod -aG wheel gpadmin
=======================

**Comment by VMWareJennyBeth** [comment]
Docs story added.
