### ISSUE TITLE
Document should mention permission are set on all the hosts

### ISSUE THREAD

**Issue by ankit-cg** [greenplum-db/sre-test#244]
Link: https://gpdb.docs.pivotal.io/pxf/6-2/release/installing_pxf.html

Under "Installing the PXF Package" point 5 -> Set the ownership and permissions of the PXF installation files to enable access by the gpadmin user. This should mention that operation is performed on all the hosts.

Ex: Set the ownership and permissions of the PXF installation files to enable access by the gpadmin user on all the hosts.

**Comment by lisakowen** [comment]
made the requested update (private repository).  will show up in next pxf release.
