### ISSUE TITLE
Reword sentence regarding superuser permissions to install Java

### ISSUE THREAD

**Issue by venkata-cg** [greenplum-db/sre-test#248]
Ref: https://gpdb.docs.pivotal.io/pxf/6-2/using/install_java.html

Installing PXF -> Installing Java for PXF, the document mention as 
"Ensure that you have access to, or superuser permissions to install, Java 8 or Java 11 on each Greenplum Database host".

This sentence can be reworded to read better for example: "Ensure that you have superuser or sufficient permissions to install, Java 8 or Java 11 on each Greenplum Database host".

**Comment by lisakowen** [comment]
i the existing text is correct.  java 8 or 11 may already be installed on the host, so no superuser permissions are required in that case.
