### ISSUE TITLE
gpinitsystem wrong option -S (spread mirror configuration)

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#25]
PDF Doc: 6.15
page no: 65
Statement:
============
For a fully redundant system (with a standby master and a spread mirror configuration) include the -s
and -S options. For example:
$ gpinitsystem -c gpconfigs/gpinitsystem_config -h gpconfigs/
hostfile_gpinitsystem \
-s standby_master_hostname -S
============

Issue: Spread mirror configuration option is given wrong.

given : "-S"
Should be : --mirror-mode=spread

**Comment by VMWareJennyBeth** [comment]
Docs story opened.
