### ISSUE TITLE
Document should mention hadoop user 

### ISSUE THREAD

**Issue by ankit-cg** [greenplum-db/sre-test#251]
Link: https://gpdb.docs.pivotal.io/pxf/6-2/using/pxfuserimpers.html

Under the section "Configure the Hadoop User" Point 5 -> if you want to access Hadoop as the user hdfsuser1. This should mention as the same user as exists in the hadoop cluster also so as to avoid the confusion.

Ex: hdfsuser1 should exists in hadoop cluster.

**Comment by lisakowen** [comment]
fixed in https://github.com/greenplum-db/pxf/pull/782
