### ISSUE TITLE
Document should mention correct file name and path

### ISSUE THREAD

**Issue by ankit-cg** [greenplum-db/sre-test#252]
link:https://gpdb.docs.pivotal.io/pxf/6-2/using/access_hdfs.html

Under the section "Specifying the Profile" 
Command should use consistent example for file names and path

For ex: In this step should it says like : hdfs dfs -cat /data/exampledir/example.txt
but in the step it stating  like 'pxf://data/pxf_examples/pxf_hdfs_simple.txt?PROFILE this will create confusion

This gives the misleading that path is pointing to some where else but not to same path has mentioned in the above steps.

**Comment by lisakowen** [comment]
fixed in https://github.com/greenplum-db/pxf/pull/782
