### ISSUE TITLE
Left side navigation pane incorrect for installing pxf 

### ISSUE THREAD

**Issue by chandra-cg** [greenplum-db/sre-test#253]
https://gpdb.docs.pivotal.io/pxf/6-2/release/installing_pxf.html
When user clicks on " Installing PXF" on the left side navigation menu the fallowing sub topics should be listed below the heading 
in the navigation pane.
**Installing PXF**
- Prerequisites
- Download PXF
- Install PXF
- Next Steps
- Uninstalling PXF

**Comment by lisakowen** [comment]
we use the left navigation pane nesting for navigation to separate, related files, not for subtopics on the same page.  the right navigation pane is for intra-page navigation.
