### ISSUE TITLE
pxf.fragmenter-cache.expiration is missing in pxf-application.properties

### ISSUE THREAD

**Issue by venkata-cg** [greenplum-db/sre-test#254]
Ref: https://gpdb.docs.pivotal.io/pxf/6-2/using/config_files.html

Administering PXF -> About the PXF Configuration Files

The first table lists about the parameters present in pxf-application.properties file.

But when I checked after the PXF 6.2 installation, the parameter **pxf.fragmenter-cache.expiration** is missing in the /usr/local/pxf-gp6/**pxf-application.properties** file.

Please check and remove the parameter from the table if it is removed in PXF6.2 version.

**Comment by lisakowen** [comment]
the pxf.fragmenter-cache.expiration config property must be added to a the config file, it is not there by default because  the property is not likely to be set by most customers.

**Comment by venkata-cg** [comment]
https://gpdb.docs.pivotal.io/pxf/6-2/using/config_files.html

The document says  "The pxf-application.properties file exposes these PXF Service application configuration properties:"

As per the above statement, the properties file should contain all the properties mentioned in the table. But currently the pxf-application.properties file does not contain the pxf.fragmenter-cache.expiration config property at all.

Either the document should mention that the customer needs to add the property to the config file if it is not present or the property needs to be uncommented if it is already present and commented.

Please review.

**Comment by lisakowen** [comment]
the text in the paragraph after the table states "To change the value of a PXF Service application property, you may first need to add the property to, or uncomment the property in, the `pxf-application.properties` file before you can set the new value."  i think this covers the cases.
