### ISSUE TITLE
Reword sentence regarding out of memory condition

### ISSUE THREAD

**Issue by venkata-cg** [greenplum-db/sre-test#255]
Ref: https://gpdb.docs.pivotal.io/pxf/6-2/using/cfg_mem.html

Advanced PXF Configuration (Optional) - >Memory and Threading

In the first paragraph it is mentioned as "You may also choose to configure PXF to perform specific actions when it detects an out of memory condition".

It may be rephrased as "PXF can be configured to [Auto-kill the PXF Service](https://gpdb.docs.pivotal.io/pxf/6-2/using/cfg_mem.html#pxf-cfgoom-autokill) (enabled by default) or [Dump the Java heap](https://gpdb.docs.pivotal.io/pxf/6-2/using/cfg_mem.html#pxf-cfgoom-heapdump) (disabled by default) actions when it detects an out of memory condition".

**Comment by lisakowen** [comment]
fixed in https://github.com/greenplum-db/pxf/pull/782
