### ISSUE TITLE
'Level' word is truncated

### ISSUE THREAD

**Issue by venkata-cg** [greenplum-db/sre-test#256]
Ref: https://gpdb.docs.pivotal.io/pxf/6-2/using/cfg_logging.html

Advanced PXF Configuration (Optional) - >Logging

The document says "Enabling more verbose **service-** or client-level logging for PXF may aid troubleshooting efforts".

The line should be "Enabling more verbose **service-level** or client-level logging for PXF may aid troubleshooting efforts".

Ref:  https://gpdb.docs.pivotal.io/pxf/6-2/using/config_files.html

Administering PXF-> About the PXF Configuration Files- -> pxf-log4j2.xml

The  document says "The Logging advanced configuration topic describes how to enable more verbose **client-** and server-level logging for PXF".

In the above line as well, **level** is truncated after the word **clinet-**.

**Comment by lisakowen** [comment]
addressed in https://github.com/greenplum-db/pxf/pull/767. closing.
