### ISSUE TITLE
Reword sentence regarding reinstate info level logging

### ISSUE THREAD

**Issue by venkata-cg** [greenplum-db/sre-test#257]
Ref: https://gpdb.docs.pivotal.io/pxf/6-2/using/cfg_logging.html

Advanced PXF Configuration (Optional) -> Logging->Configuring for the Cluster

In the above section, the point number 6 says "Reinstate info-level logging - comment out the line or set the property value back to info, and then sync the update to and restart PXF on the cluster".

It can be rephrased as "Repeat the steps above with pxf.log.level=info to reinstate the logging level to info".

**Comment by lisakowen** [comment]
fixed in https://github.com/greenplum-db/pxf/pull/782
