### ISSUE TITLE
PXF Proofreading issues

### ISSUE THREAD

**Issue by chandra-cg** [greenplum-db/sre-test#258]
Administering PXF -> Monitoring PXF -> Filtering Metric Data 
https://gpdb.docs.pivotal.io/pxf/6-2/using/monitor_pxf.html

In monitoring PXF page mentioned "additional" word incorrectly as "aditional".

**Comment by indranil-cg** [comment]
On the page Administering PXF -> About the PXF Configuration Files
https://gpdb.docs.pivotal.io/pxf/6-2/using/config_files.html

The sub-topic [Modifying the PXF Configuration](https://gpdb.docs.pivotal.io/pxf/6-2/using/config_files.html#chg_config) should be moved to the top of the page (after the 4 bullet points and before [pxf-application.properties](https://gpdb.docs.pivotal.io/pxf/6-2/using/config_files.html#pxfappprops).

The user may miss out on this mandatory step if they don't scroll to the bottom of the page.

**Comment by indranil-cg** [comment]
On the page Administering PXF -> Configuring PXF
https://gpdb.docs.pivotal.io/pxf/6-2/using/instcfg_pxf.html

The first line says "Your Greenplum Database deployment consists of a master node, standby master, and multiple segment hosts.", the Greenplum database document refers to all as hosts, the sentence should read "Your Greenplum Database deployment consists of a master host, standby master host, and multiple segment hosts.". Need to be consistent with usage of nodes, hosts and instances.

**Comment by chandra-cg** [comment]
https://gpdb.docs.pivotal.io/pxf/6-2/using/reg_jar_depend.html#reg_native
Registering PXF Library Dependencies ->Registering a Native Library Dependency
Under step number 1 in "Registering a Native Library Dependency" page mentioned "colon-separated" word incorrectly as "colon-sperated".

**Comment by indranil-cg** [comment]
Installing PXF -> Installing Java for PXF (https://gpdb.docs.pivotal.io/pxf/6-2/using/install_java.html#proc)
Here we tell the user in the last step 5 "Note the `$JAVA_HOME` setting; you will need this value when you configure PXF."

Later in Administering PXF -> Configuring PXF (https://gpdb.docs.pivotal.io/pxf/6-2/using/instcfg_pxf.html)
In the second bullet for point 1, the text should refer to or give example of the value that was noted during Installing Java for PXF.

**Comment by indranil-cg** [comment]
Accessing Files on a Network File System with PXF -> Example: Reading From and Writing to a CSV File on a Network File System -> Read Data (https://gpdb.docs.pivotal.io/pxf/6-2/using/nfs_pxf.html#ex_read)

Step 2 "Display all rows of the `pxf_read_nfs` table:" contains a syntax error in the given SELECT query
Wrong: **SELECT** * **FROM** pxf_read_nfs **ORDER_BY** num_orders **DESC**;
Right: **SELECT** * **FROM** pxf_read_nfs **ORDER BY** num_orders **DESC**;

ORDER_BY replace with ORDER BY

**Comment by ankit-cg** [comment]
Accessing an SQL Database with PXF (JDBC) : https://gpdb.docs.pivotal.io/pxf/6-2/using/jdbc_pxf.html
This section mentions Microsoft SQL is supported in the first paragraph, however the document does not provide any configuration guidance or example usage of this connector

**Comment by ankit-cg** [comment]
Document mentions "The JDBC connector is a JDBC client. It can read data from and write data to SQL databases including MySQL, ORACLE, Microsoft SQL Server, DB2, PostgreSQL, Hive, and Apache Ignite."

However the document has example for Trino and not for MicrosoftSQL and  Apache Ignite.

**Comment by chandra-cg** [comment]
PXF Utility Reference->PXF-> Options
https://gpdb.docs.pivotal.io/pxf/6-2/using/ref/pxf.html

In pxf page mentioned "standby" word incorrectly as "standy".

**Comment by indranil-cg** [comment]
The table of data formats and profiles at https://gpdb.docs.pivotal.io/pxf/6-2/using/access_hdfs.html#hadoop_connectors
lists Avro as one of the supported formats for Hive. However in the table at https://gpdb.docs.pivotal.io/pxf/6-2/using/hive_pxf.html#hive_fileformats Avro is not listed even though example is given for the same later in the page.

**Comment by lisakowen** [comment]
addressed all of these except the requested example for microsoft sql server and apache ignite in https://github.com/greenplum-db/pxf/pull/767.  i created a story for the new examples.

**Comment by lisakowen** [comment]
closing.
