### ISSUE TITLE
gpinitsystem with -O option

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#26]
PDF Doc: 6.15
Page No: 65
Statement:
==========================
During a new cluster creation, you may use the -O output_configuration_file option to save
the cluster configuration details in a file. For example:
$ gpinitsystem -c gpconfigs/gpinitsystem_config -O gpconfigs/
config_template
This output file can be edited and used at a later stage as the input file of the -I option, to create a new
cluster or to recover from a backup. See gpinitsystem for further details.
==========================

Issue: With -O option the GP system will not be initialized, it will just create the file with cluster configuration details.

**Comment by VMWareJennyBeth** [comment]
Docs story opened.

**Comment by VMWareJennyBeth** [comment]
@bala-cg 
Hi, Bala, just want to make sure I understand. You're saying that with -O, content is written to a file, but the system is not actually initialized as it would normally be when a user calls gpinitsystem? 

Would you like this clarified in a "Note"?

Thank you.

**Comment by bala-cg** [comment]
Hi Jeeny,

- Yes your understanding is right, with -O option gpinitsysyem will not initialize GP DB, instead it will write the configuration to the file.
- It will be good if this is mentioned clearly in the statement.

[gpadmin@mdw_ipv4 ~]$ gpinitsystem -c gpinitsystem_config.ipv4 -O gp_config.out
20210423:04:24:36:007878 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Checking configuration parameters, please wait...
20210423:04:24:36:007878 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Reading Greenplum configuration file gpinitsystem_config.ipv4
20210423:04:24:36:007878 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Locale has not been set in gpinitsystem_config.ipv4, will set to default value
20210423:04:24:36:007878 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Locale set to en_US.utf8
20210423:04:24:37:007878 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-MASTER_MAX_CONNECT not set, will set to default value 250
20210423:04:24:37:007878 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Checking configuration parameters, Completed
20210423:04:24:37:007878 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Commencing multi-home checks, please wait...
..
20210423:04:24:37:007878 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Configuring build for standard array
20210423:04:24:37:007878 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Commencing multi-home checks, Completed
20210423:04:24:37:007878 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Building primary segment instance array, please wait...
......
20210423:04:24:39:007878 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Building group mirror array type , please wait...
......
20210423:04:24:40:007878 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Checking Master host
20210423:04:24:40:007878 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Checking new segment hosts, please wait...
............
20210423:04:24:48:007878 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Checking new segment hosts, Completed
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ psql
psql: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ ls -lrth gp_config.out
-rw-r--r--. 1 gpadmin users 933 Apr 23 04:24 gp_config.out
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ less gp_config.out
[gpadmin@mdw_ipv4 ~]$ cat gp_config.out
ARRAY_NAME="Greenplum DB"
TRUSTED_SHELL=ssh
CHECK_POINT_SEGMENTS=8
ENCODING=UNICODE
SEG_PREFIX=gpseg
HEAP_CHECKSUM=on
HBA_HOSTNAMES=0
QD_PRIMARY_ARRAY=mdw_ipv4~mdw_ipv4~5432~/data1/gpdb/master/gpseg-1~1~-1
declare -a PRIMARY_ARRAY=(
sdw1_ipv4~sdw1_ipv4~4000~/data1/gpdb/primary/gpseg0~2~0
sdw1_ipv4~sdw1_ipv4~4001~/data2/gpdb/primary/gpseg1~3~1
sdw1_ipv4~sdw1_ipv4~4002~/data3/gpdb/primary/gpseg2~4~2
sdw2_ipv4~sdw2_ipv4~4000~/data1/gpdb/primary/gpseg3~5~3
sdw2_ipv4~sdw2_ipv4~4001~/data2/gpdb/primary/gpseg4~6~4
sdw2_ipv4~sdw2_ipv4~4002~/data3/gpdb/primary/gpseg5~7~5
)
declare -a MIRROR_ARRAY=(
sdw2_ipv4~sdw2_ipv4~5000~/data1/gpdb/mirror/gpseg0~8~0
sdw2_ipv4~sdw2_ipv4~5001~/data2/gpdb/mirror/gpseg1~9~1
sdw2_ipv4~sdw2_ipv4~5002~/data3/gpdb/mirror/gpseg2~10~2
sdw1_ipv4~sdw1_ipv4~5000~/data1/gpdb/mirror/gpseg3~11~3
sdw1_ipv4~sdw1_ipv4~5001~/data2/gpdb/mirror/gpseg4~12~4
sdw1_ipv4~sdw1_ipv4~5002~/data3/gpdb/mirror/gpseg5~13~5
)
[gpadmin@mdw_ipv4 ~]$


Without -O option.

[gpadmin@mdw_ipv4 ~]$ gpinitsystem -c gpinitsystem_config.ipv4 -s smdw_ipv4
20210423:04:30:16:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Checking configuration parameters, please wait...
20210423:04:30:16:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Reading Greenplum configuration file gpinitsystem_config.ipv4
20210423:04:30:17:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Locale has not been set in gpinitsystem_config.ipv4, will set to default value
20210423:04:30:17:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Locale set to en_US.utf8
20210423:04:30:17:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-MASTER_MAX_CONNECT not set, will set to default value 250
20210423:04:30:17:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Checking configuration parameters, Completed
20210423:04:30:17:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Commencing multi-home checks, please wait...
..
20210423:04:30:17:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Configuring build for standard array
20210423:04:30:17:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Commencing multi-home checks, Completed
20210423:04:30:17:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Building primary segment instance array, please wait...
......
20210423:04:30:19:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Building group mirror array type , please wait...
......
20210423:04:30:21:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Checking Master host
20210423:04:30:21:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Checking new segment hosts, please wait...
............
20210423:04:30:28:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Checking new segment hosts, Completed
20210423:04:30:29:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Greenplum Database Creation Parameters
20210423:04:30:29:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:---------------------------------------
20210423:04:30:29:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Master Configuration
20210423:04:30:29:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:---------------------------------------
20210423:04:30:29:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Master instance name       = Greenplum DB
20210423:04:30:29:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Master hostname            = mdw_ipv4
20210423:04:30:29:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Master port                = 5432
20210423:04:30:29:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Master instance dir        = /data1/gpdb/master/gpseg-1
20210423:04:30:29:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Master LOCALE              = en_US.utf8
20210423:04:30:29:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Greenplum segment prefix   = gpseg
20210423:04:30:29:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Master Database            = gpadmin
20210423:04:30:29:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Master connections         = 250
20210423:04:30:29:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Master buffers             = 128000kB
20210423:04:30:29:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Segment connections        = 750
20210423:04:30:29:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Segment buffers            = 128000kB
20210423:04:30:29:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Checkpoint segments        = 8
20210423:04:30:29:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Encoding                   = UNICODE
20210423:04:30:29:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Postgres param file        = Off
20210423:04:30:29:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Initdb to be used          = /usr/local/greenplum-db-6.15.0/bin/initdb
20210423:04:30:29:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-GP_LIBRARY_PATH is         = /usr/local/greenplum-db-6.15.0/lib
20210423:04:30:29:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-HEAP_CHECKSUM is           = on
20210423:04:30:29:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-HBA_HOSTNAMES is           = 0
20210423:04:30:29:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Ulimit check               = Passed
20210423:04:30:29:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Array host connect type    = Single hostname per node
20210423:04:30:29:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Master IP address [1]      = ::1
20210423:04:30:29:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Master IP address [2]      = 10.0.27.54
20210423:04:30:29:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Master IP address [3]      = 2406:da1a:5a8:7f01:eff5:73aa:cdae:59d
20210423:04:30:29:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Master IP address [4]      = fe80::96:d3ff:feba:98ea
20210423:04:30:29:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Standby Master             = smdw_ipv4
20210423:04:30:29:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Number of primary segments = 3
20210423:04:30:29:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Standby IP address         = ::1
20210423:04:30:29:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Standby IP address         = 10.0.30.145
20210423:04:30:29:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Standby IP address         = 2406:da1a:5a8:7f01:39ca:9b12:680d:f707
20210423:04:30:29:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Standby IP address         = fe80::27:14ff:fed7:eb40
20210423:04:30:29:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Total Database segments    = 6
20210423:04:30:29:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Trusted shell              = ssh
20210423:04:30:29:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Number segment hosts       = 2
20210423:04:30:29:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Mirror port base           = 5000
20210423:04:30:29:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Number of mirror segments  = 3
20210423:04:30:29:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Mirroring config           = ON
20210423:04:30:29:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Mirroring type             = Group
20210423:04:30:29:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:----------------------------------------
20210423:04:30:29:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Greenplum Primary Segment Configuration
20210423:04:30:29:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:----------------------------------------
20210423:04:30:29:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-sdw1_ipv4        4000    sdw1_ipv4       /data1/gpdb/primary/gpseg0      2
20210423:04:30:29:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-sdw1_ipv4        4001    sdw1_ipv4       /data2/gpdb/primary/gpseg1      3
20210423:04:30:29:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-sdw1_ipv4        4002    sdw1_ipv4       /data3/gpdb/primary/gpseg2      4
20210423:04:30:29:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-sdw2_ipv4        4000    sdw2_ipv4       /data1/gpdb/primary/gpseg3      5
20210423:04:30:29:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-sdw2_ipv4        4001    sdw2_ipv4       /data2/gpdb/primary/gpseg4      6
20210423:04:30:29:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-sdw2_ipv4        4002    sdw2_ipv4       /data3/gpdb/primary/gpseg5      7
20210423:04:30:29:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:---------------------------------------
20210423:04:30:29:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Greenplum Mirror Segment Configuration
20210423:04:30:29:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:---------------------------------------
20210423:04:30:29:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-sdw2_ipv4        5000    sdw2_ipv4       /data1/gpdb/mirror/gpseg0       8
20210423:04:30:29:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-sdw2_ipv4        5001    sdw2_ipv4       /data2/gpdb/mirror/gpseg1       9
20210423:04:30:29:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-sdw2_ipv4        5002    sdw2_ipv4       /data3/gpdb/mirror/gpseg2       10
20210423:04:30:29:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-sdw1_ipv4        5000    sdw1_ipv4       /data1/gpdb/mirror/gpseg3       11
20210423:04:30:29:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-sdw1_ipv4        5001    sdw1_ipv4       /data2/gpdb/mirror/gpseg4       12
20210423:04:30:29:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-sdw1_ipv4        5002    sdw1_ipv4       /data3/gpdb/mirror/gpseg5       13

Continue with Greenplum creation Yy|Nn (default=N):
> y
20210423:04:30:30:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Building the Master instance database, please wait...
y
20210423:04:30:37:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Starting the Master in admin mode
20210423:04:30:38:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Commencing parallel build of primary segment instances
20210423:04:30:38:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Spawning parallel processes    batch [1], please wait...
......
20210423:04:30:39:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Waiting for parallel processes batch [1], please wait...
.............
20210423:04:30:52:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:------------------------------------------------
20210423:04:30:52:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Parallel process exit status
20210423:04:30:52:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:------------------------------------------------
20210423:04:30:52:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Total processes marked as completed           = 6
20210423:04:30:52:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Total processes marked as killed              = 0
20210423:04:30:52:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Total processes marked as failed              = 0
20210423:04:30:52:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:------------------------------------------------
20210423:04:30:52:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Deleting distributed backout files
20210423:04:30:52:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Removing back out file
20210423:04:30:52:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-No errors generated from parallel processes
20210423:04:30:52:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Restarting the Greenplum instance in production mode
20210423:04:30:52:014762 gpstop:mdw_ipv4:gpadmin-[INFO]:-Starting gpstop with args: -a -l /home/gpadmin/gpAdminLogs -m -d /data1/gpdb/master/gpseg-1
20210423:04:30:52:014762 gpstop:mdw_ipv4:gpadmin-[INFO]:-Gathering information and validating the environment...
20210423:04:30:52:014762 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20210423:04:30:52:014762 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Segment details from master...
20210423:04:30:52:014762 gpstop:mdw_ipv4:gpadmin-[INFO]:-Greenplum Version: 'postgres (Greenplum Database) 6.15.0 build commit:4e6288c9e9fca634b007a978fba3ce25aae26aed'
20210423:04:30:52:014762 gpstop:mdw_ipv4:gpadmin-[INFO]:-Commencing Master instance shutdown with mode='smart'
20210423:04:30:52:014762 gpstop:mdw_ipv4:gpadmin-[INFO]:-Master segment instance directory=/data1/gpdb/master/gpseg-1
20210423:04:30:52:014762 gpstop:mdw_ipv4:gpadmin-[INFO]:-Stopping master segment and waiting for user connections to finish ...
server shutting down
20210423:04:30:53:014762 gpstop:mdw_ipv4:gpadmin-[INFO]:-Attempting forceful termination of any leftover master process
20210423:04:30:53:014762 gpstop:mdw_ipv4:gpadmin-[INFO]:-Terminating processes for segment /data1/gpdb/master/gpseg-1
20210423:04:30:53:014785 gpstart:mdw_ipv4:gpadmin-[INFO]:-Starting gpstart with args: -a -l /home/gpadmin/gpAdminLogs -d /data1/gpdb/master/gpseg-1
20210423:04:30:53:014785 gpstart:mdw_ipv4:gpadmin-[INFO]:-Gathering information and validating the environment...
20210423:04:30:53:014785 gpstart:mdw_ipv4:gpadmin-[INFO]:-Greenplum Binary Version: 'postgres (Greenplum Database) 6.15.0 build commit:4e6288c9e9fca634b007a978fba3ce25aae26aed'
20210423:04:30:53:014785 gpstart:mdw_ipv4:gpadmin-[INFO]:-Greenplum Catalog Version: '301908232'
20210423:04:30:53:014785 gpstart:mdw_ipv4:gpadmin-[INFO]:-Starting Master instance in admin mode
20210423:04:30:53:014785 gpstart:mdw_ipv4:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20210423:04:30:53:014785 gpstart:mdw_ipv4:gpadmin-[INFO]:-Obtaining Segment details from master...
20210423:04:30:53:014785 gpstart:mdw_ipv4:gpadmin-[INFO]:-Setting new master era
20210423:04:30:53:014785 gpstart:mdw_ipv4:gpadmin-[INFO]:-Master Started...
20210423:04:30:53:014785 gpstart:mdw_ipv4:gpadmin-[INFO]:-Shutting down master
20210423:04:30:54:014785 gpstart:mdw_ipv4:gpadmin-[INFO]:-Commencing parallel segment instance startup, please wait...
20210423:04:30:54:014785 gpstart:mdw_ipv4:gpadmin-[INFO]:-Process results...
20210423:04:30:54:014785 gpstart:mdw_ipv4:gpadmin-[INFO]:-----------------------------------------------------
20210423:04:30:54:014785 gpstart:mdw_ipv4:gpadmin-[INFO]:-   Successful segment starts                                            = 6
20210423:04:30:54:014785 gpstart:mdw_ipv4:gpadmin-[INFO]:-   Failed segment starts                                                = 0
20210423:04:30:54:014785 gpstart:mdw_ipv4:gpadmin-[INFO]:-   Skipped segment starts (segments are marked down in configuration)   = 0
20210423:04:30:54:014785 gpstart:mdw_ipv4:gpadmin-[INFO]:-----------------------------------------------------
20210423:04:30:54:014785 gpstart:mdw_ipv4:gpadmin-[INFO]:-Successfully started 6 of 6 segment instances
20210423:04:30:54:014785 gpstart:mdw_ipv4:gpadmin-[INFO]:-----------------------------------------------------
20210423:04:30:54:014785 gpstart:mdw_ipv4:gpadmin-[INFO]:-Starting Master instance mdw_ipv4 directory /data1/gpdb/master/gpseg-1
20210423:04:30:54:014785 gpstart:mdw_ipv4:gpadmin-[INFO]:-Command pg_ctl reports Master mdw_ipv4 instance active
20210423:04:30:54:014785 gpstart:mdw_ipv4:gpadmin-[INFO]:-Connecting to dbname='template1' connect_timeout=15
20210423:04:30:54:014785 gpstart:mdw_ipv4:gpadmin-[INFO]:-No standby master configured.  skipping...
20210423:04:30:54:014785 gpstart:mdw_ipv4:gpadmin-[INFO]:-Database successfully started
20210423:04:30:54:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Completed restart of Greenplum instance in production mode
20210423:04:31:05:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Commencing parallel build of mirror segment instances
20210423:04:31:05:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Spawning parallel processes    batch [1], please wait...
......
20210423:04:31:05:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Waiting for parallel processes batch [1], please wait...
.........
20210423:04:31:14:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:------------------------------------------------
20210423:04:31:14:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Parallel process exit status
20210423:04:31:14:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:------------------------------------------------
20210423:04:31:14:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Total processes marked as completed           = 6
20210423:04:31:14:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Total processes marked as killed              = 0
20210423:04:31:14:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Total processes marked as failed              = 0
20210423:04:31:14:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:------------------------------------------------
20210423:04:31:15:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Starting initialization of standby master smdw_ipv4
20210423:04:31:15:016135 gpinitstandby:mdw_ipv4:gpadmin-[INFO]:-Validating environment and parameters for standby initialization...
20210423:04:31:15:016135 gpinitstandby:mdw_ipv4:gpadmin-[INFO]:-Checking for data directory /data1/gpdb/master/gpseg-1 on smdw_ipv4
20210423:04:31:15:016135 gpinitstandby:mdw_ipv4:gpadmin-[INFO]:------------------------------------------------------
20210423:04:31:15:016135 gpinitstandby:mdw_ipv4:gpadmin-[INFO]:-Greenplum standby master initialization parameters
20210423:04:31:15:016135 gpinitstandby:mdw_ipv4:gpadmin-[INFO]:------------------------------------------------------
20210423:04:31:15:016135 gpinitstandby:mdw_ipv4:gpadmin-[INFO]:-Greenplum master hostname               = mdw_ipv4
20210423:04:31:15:016135 gpinitstandby:mdw_ipv4:gpadmin-[INFO]:-Greenplum master data directory         = /data1/gpdb/master/gpseg-1
20210423:04:31:15:016135 gpinitstandby:mdw_ipv4:gpadmin-[INFO]:-Greenplum master port                   = 5432
20210423:04:31:15:016135 gpinitstandby:mdw_ipv4:gpadmin-[INFO]:-Greenplum standby master hostname       = smdw_ipv4
20210423:04:31:15:016135 gpinitstandby:mdw_ipv4:gpadmin-[INFO]:-Greenplum standby master port           = 5432
20210423:04:31:15:016135 gpinitstandby:mdw_ipv4:gpadmin-[INFO]:-Greenplum standby master data directory = /data1/gpdb/master/gpseg-1
20210423:04:31:15:016135 gpinitstandby:mdw_ipv4:gpadmin-[INFO]:-Greenplum update system catalog         = On
20210423:04:31:15:016135 gpinitstandby:mdw_ipv4:gpadmin-[INFO]:-Syncing Greenplum Database extensions to standby
20210423:04:31:15:016135 gpinitstandby:mdw_ipv4:gpadmin-[INFO]:-The packages on smdw_ipv4 are consistent.
20210423:04:31:15:016135 gpinitstandby:mdw_ipv4:gpadmin-[INFO]:-Adding standby master to catalog...
20210423:04:31:15:016135 gpinitstandby:mdw_ipv4:gpadmin-[INFO]:-Database catalog updated successfully.
20210423:04:31:15:016135 gpinitstandby:mdw_ipv4:gpadmin-[INFO]:-Updating pg_hba.conf file...
20210423:04:31:16:016135 gpinitstandby:mdw_ipv4:gpadmin-[INFO]:-pg_hba.conf files updated successfully.
20210423:04:31:19:016135 gpinitstandby:mdw_ipv4:gpadmin-[INFO]:-Starting standby master
20210423:04:31:19:016135 gpinitstandby:mdw_ipv4:gpadmin-[INFO]:-Checking if standby master is running on host: smdw_ipv4  in directory: /data1/gpdb/master/gpseg-1
20210423:04:31:24:016135 gpinitstandby:mdw_ipv4:gpadmin-[INFO]:-Cleaning up pg_hba.conf backup files...
20210423:04:31:25:016135 gpinitstandby:mdw_ipv4:gpadmin-[INFO]:-Backup files of pg_hba.conf cleaned up successfully.
20210423:04:31:25:016135 gpinitstandby:mdw_ipv4:gpadmin-[INFO]:-Successfully created standby master on smdw_ipv4
20210423:04:31:25:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Successfully completed standby master initialization
20210423:04:31:25:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Scanning utility log file for any warning messages
20210423:04:31:25:010547 gpinitsystem:mdw_ipv4:gpadmin-[WARN]:-*******************************************************
20210423:04:31:25:010547 gpinitsystem:mdw_ipv4:gpadmin-[WARN]:-Scan of log file indicates that some warnings or errors
20210423:04:31:25:010547 gpinitsystem:mdw_ipv4:gpadmin-[WARN]:-were generated during the array creation
20210423:04:31:25:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Please review contents of log file
20210423:04:31:25:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-/home/gpadmin/gpAdminLogs/gpinitsystem_20210423.log
20210423:04:31:25:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-To determine level of criticality
20210423:04:31:25:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-These messages could be from a previous run of the utility
20210423:04:31:25:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-that was called today!
20210423:04:31:25:010547 gpinitsystem:mdw_ipv4:gpadmin-[WARN]:-*******************************************************
20210423:04:31:25:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Greenplum Database instance successfully created
20210423:04:31:25:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-------------------------------------------------------
20210423:04:31:25:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-To complete the environment configuration, please
20210423:04:31:25:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-update gpadmin .bashrc file with the following
20210423:04:31:25:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-1. Ensure that the greenplum_path.sh file is sourced
20210423:04:31:25:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-2. Add "export MASTER_DATA_DIRECTORY=/data1/gpdb/master/gpseg-1"
20210423:04:31:25:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-   to access the Greenplum scripts for this instance:
20210423:04:31:25:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-   or, use -d /data1/gpdb/master/gpseg-1 option for the Greenplum scripts
20210423:04:31:25:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-   Example gpstate -d /data1/gpdb/master/gpseg-1
20210423:04:31:25:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Script log file = /home/gpadmin/gpAdminLogs/gpinitsystem_20210423.log
20210423:04:31:25:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-To remove instance, run gpdeletesystem utility
20210423:04:31:25:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Standby Master smdw_ipv4 has been configured
20210423:04:31:25:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-To activate the Standby Master Segment in the event of Master
20210423:04:31:25:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-failure review options for gpactivatestandby
20210423:04:31:25:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-------------------------------------------------------
20210423:04:31:25:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-The Master /data1/gpdb/master/gpseg-1/pg_hba.conf post gpinitsystem
20210423:04:31:25:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-has been configured to allow all hosts within this new
20210423:04:31:25:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-array to intercommunicate. Any hosts external to this
20210423:04:31:25:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-new array must be explicitly added to this file
20210423:04:31:25:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-Refer to the Greenplum Admin support guide which is
20210423:04:31:25:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-located in the /usr/local/greenplum-db-6.15.0/docs directory
20210423:04:31:25:010547 gpinitsystem:mdw_ipv4:gpadmin-[INFO]:-------------------------------------------------------
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ psql
psql (9.4.24)
Type "help" for help.

gpadmin=#

**Comment by VMWareJennyBeth** [comment]
Thanks, @bala-cg !
