### ISSUE TITLE
example step refers to older version of pxf installer

### ISSUE THREAD

**Issue by indranil-cg** [greenplum-db/sre-test#262]
https://gpdb.docs.pivotal.io/pxf/6-2/release/installing_pxf.html#install

under the topic "Installing the PXF Package", point 4a says to run
`gphost$ gpssh -e -v -f gphostfile "sudo rpm -Uvh /tmp/pxf-gp6-6.0.0-2.el7.x86_64.rpm"`

however the PXF 6.2 rpm file is pxf-gp6-**6.2.0**-2.el7.x86_64.rpm, the documented command should be updated with the correct filename for all the examples in the document.

**Comment by lisakowen** [comment]
updated the rpm/deb filenames  to reflect the release version in recently-released v6.2.3.  will carry this forward in future releases.  see https://greenplum.docs.pivotal.io/pxf/6-2/release/installing_pxf.html.
