### ISSUE TITLE
"synchronize" spelled incorrectly in 'About the PXF Configuration Files' page

### ISSUE THREAD

**Issue by chandra-cg** [greenplum-db/sre-test#263]
https://gpdb.docs.pivotal.io/pxf/6-2/using/config_files.html

About the PXF Configuration Files->Modifying the PXF Configuration

In Modifying the PXF Configuration page mentioned "synchronize" word incorrectly mentioned as "sychronize" .

**Comment by lisakowen** [comment]
addressed in https://github.com/greenplum-db/pxf/pull/767
