### ISSUE TITLE
OEL OS details missed in the "Introduction to PXF" page

### ISSUE THREAD

**Issue by chandra-cg** [greenplum-db/sre-test#265]
https://gpdb.docs.pivotal.io/pxf/6-2/using/intro_pxf.html
In the "Introduction to PXF page" from the  Supported platform section OEL 7.x OS details missed for PXF supported platform.
Document need to update OEL 7.x OS version for PXF supported platform.

https://gpdb.docs.pivotal.io/pxf/6-2/release/release-notes.html 
Where as in the released notes page under supported platform section OEL 7.x OS details mentioned under OS version column.

**Comment by lisakowen** [comment]
fixed in https://github.com/greenplum-db/pxf/pull/766.
