### ISSUE TITLE
PXF versions details not mentioned properly in 'Introduction to PXF' page

### ISSUE THREAD

**Issue by chandra-cg** [greenplum-db/sre-test#266]
https://gpdb.docs.pivotal.io/pxf/6-2/using/intro_pxf.html

Introduction to PXF->Supported Platforms->Hadoop
All PXF version are not updated in the PXF version column under supported platform section in Introduction to PXF page, there is a discrepancy when compare with release notes Supported platforms section.
https://gpdb.docs.pivotal.io/pxf/6-2/using/intro_pxf.html

**Comment by lisakowen** [comment]
the content on these two pages looks similar to me.  in the intro page, we do not list out every 6 version, specify 6.x.  and specify version 5.9+. i believe this info on the intro/relnotes pages is equivalent.   closing.
