### ISSUE TITLE
Bullet point not need under "filter pushdown to occur" section.

### ISSUE THREAD

**Issue by chandra-cg** [greenplum-db/sre-test#269]
https://gpdb.docs.pivotal.io/pxf/6-2/using/filter_push.html
Introduction to PXF->About PXF Filter Pushdown ->To summarize, all of the following criteria must be met for filter pushdown to occur 

Bullet point not required under filter pushdown summarize section, In the last bullet point we can add this below line for PXF Hive. Or
We can put as Note for refer to PXF Hive support.
"Refer to Hive Partition Pruning for more information about Hive support for this feature.

**Comment by lisakowen** [comment]
addressed ub https://github.com/greenplum-db/pxf/pull/767. closing.
