### ISSUE TITLE
PDF version of Greenplum document has some dead links.

### ISSUE THREAD

**Issue by vivek-cg** [greenplum-db/sre-test#27]
Found some dead links in the PDF version of Greenplum document which are working fine in the web view of the document.

Details:
VMware Tanzu™ Greenplum® 6.15 Documentation
[https://greenplum.docs.pivotal.io/6-15/install_guide/install_guide.html](url)

**Chapter 2 : Installing and Upgrading Greenplum**

Below, attaching the document in which the dead links have been highlighted.

[02 - Installing and Upgrading Greenplum - dead links.pdf](https://github.com/greenplum-db/sre-test/files/6277916/02.-.Installing.and.Upgrading.Greenplum.-.dead.links.pdf)

**Comment by VMWareJennyBeth** [comment]
Docs story opened.
