### ISSUE TITLE
PXF Cluster fails to start if custom log directory missing

### ISSUE THREAD

**Issue by indranil-cg** [greenplum-db/sre-test#273]
Administering PXF -> Configuring PXF -> Advanced PXF Configuration -> Logging -> Configuring the Log Directory
https://gpdb.docs.pivotal.io/pxf/6-2/using/cfg_logging.html#cfglogdir

The document says "To change the PXF log directory, you must update the $PXF_LOGDIR property in the pxf-env.sh configuration file, synchronize the configuration change to the Greenplum Database cluster, and then restart PXF".

The issue here is that if the user specified log directory does not exist on any one or more of the nodes then that node may prevent the cluster from starting successfully. The cluster sync command only copies the configuration files to all the nodes but does not create the user specified log directory. This directory must be created by the user manually on all the nodes in the Greenplum cluster.

In step number 2 under the topic "Configuring the Log Directory" a note should be added instructing the user to manually create the custom log directory (e.g. /new/log/dir) on all the nodes with the proper permissions. An example using gpssh may also be provided.

**Comment by lisakowen** [comment]
fixed in https://github.com/greenplum-db/pxf/pull/782
