### ISSUE TITLE
Usage of $PXF_HOME in document is misleading

### ISSUE THREAD

**Issue by indranil-cg** [greenplum-db/sre-test#277]
Location : https://gpdb.docs.pivotal.io/pxf/6-2/using/about_pxf_dir.html
Administering PXF -> About the PXF Installation and Configuration Directories

The document uses $PXF_HOME to refer to the PXF installation directory. There is even a note that says this environment variable is internal and echo $PXF_HOME will not return any value.

The document then goes on to refer to this (internal) environment variable to describe various configuration steps throughout the document e.g. to configure the connector copy `$PXF_HOME/templates/pxf-site.xml`. Another example in "Starting, Stopping, and Restarting PXF" says "`The procedures in this topic assume that you have added the $PXF_HOME/bin directory to your $PATH`"

Typically the user will then try to literally add "$PXF_HOME/bin" to $PATH which will not work since $PXF_HOME is not a real environment variable.

Since $PXF_HOME is only used in the document to refer to the PXF install directory, it should be changed to some other format that does not make is seem like an environment variable e.g. `<PXF_HOME>`

**Comment by lisakowen** [comment]
addressing in https://github.com/greenplum-db/pxf/pull/793
