### ISSUE TITLE
Bundled JDBC JAR file version

### ISSUE THREAD

**Issue by indranil-cg** [greenplum-db/sre-test#278]
Chapter: https://gpdb.docs.pivotal.io/pxf/6-2/using/jdbc_cfg.html
Topic: JDBC Driver JAR Registration

The PXF v6.2 document under the above topic says "PXF is bundled with the `postgresql-42.2.14.jar` JAR file.". However we have found that with PXF v6.2.0 the JDBC driver bundled is `postgresql-42.2.5.jar`. The latest version of the JAR available at https://jdbc.postgresql.org/download.html is v42.3.1. We are not able to find any version compatibility matrix indicating which versions of the jar would work with which version of Postgres against the given version of PXF.

**Comment by lisakowen** [comment]
pxf recently updated the bundled postgresql jar version to 42.3.3.  the docs will be updated via this PR:  https://github.com/greenplum-db/pxf/pull/765. closing.
