### ISSUE TITLE
Found some editorial issues in Greenplum Document v6.15.

### ISSUE THREAD

**Issue by vivek-cg** [greenplum-db/sre-test#28]
Found some editorial issues in Greenplum Document v6.15 (PDF version and web version).

Details: 
VMware Tanzu™ Greenplum® 6.15 Documentation
[https://greenplum.docs.pivotal.io/6-15/install_guide/install_guide.html](url)

**Chapter 2 : Installing and Upgrading Greenplum**

Below, attaching the document in which the issues have been highlighted and commented.

[02.-.Installing.and.Upgrading.Greenplum.-.Editorial.issues.pdf](https://github.com/greenplum-db/sre-test/files/6286395/02.-.Installing.and.Upgrading.Greenplum.-.Editorial.issues.pdf)

**Comment by VMWareJennyBeth** [comment]
why is openssh highlighted in list on page 26? Why shouldn't it be there? 

openldap
**• openssh**
• openssl

**Comment by bala-cg** [comment]
Responding to this.
Why is openssh highlighted in list on page 26? Why shouldn't it be there?
• openldap
• openssh
• openssl
Thank you

- please download the attached PDF file it will have all the bugs reported along with issues.

**Comment by VMWareJennyBeth** [comment]
Docs story opened.
