### ISSUE TITLE
Verification step after changing PXF host and or port

### ISSUE THREAD

**Issue by indranil-cg** [greenplum-db/sre-test#281]
Location: https://gpdb.docs.pivotal.io/pxf/6-2/using/cfghostport.html
Administering PXF -> Advanced PXF Configuration -> PXF Service Host and Port

A point number 5 should be added at the end of the chapter with instructions on how to check that PXF is indeed running on the reconfigured host and port, for example, by checking the url at `http://<PXF_HOST>:<PXF_PORT>/<endpoint>[/<name>]` as described in [Monitoring PXF](https://gpdb.docs.pivotal.io/pxf/6-2/using/monitor_pxf.html#status)

**Comment by lisakowen** [comment]
fixed in https://github.com/greenplum-db/pxf/pull/782
