### ISSUE TITLE
ORC/AVRO conversion tool download version not clear

### ISSUE THREAD

**Issue by ankit-cg** [greenplum-db/sre-test#285]
For Avro : https://gpdb.docs.pivotal.io/pxf/6-2/using/hdfs_avro.html#topic_tr3_dpgspk_15g_tsdata 
Under point (3) the document should provide the link to download site (https://dlcdn.apache.org/avro/avro-1.11.0/java/) and mention that latest version is to be downloaded, for ex: avro-<_latest_version_>.jar

For ORC: https://gpdb.docs.pivotal.io/pxf/6-2/using/hdfs_orc.html#read_example
Under point (2) the document directly links to the downloadable jar file (old version). Similar to avro  the document should provide the link to download site (https://repo1.maven.org/maven2/org/apache/orc/orc-tools/) and mention that latest version is to be downloaded, for ex: orc-tools-<_latest_version_>-uber.jar

**Comment by lisakowen** [comment]
fixed in https://github.com/greenplum-db/pxf/pull/782
