### ISSUE TITLE
export PGDATABASE value should be DB name

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#29]
PDF Page No : 67
Command: 
export PGDATABASE=default_login_database_name

Issue: export PGDATABASE value should be a DB name, as customers can copy the value directly and pate in .bashrc file, which can potentially make GP connectivity via psql from local.
solution: give the DB name to which user want to connect by default.
export PGDATABASE=gpadmin

**Comment by VMWareJennyBeth** [comment]
Docs story created.
