### ISSUE TITLE
Incorrect backup option specified

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#37]
Pdf page no: 164

- Incorrect backup option specified
For tables that might be dropped during a backup, you can exclude the tables from a backup with a
gpbackup table filtering option such as --exclude-table or **--exclude-schema**.

- should be
gpbackup table filtering option such as --exclude-table or **--exclude-table-file**

**Comment by VMWareJennyBeth** [comment]
Docs story created.
