### ISSUE TITLE
Editorial issues (Typo or Grammar or Duplicate or incorrect statement)

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#38]
pdf page no: 162
1)
Backup and Restore Overview
Greenplum Database supports parallel and non-parallel methods for backing up and restoring databases.
Parallel operations scale regardless of the number of segments in your system, because segment hosts
each write their data to local disk storage simultaneously. With non-parallel backup and restore operations,
the data must be sent over the network from the segments to the master, which writes **all of** the data to
its storage. In addition to restricting I/O to one host, non-parallel backup requires that the master have
sufficient local disk storage to store the entire database.

"all of" replace with "all"

2)
Non-Parallel Backup with pg_dump
The PostgreSQL pg_dump and pg_dumpall non-parallel backup utilities can be used to create a single
dump file on the master host that contains all data from all active segments.
The PostgreSQL non-parallel utilities should be used only for special cases. They are much slower than
using the Greenplum backup utilities since **all of** the data must pass through the master. Additionally, it is

 "all of" replace with "all"

3)
pdf page no:179

gprestore --backup-dir /backupdir --timestamp 20170914081205

- correct statement, as it refers to the backup created in before step.
gprestore --backup-dir /mybackup --timestamp 20170914081205

4)
pdf page no:179

The gpbackup output displays the timestamp of the backup on which the incremental backup is based.
In this example, the incremental backup is based on the backup with timestamp 20180802171642. The
backup 20180802171642 can be an incremental or full backup

gpbackup --dbname test --backup-dir /backups --leaf-partition-data --incremental

missing --from-timestamp 20180802171642

- correct statement

gpbackup --dbname test --backup-dir /backups --leaf-partition-data --incremental --from-timestamp 20180802171642

5)

pdf page no: 180

- Grammar mistake, "an" should be removed.

When restoring **an from** an incremental backup, you can specify the --verbose option to display
the backups that are used in the restore operation on the command line. For example, the following
gprestore command restores a backup using the timestamp 20180807092740, an incremental backup.
The output includes the backups that were used to restore the database data.

6)

pdf page no: 193

- Wrong path, in below statement.
3. Locate the test bench program in the gpbackup/master/plugins directory. For example:
ls gpbackup/master/plugins/plugin_test_bench.sh

Correct path:
ls gpbackup/plugins/plugin_test_bench.sh

7)

pdf page no: 763

- Given "a back up" instead of "restore"

gprestore can send status email notifications after **a back up** operation completes. You specify when the
utility sends the mail and the email recipients in a configuration file. See Configuring Email Notifications.

8)

pdf page no:  764

- Given "backup" instead of restore.

--exclude-schema-file file_name
Optional. Specifies a text file containing a list of schemas to exclude from the **backup**.

**Comment by VMWareJennyBeth** [comment]
Docs story created.
