### ISSUE TITLE
exclude/include file can contain trailing lines

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#39]
pdf page no: 170

- Statement not correct "and the file cannot contain trailing lines".

If you have a large number of schemas, you can list the schemas in a text file and specify the file with
the --include-schema-file or --exclude-schema-file options in a gpbackup command. Each
line in the file must define a single schema, **and the file cannot contain trailing lines**. For example, this
command uses a file in the gpadmin home directory to include a set of schemas.

tried with file having trailing lines it works.

**Comment by VMWareJennyBeth** [comment]
Doc story created.
