### ISSUE TITLE
GPCC Prerequisites "sudo" is missing in a command, which fails on that command 

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#4]
**KB Link**
https://gpcc.docs.pivotal.io/630/topics/install.html

$ source /usr/local/greenplum-db-<version>/greenplum_path.sh
$ gpssh -f <hostfile> 'sudo mkdir -p /usr/local/greenplum-cc-6.3.0; chown -R centos:centos /usr/local/greenplum-cc-6.3.0'
$ gpssh -f <hostfile> 'sudo ln -s /usr/local/greenplum-cc-6.3.0 /usr/local/greenplum-cc'

**Error**
[centos@mdw_ipv4 ~]$ gpssh -f gp_all_hosts_ipv4 'sudo mkdir -p /usr/local/greenplum-cc-6.3.0; chown -R centos:centos /usr/local/greenplum-cc-6.3.0'
[sdw2_ipv4] chown: changing ownership of ‘/usr/local/greenplum-cc-6.3.0’: Operation not permitted
[smdw_ipv4] chown: changing ownership of ‘/usr/local/greenplum-cc-6.3.0’: Operation not permitted
[sdw1_ipv4] chown: changing ownership of ‘/usr/local/greenplum-cc-6.3.0’: Operation not permitted
[ mdw_ipv4] chown: changing ownership of ‘/usr/local/greenplum-cc-6.3.0’: Operation not permitted
[centos@mdw_ipv4 ~]$

**- If we run the same with sudo it works.**
[centos@mdw_ipv4 ~]$ gpssh -f gp_all_hosts_ipv4 'sudo mkdir -p /usr/local/greenplum-cc-6.3.0; sudo chown -R centos:centos /usr/local/greenplum-cc-6.3.0'
[sdw1_ipv4]
[ mdw_ipv4]
[sdw2_ipv4]
[smdw_ipv4]
[centos@mdw_ipv4 ~]$

**Comment by VMWareJennyBeth** [comment]
Doc story created.
