### ISSUE TITLE
two commands given in one line which fails

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#40]
pdf page no :570

- Below step has to be in 2 lines

3. The program generates a key that is passphrase-protected; it does not accept a passphrase that is less
than four characters long. To remove the passphrase (and you must if you want automatic start-up of
the server), run the following command:

openssl rsa -in privkey.pem -out server.key rm privkey.pem

- correct command 
openssl rsa -in privkey.pem -out server.key
rm privkey.pem

**Comment by VMWareJennyBeth** [comment]
Docs story created.
