### ISSUE TITLE
An example psql command will sslmode will be helpful

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#41]
pdf page no : 571

- a psql example would be helpful used to connect using sslmode.

- sample example

[centos@ip-172-31-8-182 ~]$ psql --set=sslmode=require -d postgres -h 65.1.64.67 -p 5432 -U ssltest
Password for user ssltest:
psql (9.2.24, server 9.4.24)
WARNING: psql version 9.2, server version 9.4.
         Some psql features might not work.
SSL connection (cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256)
Type "help" for help.

postgres=>

**Comment by VMWareJennyBeth** [comment]
@bala-cg 
Hi,

Where, in the doc, is this? (I don't have your PDF, I just have the site on docs.pivotal.io). If you could just give me a section heading to search on that would be great. Thank you.

**Comment by VMWareJennyBeth** [comment]
Docs story created.

**Comment by bala-cg** [comment]
Hi Jenny,

In response to below comment.

==============
Hi,
Where, in the doc, is this? (I don't have your PDF, I just have the site on docs.pivotal.io). If you could just give me a section heading to search on that would be great. Thank you.
===================

- I felt if an example psql command using sslmode will be helpful before ending the topic in 572 page.
