### ISSUE TITLE
wrong command given to create a super user

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#42]
pdf page no : 255

- First the given command does not prompt " Shall the new role be a superuser? (y/n) y "

6. Create the gpadmin/admin Greenplum Database superuser role.
$ createuser gpadmin/admin
Shall the new role be a superuser? (y/n) y

- right commands for creating superuser are below

createuser gpadmin/admin3 -s
createuser gpadmin/admin2 --superuser

**Comment by VMWareJennyBeth** [comment]
Docs story created.

**Comment by VMWareJennyBeth** [comment]
@bala-cg 

Need clarification

Are you saying we should show EITHER createuser gpadmin/admin3 -s OR createuser gpadmin/admin2 --superuser?

Or are you saying we should show both?

**Comment by bala-cg** [comment]
Hi Jenny,

-  two issues here.

- Given Command
Create the gpadmin/admin Greenplum Database superuser role.
$ createuser gpadmin/admin
Shall the new role be a superuser? (y/n) y

1) First the given command does not prompt " Shall the new role be a superuser? (y/n) y "

2) To create superuser role below are 2 options, one of it can be mentioned.
createuser gpadmin/admin3 -s
createuser gpadmin/admin2 --superuser

**Comment by VMWareJennyBeth** [comment]
Hi, Bala!

Yes, I knew to remove the part about being prompted.
Thanks for clarifying that I only need to mention one of those command syntaxes

Many thanks!
