### ISSUE TITLE
Section need to run with sudo.

### ISSUE THREAD

**Issue by Govind-cg** [greenplum-db/sre-test#43]
PDF page 257 
Topic: Installing and Configuring a Kerberos KDC Server.
this section needs to run with sudo.

**Comment by VMWareJennyBeth** [comment]
Docs story created.

**Comment by VMWareJennyBeth** [comment]
@bala-cg 

Need clarification/specifics, as this is a large section. 

Do you mean that every command in this section should have sudo in front of it? (For example, kdb5_util create)? 

Some of these commands are already shown with the # prompt, which signals that the user is already root.

**Comment by bala-cg** [comment]
Hi Jeeny,

Yes (#) prompt is enough as it signals command run as root user.

**Comment by VMWareJennyBeth** [comment]
Fantastic, thanks Bala!
