### ISSUE TITLE
kerberos editorial issue

### ISSUE THREAD

**Issue by Govind-cg** [greenplum-db/sre-test#44]
PDF page 255.
- gpadmin misspelled as gadmin

 kadmin.local -q "ktadd -k gpdb-kerberos.keytab postgres/mdw@GPDB.KRB
**gadmin**/admin@GPDB.KRB"
Correct cmd is :
kadmin.local -q "ktadd -k gpdb-kerberos.keytab postgres/mdw@GPDB.KRB
**gpadmin**/admin@GPDB.KRB"

**Comment by VMWareJennyBeth** [comment]
Doc story added.
