### ISSUE TITLE
Editorial issues.

### ISSUE THREAD

**Issue by Govind-cg** [greenplum-db/sre-test#45]
Page no 109
Issue: space missing b/w ctid and system columns.
Given statement :
Each segment instance maintains its own values for
the system columns xmin, xmax, cmin, and cmax, as well as for the gp_segment_id and
**ctidsystem** columns.

Correct statement:
Each segment instance maintains its own values for
the system columns xmin, xmax, cmin, and cmax, as well as for the gp_segment_id and
**ctid system** columns

Page no 114
Issue: typo error
Table 13: Example Table with Updates
Issue: in Table 13  second entry of **sprocket** under item column misspelled as **sproket**.

Page no 115
Issue: typo error
Table 14: Example Table after VACUUM
Issue: in Table 14  second entry of **sprocket** under item column misspelled as **sproket**.

Page no 115
Issue: typo error
Table 15: Example Table with Wrapping XID
Issue: in Table 15  second entry of **sprocket** under item column misspelled as **sproket**.

Page no 127
Issue: typo error 
Given statement:
Greenplum Database version numbers and **they way** they change identify what has been modified from
one Greenplum Database release to the next.
Correct statement:
Greenplum Database version numbers and **the way** they change identify what has been modified from
one Greenplum Database release to the next.

Page no 142.
Issue:  Invalid command option.
there is no such option U with gpsto -U.It should be gpstop -u
Given command is  **gpstop -U** .
The correct command is **gpstop -u**

Page no 157 
Issue: typo error.
In figure 18.wherever we see gprecover , it should be replaced with gprecoverseg.

page no 221
Issue: duplicate "or" given, in below statement.

5. Check the cardinality of the join keys. If they have low cardinality, try to rewrite the query with different
joining columns **or or** additional filters on the tables to reduce the number of rows. These changes could
change the query semantics.

**Comment by VMWareJennyBeth** [comment]
Docs story created.
