### ISSUE TITLE
Wrong phrase/word used

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#46]
pdf page no : 124

- Issue: below statement "partition files" was given it should be partition tables.

When the ANALYZE command is run on a partitioned table, it analyzes each child leaf partition table, one at
a time. You can run ANALYZE on just new or changed partition **files** to avoid analyzing partitions that have
not changed.

pdf page no: 128

- Issue: "pg_hba.conf file" is mentioned two times, second entry can be removed.

Reloading Configuration File Changes Only
Reload changes to Greenplum Database configuration files without interrupting the system.
The gpstop utility can reload changes to the pg_hba.conf configuration file and to runtime parameters
in the master postgresql.conf file and **pg_hba.conf file** without service interruption. Active sessions
pick up changes when they reconnect to the database. Many server configuration parameters require a full
system restart (gpstop -r) to activate. For information about server configuration parameters, see the
Greenplum Database Reference Guide.

pdf page no : 128

- Issue: In below statement it would be meaningful if addressed Greenplum Database system instead of system. 

Reload configuration file changes without shutting down the **system** using the gpstop utility:

pdf page no: 129

Issue: incorrect statement, instead if "utility mode" it should be "maintenance mode".

3. After completing your administrative tasks, stop the master in **utility mode**. Then, restart it in production
mode.

page no: 243

-  Incorrect statement
Mark deleted rows in heap tables
so that the space they occupy
can be reused.

- correct statement
Clear/Reclaim space occupied deleted/updated rows in heap tables
so that the space they occupy can be reused.

**Comment by VMWareJennyBeth** [comment]
Docs story created.
