### ISSUE TITLE
gpactivatestandby command fails.

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#49]
pdf page no: 160 and 161

Issue: below command fails, works after setting the PGPORT. 

gpactivatestandby -d /data/master/gpseg-1

[gpadmin@mdw_ipv4 ~]$ gpactivatestandby -d /data1/gpdb/master/gpseg-1
20210423:17:20:43:006569 gpactivatestandby:mdw_ipv4:gpadmin-[CRITICAL]:-PGPORT environment variable not set.
[gpadmin@mdw_ipv4 ~]$

- Works when PGPOTR is set to 5432

[gpadmin@mdw_ipv4 ~]$ export PGPORT=5432
[gpadmin@mdw_ipv4 ~]$

Fix:

export PGPORT=5432
gpactivatestandby -d /data/master/gpseg-1

**Comment by VMWareJennyBeth** [comment]
Docs story created.
