### ISSUE TITLE
Steps given under wrong section

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#50]
pdf page no: 161

Issue and Fix: Below steps should be part of section "Restoring Master Mirroring After a Recovery" instead of "To restore the master and standby instances on original hosts(optional)"

To restore the master and standby instances on original hosts(optional)
To restore the master and standby instances on original hosts
(optional)
1. Ensure the original master host is in dependable running condition; ensure the cause of the original
failure is fixed.
2. On the original master host, move or remove the data directory, gpseg-1. This example moves the
directory to backup_gpseg-1:
$ mv /data/master/gpseg-1 /data/master/backup_gpseg-1
You can remove the backup directory once the standby is successfully configured.
3. Initialize a standby master on the original master host. For example, run this command from the current
master host, smdw:
$ gpinitstandby -s mdw
4. After the initialization completes, check the status of standby master, mdw. Run gpstate with the -f
option to check the standby master status:
$ gpstate -f

**Comment by VMWareJennyBeth** [comment]
@bala-cg 
Hi, Bala. 

I need some clarification.

Are you saying that just the first 4 steps should be added under the heading "Restore Master Mirroring after Recovery"  and then all 7 steps should remain under "To restore the master and standby instances on original hosts
(optional)"?

**Comment by VMWareJennyBeth** [comment]
@bala-cg Ping.

**Comment by bala-cg** [comment]
Hi Jenny,

- Yes steps 1 to 4 should be under "Restoring Master Mirroring After a Recovery" 
- And steps from 5 to 9 will be under "To restore the master and standby instances on original hosts (optional)"

**Comment by VMWareJennyBeth** [comment]
@bala-cg Thank you!!!

**Comment by VMWareJennyBeth** [comment]
Docs story created.
