### ISSUE TITLE
editorial and command issue.

### ISSUE THREAD

**Issue by Govind-cg** [greenplum-db/sre-test#51]
Page no 157 
Issue: typo error.
In figure 18.wherever we see gprecover , it should be replaced with gprecoverseg.

Page no 142.
Issue:  Invalid command option.
there is no such option U with gpsto -U.It should be gpstop -u
Given command is  **gpstop -U** .
The correct command is **gpstop -u**

**Comment by bala-cg** [comment]
Closing this issues, as it's consolidated under existing Editorial issues.
