### ISSUE TITLE
Activity not relevant to current document 

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#54]
Issue: Activity not relevant to current document (6.15), see if this can be removed.

Test the state of master mirroring
on a Greenplum Database 4.2 or
earlier cluster. If the value is "Not
Synchronized", raise an alert or
warning.
Recommended frequency: run
every 5 to 10 minutes
Severity: IMPORTANT

Execute the following query in the
postgres database:
SELECT summary_state
FROM gp_master_
mirroring;

Check the pg_log from the
master and standby master for
errors. If there are no unexpected
errors and the machines are up,
run the gpinitstandby utility
to bring the standby online. This
requires a database restart on
GPDB 4.2 and earlier.

**Comment by VMWareJennyBeth** [comment]
Docs story created.
