### ISSUE TITLE
Incorrect Recovery statement.

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#55]
Page no : 240

Issue: Incorrect Recovery statement.

Preferred Statement: try to start the start the DB on Original Master if the server is up and running, if that fails then try to activate stand by master as Master.

If this query fails the active
master may be down. Try again
several times and then inspect
the active master manually. If the
active master is down, reboot or
power cycle the active master to
ensure no processes remain on
the active master **and then trigger
the activation of the standby
master.**

**Comment by VMWareJennyBeth** [comment]
@bala-cg 
I'm not clear on what you're asking for here. Is this how you want the paragraph to read? 

"If this query fails, the active master may be down. Try to start the database on the original master if the server is up and running. If that fails, try to activate the standby master as master."

**Comment by VMWareJennyBeth** [comment]
Docs story created.
