### ISSUE TITLE
Given table does not exists

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#56]
page no :240

Issue: This query fails, as the table does not exists.

Given table : log_alert_history

Correct table : gpmetrics.gpcc_pg_log_history
correct query:

gpperfmon=# SELECT * FROM gpmetrics.gpcc_pg_log_history
  WHERE logseverity in('FATAL', 'ERROR') AND logtime > (now() - interval '15 minutes');
 logtime | loguser | logdatabase | logpid | logthread | loghost | logport | logsessiontime | logtransaction | logsession | logcmdcount | logsegment | logslice | logdistxact | loglocalxact | logsubx
act | logseverity | logstate | logmessage | logdetail | loghint | logquery | logquerypos | logcontext | logdebug | logcursorpos | logfunction | logfile | logline | logstack
---------+---------+-------------+--------+-----------+---------+---------+----------------+----------------+------------+-------------+------------+----------+-------------+--------------+--------
----+-------------+----------+------------+-----------+---------+----------+-------------+------------+----------+--------------+-------------+---------+---------+----------
(0 rows)

**Comment by VMWareJennyBeth** [comment]
Docs story created.

**Comment by VMWareJennyBeth** [comment]
This section and table were removed in the master branch (in anticipation of Greenplum 7. I will fix in 6.16 branch and backport.
