### ISSUE TITLE
Incorrect sequence of activities.

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#59]
Page No: 244

Issue : In page no : 235, it's mentioned REINDEX need to be performed first, then VACUUM and last ANALZE.
Here in 244 page it's given VACUUM first and then REINDEX and last ANALYZE.

Vacuum, reindex, and analyze
system catalogs to maintain an
efficient catalog.
Recommended frequency:
weekly, or more often if database
objects are created and dropped
frequently
1. VACUUM the system tables in
each database.
2. Run REINDEX SYSTEM in
each database, or use the
reindexdb command-line
utility with the -s option:
reindexdb -
s <database>
3. ANALYZE each of the system
tables:
analyzedb -s
pg_catalog -
d <database>

**Comment by VMWareJennyBeth** [comment]
Page 235 has incorrect order
correct order is vacuum, reindex, analyze

I will fix in docs.

**Comment by VMWareJennyBeth** [comment]
Docs story created.
