### ISSUE TITLE
Error while creating user defined type

### ISSUE THREAD

**Issue by Govind-cg** [greenplum-db/sre-test#60]
Page 291.

Issue: while creating type it fails with the below error.
ERROR:  function int33_in(cstring) does not exist.

Command.CREATE TYPE int33 (
internallength = 4,
input = int33_in,
output = int33_out,
alignment = int4,
default = 123,
passedbyvalue,
compresstype="quicklz",
blocksize=65536,
compresslevel=1
);

Fix: Need to create int33_in,int33_out functions before creating type.

**Comment by VMWareJennyBeth** [comment]
Docs story created.
