### ISSUE TITLE
Sequences only support USAGE, SELECT, and UPDATE privileges

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#61]
Page No:  268

Topic: Table 38: Object Privileges

Issue: Sequences only support USAGE, SELECT, and UPDATE privileges, for insert and delete it gives a waring.

gpadmin=# grant insert on sq1 to bala1;
WARNING:  sequence "sq1" only supports USAGE, SELECT, and UPDATE privileges
WARNING:  sequence "sq1" only supports USAGE, SELECT, and UPDATE privileges  (seg2 10.0.20.178:4000 pid=3086)
WARNING:  sequence "sq1" only supports USAGE, SELECT, and UPDATE privileges  (seg3 10.0.20.178:4001 pid=3087)
WARNING:  sequence "sq1" only supports USAGE, SELECT, and UPDATE privileges  (seg1 10.0.25.194:4001 pid=11825)
WARNING:  sequence "sq1" only supports USAGE, SELECT, and UPDATE privileges  (seg0 10.0.25.194:4000 pid=11824)

Given in table :Table 38: Object Privileges
Tables, Views, Sequences supported below privileges.
SELECT
INSERT
UPDATE
DELETE
RULE
ALL

**Comment by VMWareJennyBeth** [comment]
Corrected in the latest published version of this content. See https://greenplum.docs.pivotal.io/6-15/admin_guide/roles_privs.html"
