### ISSUE TITLE
Given query fails, when ran as given 

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#62]
Page no : 317

Issue: This query fails if copied and run as is with below error.

ERROR:  type modifier is not allowed for type "regclass"
LINE 14: AND d.refclassid = 'pg_class'::regclass

Given Query:
SELECT v.oid::regclass AS view,
ns.nspname AS schema,
-- view schema,
d.refobjid::regclass AS ref_object -- name of table
FROM pg_depend AS d
-- objects that depend on a table
JOIN pg_rewrite AS r
-- rules depending on a table
ON r.oid = d.objid
JOIN pg_class AS v
-- views for the rules
ON v.oid = r.ev_class
JOIN pg_namespace AS ns
-- schema information
ON ns.oid = v.relnamespace
WHERE v.relkind = 'v'
-- filter views only
-- dependency must be a rule depending on a relation
AND d.classid = 'pg_rewrite'::regclass
AND d.refclassid = 'pg_class'::regclass
-- referenced objects in pg_class
(tables and views)
AND d.deptype = 'n'
-- normal dependency
-- qualify object
AND ns.nspname NOT IN ('pg_catalog', 'information_schema', 'gp_toolkit')
-- system schemas
AND NOT (v.oid = d.refobjid) -- not self-referencing dependency
;

Reason:
Below line in query is in part of comment before it

AND d.refclassid = 'pg_class'::regclass -- referenced objects in pg_class
(tables and views)

Fix: comment this line.
AND d.refclassid = 'pg_class'::regclass -- referenced objects in pg_class
-- (tables and views)

**Comment by VMWareJennyBeth** [comment]
Docs story created.
