### ISSUE TITLE
pgsql_tmp folder is not present under database oid's

### ISSUE THREAD

**Issue by Govind-cg** [greenplum-db/sre-test#63]
Page no 324.

Issue: pgsql_tmp folder is not present under database oid's.

cmd : [gpadmin@mdw kend]$ gpssh -f ~/hosts -e \
"du -b /data[1-2]/primary/gpseg*/base/<OID>/pgsql_tmp/*" | \
grep -v "du -b" | sort | awk -F" " '{ arr[$1] = arr[$1] + $2 ; tot =
tot + $2 }; END \
{ for ( i in arr ) print "Segment node" i, arr[i], "bytes (" arr[i]/
(1024**3)" GB)"; \
print "Total", tot, "bytes (" tot/(1024**3)" GB)" }'

Correct path: it is there under the base folder.
[gpadmin@sdw1_ipv4 base]$ pwd
/data1/gpdb/primary/gpseg0/base
[gpadmin@sdw1_ipv4 base]$ ll
total 64
drwx------ 2 gpadmin users 12288 Apr 28 04:57 1
drwx------ 2 gpadmin users  8192 Apr 23 05:57 12815
drwx------ 2 gpadmin users  8192 Apr 28 04:57 12818
drwx------ 2 gpadmin users 45056 May  3 07:38 16384
drwx------ 2 gpadmin users     6 May  3 07:59 pgsql_tmp

page no 325:.

Issue: same as above.

cmd: $ gpssh -f ~/hosts -e
"ls -l /data[1-2]/primary/gpseg*/base/19979/pgsql_tmp/*"
| grep -i sort | awk '{sub(/base.*tmp\//, ".../", $10); print $1,$6,
$10}' | sort -k2 -n

Correct path: it is there under the base folder.
[gpadmin@sdw1_ipv4 base]$ pwd
/data1/gpdb/primary/gpseg0/base
[gpadmin@sdw1_ipv4 base]$ ll
total 64
drwx------ 2 gpadmin users 12288 Apr 28 04:57 1
drwx------ 2 gpadmin users  8192 Apr 23 05:57 12815
drwx------ 2 gpadmin users  8192 Apr 28 04:57 12818
drwx------ 2 gpadmin users 45056 May  3 07:38 16384
drwx------ 2 gpadmin users     6 May  3 07:59 pgsql_tmp

**Comment by VMWareJennyBeth** [comment]
Note to Jenny: 

This is correct syntax: 

/primary/gpseg*/base/pgsql_tmp

**Comment by VMWareJennyBeth** [comment]
Docs story created.
