### ISSUE TITLE
Editorial issue.

### ISSUE THREAD

**Issue by Govind-cg** [greenplum-db/sre-test#64]
1)
Page No: 119

misspelled statistics as stastistics.

2)
Page No: 125

misspelled statistics as statististics.
misspelled optimization as otpimization.

3)
Page No: 158

misspelled synchronizing  as sycnronizing.

4)
Page no 333.

Issue: type error.

Given statement:
The following table shows the concurrent UPDATE or DELETE commands that are **manged** by the Global
Deadlock Detector.

Correct statement:
The following table shows the concurrent UPDATE or DELETE commands that are ** managed** by the Global
Deadlock Detector.

**Comment by VMWareJennyBeth** [comment]
Docs story created.
