### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by Govind-cg** [greenplum-db/sre-test#65]
Page no 327.
Issue: "See Note" is dead in both pdf and web versions of the docementation.

Table 42: Lock Modes in Greenplum Database
Given statements:
1)
INSERT, COPY
See Note.
2)
DELETE, UPDATE, SELECT...FOR
UPDATE, REFRESH MATERIALIZED
VIEW CONCURRENTLY
See Note.

**Comment by VMWareJennyBeth** [comment]
Docs story created.
