### ISSUE TITLE
Greenplum configuration parameter "optimizer" is not consistent after it's set

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#66]
page no: 339 and 340

Issue: Greenplum configuration parameter "optimizer" is not consistent after it's set, and reload/restrat performed.

[gpadmin@mdw_ipv4 ~]$ gpconfig -c optimizer -v off
20210504:09:52:16:007824 gpconfig:mdw_ipv4:gpadmin-[INFO]:-completed successfully with parameters '-c optimizer -v off'
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpstop -u
20210504:09:52:22:007899 gpstop:mdw_ipv4:gpadmin-[INFO]:-Starting gpstop with args: -u
20210504:09:52:22:007899 gpstop:mdw_ipv4:gpadmin-[INFO]:-Gathering information and validating the environment...
20210504:09:52:22:007899 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20210504:09:52:22:007899 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Segment details from master...
20210504:09:52:22:007899 gpstop:mdw_ipv4:gpadmin-[INFO]:-Greenplum Version: 'postgres (Greenplum Database) 6.15.0 build commit:4e6288c9e9fca634b007a978fba3ce25aae26aed'
20210504:09:52:22:007899 gpstop:mdw_ipv4:gpadmin-[INFO]:-Signalling all postmaster processes to reload
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s optimizer
Values on all segments are consistent
GUC          : optimizer
Master  value: off
Segment value: off
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ psql
psql (9.4.24)
Type "help" for help.

gpadmin=#
gpadmin=# show optimizer;
 optimizer
-----------
 on
(1 row)

gpadmin=# select name,setting from pg_settings where name = 'optimizer';
   name    | setting
-----------+---------
 optimizer | on
(1 row)

gpadmin=#
gpadmin=#
gpadmin=# \q
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpstop -ar
20210504:09:54:17:008060 gpstop:mdw_ipv4:gpadmin-[INFO]:-Starting gpstop with args: -ar
20210504:09:54:17:008060 gpstop:mdw_ipv4:gpadmin-[INFO]:-Gathering information and validating the environment...
20210504:09:54:17:008060 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Greenplum Master catalog information
20210504:09:54:17:008060 gpstop:mdw_ipv4:gpadmin-[INFO]:-Obtaining Segment details from master...
20210504:09:54:17:008060 gpstop:mdw_ipv4:gpadmin-[INFO]:-Greenplum Version: 'postgres (Greenplum Database) 6.15.0 build commit:4e6288c9e9fca634b007a978fba3ce25aae26aed'
20210504:09:54:17:008060 gpstop:mdw_ipv4:gpadmin-[INFO]:-Commencing Master instance shutdown with mode='smart'
20210504:09:54:17:008060 gpstop:mdw_ipv4:gpadmin-[INFO]:-Master segment instance directory=/data1/gpdb/master/gpseg-1
20210504:09:54:17:008060 gpstop:mdw_ipv4:gpadmin-[INFO]:-Stopping master segment and waiting for user connections to finish ...
server shutting down
20210504:09:54:18:008060 gpstop:mdw_ipv4:gpadmin-[INFO]:-Attempting forceful termination of any leftover master process
20210504:09:54:18:008060 gpstop:mdw_ipv4:gpadmin-[INFO]:-Terminating processes for segment /data1/gpdb/master/gpseg-1
20210504:09:54:18:008060 gpstop:mdw_ipv4:gpadmin-[INFO]:-Stopping master standby host smdw_ipv4 mode=fast
20210504:09:54:18:008060 gpstop:mdw_ipv4:gpadmin-[INFO]:-Successfully shutdown standby process on smdw_ipv4
20210504:09:54:18:008060 gpstop:mdw_ipv4:gpadmin-[INFO]:-Targeting dbid [2, 6, 3, 7, 4, 8, 5, 9] for shutdown
20210504:09:54:19:008060 gpstop:mdw_ipv4:gpadmin-[INFO]:-Commencing parallel primary segment instance shutdown, please wait...
20210504:09:54:19:008060 gpstop:mdw_ipv4:gpadmin-[INFO]:-0.00% of jobs completed
20210504:09:54:19:008060 gpstop:mdw_ipv4:gpadmin-[INFO]:-100.00% of jobs completed
20210504:09:54:19:008060 gpstop:mdw_ipv4:gpadmin-[INFO]:-Commencing parallel mirror segment instance shutdown, please wait...
20210504:09:54:19:008060 gpstop:mdw_ipv4:gpadmin-[INFO]:-0.00% of jobs completed
20210504:09:54:19:008060 gpstop:mdw_ipv4:gpadmin-[INFO]:-100.00% of jobs completed
20210504:09:54:19:008060 gpstop:mdw_ipv4:gpadmin-[INFO]:-----------------------------------------------------
20210504:09:54:19:008060 gpstop:mdw_ipv4:gpadmin-[INFO]:-   Segments stopped successfully      = 8
20210504:09:54:19:008060 gpstop:mdw_ipv4:gpadmin-[INFO]:-   Segments with errors during stop   = 0
20210504:09:54:19:008060 gpstop:mdw_ipv4:gpadmin-[INFO]:-----------------------------------------------------
20210504:09:54:19:008060 gpstop:mdw_ipv4:gpadmin-[INFO]:-Successfully shutdown 8 of 8 segment instances
20210504:09:54:19:008060 gpstop:mdw_ipv4:gpadmin-[INFO]:-Database successfully shutdown with no errors reported
20210504:09:54:19:008060 gpstop:mdw_ipv4:gpadmin-[INFO]:-Cleaning up leftover gpmmon process
20210504:09:54:19:008060 gpstop:mdw_ipv4:gpadmin-[INFO]:-No leftover gpmmon process found
20210504:09:54:19:008060 gpstop:mdw_ipv4:gpadmin-[INFO]:-Cleaning up leftover gpsmon processes
20210504:09:54:19:008060 gpstop:mdw_ipv4:gpadmin-[INFO]:-No leftover gpsmon processes on some hosts. not attempting forceful termination on these hosts
20210504:09:54:19:008060 gpstop:mdw_ipv4:gpadmin-[INFO]:-Cleaning up leftover shared memory
20210504:09:54:20:008060 gpstop:mdw_ipv4:gpadmin-[INFO]:-Restarting System...
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ gpconfig -s optimizer
Values on all segments are consistent
GUC          : optimizer
Master  value: off
Segment value: off
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ psql
psql (9.4.24)
Type "help" for help.

gpadmin=#
gpadmin=# select name,setting from pg_settings where name = 'optimizer';
   name    | setting
-----------+---------
 optimizer | on
(1 row)

gpadmin=# show optimizer;
 optimizer
-----------
 on
(1 row)
gpadmin=#
[gpadmin@mdw_ipv4 ~]$ grep optimizer= $MASTER_DATA_DIRECTORY/postgresql.conf | grep -v "#"
optimizer=off

**Comment by VMWareJennyBeth** [comment]
Docs story created.

**Comment by mperezfuster** [comment]
Yes I am using 6.15 as well:

```
[gpadmin@pxfcluster-m library]$ grep optimizer= $MASTER_DATA_DIRECTORY/postgresql.conf | grep -v "#"
optimizer=off

[gpadmin@pxfcluster-m library]$ gpconfig -s optimizer
Values on all segments are consistent
GUC          : optimizer
Master  value: off
Segment value: off

[gpadmin@pxfcluster-m library]$ psql -c "show optimizer;"
 optimizer 
-----------
 off
(1 row)

[gpadmin@pxfcluster-m library]$  psql -c "select name,setting from pg_settings where name = 'optimizer';"
   name    | setting 
-----------+---------
 optimizer | off
(1 row)

**Comment by bala-cg** [comment]
- Thanks for the update, if you don't see this issue, it seems to be inconsistent and you can take a call on it and close it.

**Comment by mperezfuster** [comment]
Thanks @bala-cg!
