### ISSUE TITLE
Incorrect create table statement with range partition

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#67]
Page No : 343

-  Given statement.
CREATE TABLE sales(order_id int, item_id int, amount numeric(15,2),
date date, yr_qtr int)
range partitioned by yr_qtr;

This query fails with below error.

gpadmin=# CREATE TABLE sales(order_id int, item_id int, amount numeric(15,2), date date, yr_qtr int)
gpadmin-#  range partitioned by yr_qtr;
ERROR:  syntax error at or near "range"
LINE 2:  range partitioned by yr_qtr;

- Possible Correct Query.

 CREATE TABLE sales(order_id int, item_id int, amount numeric(15,2), date date, yr_qtr int)
 PARTITION BY RANGE (yr_qtr) (start (201501) INCLUSIVE end (201504) INCLUSIVE,
start (201601) INCLUSIVE end (201604) INCLUSIVE,
start (201701) INCLUSIVE end (201704) INCLUSIVE,
start (201801) INCLUSIVE end (201804) INCLUSIVE,
start (201901) INCLUSIVE end (201904) INCLUSIVE,
start (202001) INCLUSIVE end (202004) INCLUSIVE);

**Comment by VMWareJennyBeth** [comment]
Docs story created.
