### ISSUE TITLE
Explain Query plan differs from what's mentioned

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#68]
Page No : 348

Issue: Explain Query plan differs from what's mentioned.

- Given Comment:

• When GPORCA generates the query plan, the setting optimizer=on and GPORCA version are
displayed at the end of the query plan. For example.
Settings: optimizer=on
Optimizer status: Pivotal Optimizer (GPORCA) version 1.584
When Greenplum Database falls back to the Postgres Planner to generate the plan, the setting
optimizer=on and Postgres query optimizer are displayed at the end of the query plan. For
example.
**Settings: optimizer=on
Optimizer status: Postgres query optimizer**
When the server configuration parameter OPTIMIZER is off, these lines are displayed at the end of a
query plan.
Settings: optimizer=off
Optimizer status: Postgres query optimizer

- actual EXPLAIN query plan just displays.

 Optimizer: Postgres query optimizer
(or)
 Optimizer: Pivotal Optimizer (GPORCA)

gpadmin=#
gpadmin=# explain select * from tab1, tab10 where tab1.generate_series= tab10.col1;
                                            QUERY PLAN
---------------------------------------------------------------------------------------------------
 Gather Motion 4:1  (slice2; segments: 4)  (cost=0.00..912.59 rows=1 width=8)
   ->  Hash Join  (cost=0.00..912.59 rows=1 width=8)
         Hash Cond: (tab1.generate_series = tab10.col1)
         ->  Seq Scan on tab1  (cost=0.00..435.68 rows=250000 width=4)
         ->  Hash  (cost=431.00..431.00 rows=1 width=4)
               ->  Broadcast Motion 4:4  (slice1; segments: 4)  (cost=0.00..431.00 rows=1 width=4)
                     ->  Seq Scan on tab10  (cost=0.00..431.00 rows=1 width=4)
 **Optimizer: Pivotal Optimizer (GPORCA)**
(8 rows)

gpadmin=#
gpadmin=#
gpadmin=# set optimizer=off;
SET
gpadmin=#
gpadmin=#
gpadmin=# explain select * from tab1, tab10 where tab1.generate_series= tab10.col1;
                                           QUERY PLAN
-------------------------------------------------------------------------------------------------
 Gather Motion 4:1  (slice2; segments: 4)  (cost=1.11..18603.31 rows=20 width=8)
   ->  Hash Join  (cost=1.11..18603.31 rows=5 width=8)
         Hash Cond: (tab1.generate_series = tab10.col1)
         ->  Seq Scan on tab1  (cost=0.00..11102.00 rows=250000 width=4)
         ->  Hash  (cost=1.06..1.06 rows=1 width=4)
               ->  Broadcast Motion 4:4  (slice1; segments: 4)  (cost=0.00..1.06 rows=1 width=4)
                     ->  Seq Scan on tab10  (cost=0.00..1.01 rows=1 width=4)
 **Optimizer: Postgres query optimizer**
(8 rows)

gpadmin=#

**Comment by VMWareJennyBeth** [comment]
Docs story created.
