### ISSUE TITLE
"select * from " missing

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#69]
Page No : 389, 390

Issue: "select * from " missing, in below statement.

json_extract_
path('{"f2":
{"f3":1},"f4":
{"f5":99,"f6":"foo"}}','f4')

json_extract_
path_text('{"f2":
{"f3":1},"f4":
{"f5":99,"f6":"foo"}}','f4',
'f6')

json_object_
keys('{"f1":"abc","f2":
{"f3":"a",
"f4":"b"}}')

json_
typeof('-123.4')

- Complete statements.

gpadmin=# select * from json_extract_path('{"f2":{"f3":1},"f4":{"f5":99,"f6":"foo"}}','f4');
  json_extract_path
----------------------
 {"f5":99,"f6":"foo"}
(1 row)

gpadmin=# select * from json_extract_path_text('{"f2":{"f3":1},"f4":{"f5":99,"f6":"foo"}}','f4','f6');
 json_extract_path_text
------------------------
 foo
(1 row)

gpadmin=# select * from json_object_keys('{"f1":"abc","f2":{"f3":"a","f4":"b"}}');
 json_object_keys
------------------
 f1
 f2
(2 rows)

gpadmin=# select * from json_typeof('-123.4');
 json_typeof
-------------
 number
(1 row)

**Comment by VMWareJennyBeth** [comment]
Docs story created.
