### ISSUE TITLE
Incorrect Insert statement.

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#70]
Page no: 417

Issue: Insert statement fails with below error.

gpadmin=# INSERT INTO aliases VALUES('a','c');
ERROR:  invalid input syntax for integer: "a"

Given Statement:
CREATE TABLE aliases (id int, t
tsquery, s tsquery);
INSERT INTO aliases VALUES('a',
'c');

Possible Correct insert statement.
INSERT INTO aliases VALUES(1,'a','c');

**Comment by VMWareJennyBeth** [comment]
Docs story created.
