### ISSUE TITLE
Incorrect Output mentioned in doc

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#71]
Page No : 426, 427

Issue: Incorrect Output for below mentioned queries in doc.

- Given:
SELECT plainto_tsquery('supernova star');
plainto_tsquery
-----------------
'sn'
SELECT to_tsvector('supernova star');
to_tsvector
-------------
'sn':1

SELECT to_tsquery('''supernova star''');
to_tsquery
------------
'sn'

SELECT plainto_tsquery('supernova star');
plainto_tsquery
-----------------------------
'sn' & 'supernova' & 'star'

-  Actual Output:

gpadmin=# SELECT plainto_tsquery('supernova star');
   plainto_tsquery
----------------------
 'supernova' & 'star'
(1 row)

gpadmin=# SELECT to_tsvector('supernova star');
      to_tsvector
------------------------
 'star':2 'supernova':1
(1 row)

gpadmin=# SELECT to_tsquery('''supernova star''');
      to_tsquery
----------------------
 'supernova' & 'star'
(1 row)

gpadmin=# SELECT plainto_tsquery('supernova star');
   plainto_tsquery
----------------------
 'supernova' & 'star'
(1 row)

**Comment by VMWareJennyBeth** [comment]
Docs story created.
