### ISSUE TITLE
gp_external_enable_exec server configuration parameter change need DB restart to take affect

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#72]
Page No : 506

Issue: Not mention of the DB restart is required for gp_external_enable_exec server configuration parameter change to take affect.

Topic/Statement:
There is a security risk associated with allowing external tables to execute OS commands or
scripts. To disable the use of EXECUTE in web and writable external table definitions, set the
gp_external_enable_exec server configuration parameter to off in your master postgresql.conf
file:
gp_external_enable_exec = off

**Comment by VMWareJennyBeth** [comment]
Docs story created.
