### ISSUE TITLE
Configuration file content sequence not proper

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#73]
Page No : 458

- The Configuration file that gets generated has secret first and then accessid , unlike other configuration files where accessid given first and then secret.

[gpadmin@mdw_ipv4 ~]$ gpcheckcloud -t > ./mytest_s3.config
[gpadmin@mdw_ipv4 ~]$
[gpadmin@mdw_ipv4 ~]$ cat mytest_s3.config
[default]
**secret = "aws secret"
accessid = "aws access id"**
threadnum = 4
chunksize = 67108864
low_speed_limit = 10240
low_speed_time = 60
encryption = true

**Comment by VMWareJennyBeth** [comment]
Docs story created.

**Comment by VMWareJennyBeth** [comment]
Sorry, @bala-cg 

I can't find this section. Are you sure it's page 458?

**Comment by VMWareJennyBeth** [comment]
@bala-cg 

So are you wanting a change in the docs or not? 

Thanks,
Jenny

**Comment by bala-cg** [comment]
Yes, the change should be in this command "gpcheckcloud" code I believe.
As below command generates the config file.

 gpcheckcloud -t > ./mytest_s3.config

**Comment by fifthposition** [comment]
Docs story created.

**Comment by mperezfuster** [comment]
@bala-cg this doesn't look like a Docs change. Maybe @lij55 's team would be more appropriate?

**Comment by bala-cg** [comment]
Yes this is not a Doc change, nor it fails, Just that the config file generated has secret(password) first and accessid(username).

**Comment by fifthposition** [comment]
@bala-cg Is the request that we add text in the docs to emphasize that the generated file has secret first, and then username?

**Comment by bala-cg** [comment]
Hi,

This is logged as feedback, there's no issue.

Below command generates a config file which has secret first and then accessid, and as we are used to write username and then password, it would be good to the config file gets generated accessid first and then secrete. 

gpcheckcloud -t > ./mytest_s3.config

**Comment by zhaorui20005** [comment]
The print sequence of 'secret' and 'access_id' has been adjusted in master branch in this commit: https://github.com/greenplum-db/gpdb/commit/301d05aefa28af87cba1081d4a9dfcd7cba0c17c
