### ISSUE TITLE
dead links.

### ISSUE THREAD

**Issue by Govind-cg** [greenplum-db/sre-test#75]
Page no 427.

Issue: dead link.

Given statement.
The standard Greenplum Database distribution does not include any Ispell configuration files. Dictionaries
for a large number of languages are available from Ispell. Also, some more modern dictionary file formats
are supported — MySpell (OO < 2.0.1) and Hunspell (OO >= 2.0.2). A large list of dictionaries is available
on the OpenOffice Wiki.

correct statement: bold one is a dead link (needs to fix).
The standard Greenplum Database distribution does not include any Ispell configuration files. Dictionaries
for a large number of languages are available from **Ispell**. Also, some more modern dictionary file formats
are supported — MySpell (OO < 2.0.1) and Hunspell (OO >= 2.0.2). A large list of dictionaries is available
on the OpenOffice Wiki.

Page no 453
Issue: dead link.

Given statement:  
For detailed information about the architecture of and using PXF, refer to the Greenplum Platform
Extension Framework (PXF) documentation.

correct statement: bold one is a dead link (needs to fix).
For detailed information about the architecture of and using PXF, refer to t**he Greenplum Platform
Extension Framework (PXF)** documentation.

Page no 484.
Issue: dead link.

Given statement.
You can create readable and writable external tables with the Greenplum Platform Extension
Framework (PXF), and use these tables to load data into, or offload data from, Greenplum Database.
For information about using PXF, refer to Accessing External Data with PXF.

correct statement: bold one is a dead link (needs to fix).
You can create readable and writable external tables with the Greenplum Platform Extension
Framework (PXF), and use these tables to load data into, or offload data from, Greenplum Database.
For information about using PXF, refer to **Accessing External Data with PXF**.

page no 492.

Issue: dead link.

Given statement:
For detailed information about the architecture of and using PXF, refer to the Greenplum Platform
Extension Framework (PXF) documentation.

correct statement: bold one is a dead link (needs to fix).
For detailed information about the architecture of and using PXF, refer to **the Greenplum Platform
Extension Framework (PXF)** documentation.

Page no  504.

Issue: dead link.
Given statement.
Use the CREATE WRITABLE EXTERNAL TABLE command to define the external table and specify
the location and format of the output files. See Using the Greenplum Parallel File Server (gpfdist) for
instructions on setting up gpfdist for use with an external table and Accessing External Data with PXF
for instructions on setting up PXF for use with an external table

correct statement: bold one is a dead link (needs to fix).
Use the CREATE WRITABLE EXTERNAL TABLE command to define the external table and specify
the location and format of the output files. See Using the Greenplum Parallel File Server (gpfdist) for
instructions on setting up gpfdist for use with an external table and **Accessing External Data with PXF**
for instructions on setting up PXF for use with an external table

**Comment by fifthposition** [comment]
Docs story created.

**Comment by mperezfuster** [comment]
@bala-cg I am double checking these links, they should all be already corrected except the first one (Ispell). I will fix this one but the rest are referring to PXF and these are working fine now. Let me know if I missed anything.

**Comment by bala-cg** [comment]
@Govind-cg , can you check this and revert back?

**Comment by Govind-cg** [comment]
Hi @mperezfuster ,
I have re-checked, above links are not working in pdf. attaching pdf for your reference.

**Comment by mperezfuster** [comment]
Thanks!
