### ISSUE TITLE
dead links

### ISSUE THREAD

**Issue by Govind-cg** [greenplum-db/sre-test#76]
Page no 558.

Issue: dead link.

Given statement:
Accessing a Kerberized Hadoop Cluster
You can use the Greenplum Platform Extension Framework (PXF) to read or write external tables
referencing files in a Hadoop file system. If the Hadoop cluster is secured with Kerberos ("Kerberized"),
you must configure Greenplum Database and PXF to allow users accessing external tables to authenticate
with Kerberos. Refer to Configuring PXF for Secure HDFS for the procedure to perform this setup.

Correct statement: bold one is dead link( needs to fix).
Accessing a Kerberized Hadoop Cluster
You can use the Greenplum Platform Extension Framework (PXF) to read or write external tables
referencing files in a Hadoop file system. If the Hadoop cluster is secured with Kerberos ("Kerberized"),
you must configure Greenplum Database and PXF to allow users accessing external tables to authenticate
with Kerberos. Refer to **Configuring PXF for Secure HDFS** for the procedure to perform this setup.

**Comment by fifthposition** [comment]
Docs story created.
