### ISSUE TITLE
Not mentioned reload (gpstop -u) step after changing pg_hba.conf file

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#77]
Page No : 581

Statement/Topic:

The gpmon database role is a superuser. In a secure or production environment, it may be desirable to
restrict the gpmon user to just the gpperfmon database. Do this by editing the gpmon host entry in the
pg_hba.conf file and changing all in the database field to gpperfmon:
local gpperfmon gpmon md5
host gpperfmon gpmon 127.0.0.1/28 md5
host gpperfmon gpmon ::1/128 md5

Fix/Solution: "gpstop -u" reload is required to get the changes affect done to pg_hba.conf file.

**Comment by fifthposition** [comment]
Docs story created.
