### ISSUE TITLE
Given command fails

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#79]
Page No : 586

- This command fails:
gplogfilter -n 3 /gpdata/gp*/pg_log/gpdb*.csv

- Below commands work
- Display only Primary segment logs.
gplogfilter -n 3 /data?/gpdb/primary/gpseg?/pg_log/gpdb*.csv

- Display all segment logs (Primary and Mirror) segment logs.
gplogfilter -n 3 /data?/gpdb/*/gpseg?/pg_log/gpdb*.csv

**Comment by fifthposition** [comment]
Docs story created.
