### ISSUE TITLE
Incorrect sequence of maintenance steps.

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#87]
Page No : 635

Given Topic/Statement:
===========
These are Greenplum Database system catalog maintenance steps.
1. Perform a REINDEX on the system catalog tables to rebuild the system catalog indexes. This removes
bloat in the indexes and improves VACUUM performance.
Note: When performing REINDEX on the system catalog tables, locking will occur on the
tables and might have an impact on currently running queries. You can schedule the REINDEX
operation during a period of low activity to avoid disrupting ongoing business operations.
2. Perform a VACUUM on system catalog tables.
3. Perform an ANALYZE on the system catalog tables to update the table statistics.
===========

Correct sequence of steps.
1)Vacuum
2)Reindex
3)Analyze

- Same applies for below section:

These are steps for intensive system catalog maintenance.
1. Stop all catalog activity on the Greenplum Database system.
2. Perform a REINDEX on the system catalog tables to rebuild the system catalog indexes. This removes
bloat in the indexes and improves VACUUM performance.
3. Perform a VACUUM FULL on the system catalog tables. See the following Note.
4. Perform an ANALYZE on the system catalog tables to update the catalog table statistics.

**Comment by fifthposition** [comment]
Docs story created.
