### ISSUE TITLE
Given Command not recommended and fails

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#90]
Page No : 640

Issue: Given Command not recommended and fails

Given Statement:
=================
External tables have no statistics to inform the optimizer. You can set rough estimates for the number
of rows and disk pages for the external table in the pg_class system catalog with a statement like the
following:

UPDATE pg_class SET reltuples=400000, relpages=400
WHERE relname='myexttable';
=================

- We should not directly perform any DML operation on any system catalog tables, it fails with below error.

gpadmin=# UPDATE pg_class SET reltuples=400000, relpages=400
gpadmin-# WHERE relname='myexttable';
ERROR:  permission denied: "pg_class" is a system catalog
gpadmin=#

- If we have to do this, use below steps, advised to consult Greenplum product support team and run below steps.

gpadmin=# set allow_system_table_mods=on;
SET
gpadmin=# UPDATE pg_class SET reltuples=400000, relpages=400
WHERE relname='myexttable';
UPDATE 0
gpadmin=#

**Comment by fifthposition** [comment]
Docs story created.
