### ISSUE TITLE
Unrelated commands following statement

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#94]
Page No : 642

Issue: Unrelated commands following statement

- Statement and Commands:
Note: We strongly recommend that customers change their passwords after initial setup.
cd /etc
chown root:root passwd shadow group gshadow
chmod 644 passwd group
chmod 400 shadow gshadow

Page No : 643

Issue: Duplicate and unrelated content, can be remove, commands same as above.

cd /etc
chown root:root passwd shadow group gshadow
chmod 644 passwd group
chmod 400 shadow gshadow

**Comment by fifthposition** [comment]
Docs story created.
