### ISSUE TITLE
Editorial Issue

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#96]
Page No: 607

1)
Issue: cryptographic misspelled as crytographic.

2)
Issue: Grammar mistake.
Given
database. .
To be.
database.

Page No : 613

Issue: missing space.
Given
See How to Read Explain Plansfor information about operators.
To Be
See How to Read Explain Plans for information about operators.

Page No : 631

Issue: statistics misspelled stastistics.

Page No:  643

Unwanted space.
Given
pam_ unix
To Be
pam_unix

**Comment by fifthposition** [comment]
Docs story created.
