### ISSUE TITLE
Missing Step CREATE EXTENSION for a database.

### ISSUE THREAD

**Issue by bala-cg** [greenplum-db/sre-test#97]
Page No 648

- Before step 2, it's better to enable pgcrypto extension for the DB with example.
 [gpadmin@mdw_ipv4 ~]$  psql -d mydb -c 'CREATE EXTENSION pgcrypto'
CREATE EXTENSION

Given Statement:
2. Create a table called userssn and insert some sensitive data, social security numbers for Bob and
Alice, in this example. Paste the public.key contents after "dearmor(".

**Comment by fifthposition** [comment]
Docs story created.
