### ISSUE TITLE
Dead links/references

### ISSUE THREAD

**Issue by Govind-cg** [greenplum-db/sre-test#99]
Page no 604.

Issue: Dead link.

Given statement:
See Setting the Greenplum Recommended OS Parameters and Memory and Resource Management with
Resource Queues.

Correct statement: bold one should have the correct reference.
See **Setting the Greenplum Recommended OS Parameters** and Memory and Resource Management with
Resource Queues.

Page no 606.

Issue: Dead link.

Given statement:
See System Monitoring and Maintenance, Query Profiling and Monitoring Greenplum Database Log Files.

Correct statement: bold one should have the correct reference.
See System Monitoring and Maintenance, **Query Profiling** and Monitoring Greenplum Database Log Files.

Page no 609

Issue: Dead link.

Given statement:
See the recommended OS parameter settings in the Greenplum Database Installation Guide for further
details.

Correct statement: bold one should have the correct reference.
See the **recommended OS parameter settings** in the Greenplum Database Installation Guide for further
details.

Page no 610

Issue: Dead link.

Given statement:
See the recommended OS parameter settings in the Greenplum Database Installation Guide for further
details.

Correct statement: bold one should have the correct reference.
See the **recommended OS parameter settings** in the Greenplum Database Installation Guide for further
details.

**Comment by fifthposition** [comment]
Docs story created.
